### PR TITLE
fix the crummy busybox flags code

### PR DESCRIPTION
**Pull request by rminnich**
All the nonsense is gone and flag handling is sane.

Basic idea is to create per-package FlagSet variable per for flags,
then rewrite all usages of the flag package to use the per-package
variable.

I've been testing this and it's working extremely well.

Let me know if you see an issue. The code is far better than it
was.

### CODE REVIEW

**Comment by rminnich** [comment]
Ryan should be pleased.

**Comment by rminnich** [comment]
me again. This one is easy, I hope.

**Comment by rminnich** [comment]
tested and it works wonderfully well.

**Comment by hugelgupf** [comment]
This is waay better. Thanks!

**Pull request merged**
