### PR TITLE
[roadmap item] Add nonewline flag to cmds/core/readlink

### PR DESCRIPTION
**Pull request by TimRots**
This PR adds an optional -n flag to cmds/core/readlink which removes newline delimiter from readLink() output

Signed-off-by: Tim Rots <tim.rots@protonmail.ch>

### CODE REVIEW

**Comment by TimRots** [comment]
> could we just leave off putting the newline in the first place? It would be nice to avoid more flags.

May I suggest to update [roadmap.md](https://github.com/u-root/u-root/blob/master/roadmap.md) to make wanted features more clear for people, less involved, who want to make small contributions to this awesome project.

**Comment by TimRots** [comment]
> could we just leave off putting the newline in the first place? It would be nice to avoid more flags.

Thank you for having a look at this PR. Would you suggest not adding any additional flags at all?

**Comment by TimRots** [comment]
Would you like me to close this PR?

**Comment by hugelgupf** [comment]
I think this is okay to have, especially because elvish sucks when there isn't a newline (elvish will override the last line of output of a command if it doesn't have a newline at the end...)

**Pull request merged**
