### PR TITLE
dhclient: typo fix.

### PR DESCRIPTION
**Pull request by 10000TB**
Signed-off-by: David Hu <xuehaohu@google.com>

### CODE REVIEW

**Comment by 10000TB** [comment]
Learnt sth new

**Comment by 10000TB** [comment]
Make sense after you explained it

**Comment by hugelgupf** [comment]
I'm gonna take it as is actually since I don't think it's that important in the comment. Doesn't add value

**Comment by 10000TB** [comment]
Okay

But in general, I think less acronyms and be as specific as possible in
comments is more helpful and make the meaning of comment more accessible

**Comment by 10000TB** [comment]
merge :) ?

**Pull request merged**
