### PR TITLE
remove busybox tool

### PR DESCRIPTION
**Pull request by rminnich**
Yes, it worked, on occasion, and it was a fun ride, but what is was doing
was impossible to do in go in the general case. A pity, that, since it produced
very compact binaries.

Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>

### CODE REVIEW

**Comment by rminnich** [comment]
you shoulda been pr #200

**Comment by rjoleary** [comment]
This is the beginning of a new era...

**Comment by hugelgupf** [comment]
Kill it with fire. :)

**Comment by rminnich** [comment]
"The sun is out - the sky is blue there's not a cloud to spoil the view but it's raining - raining in my heart"

**Comment by rminnich** [comment]
I Just had a conversation, at gri's suggestion, with Russ about busybox mode and models. I just found out today I needed something like busybox mode for another memory-constrained system. We talked about ways to get busy-box-like sytems using the linker. But after a minute he proposed an idea based on source to source transformation. The idea he proposed is *exactly* what we're doing here: rewrite commands from package main to a package, rename init in the package to Init, and main to Main, only call the Init and Main you need to call.

Sure, it's not perfect, there are issues you need to be aware of, but there's no universal solution to this problem. There are some pretty good non-universal solutions, and this is one of them. Will it work for everything? No. Will it work for many things? Yes. Do we have a usable alternative that is as good at putting a lot of commands into a small footprint? No. So, I want to bring this back. We need it and I can't get a much better endorsement for how it works than Russ.

Also when I mentioned people had some concerns about doing this type of source to source transformation he said he'd be interested in hearing them.

**Pull request merged**
