### PR TITLE
Use new vmtest, move tests to Github Actions, move to Go 1.21

### PR DESCRIPTION
**Pull request by hugelgupf**
* All tests except tamago/tinygo are moved to Github actions, with one config for all of them
* Everything moves to Go 1.21, except arm integration tests which for some reason only pass on 1.20.
* Migrate to https://github.com/hugelgupf/vmtest.
* Remove pkg/vmtest, pkg/qemu, other unused code due to migration.

### CODE REVIEW

**Comment by rminnich** [comment]
fantastic. What might it take to get tamago over?

**Comment by MDr164** [comment]
Looks already quite good. The failed test seems to be either caused by an oom situation or a timeout as the test process got killed by the OS. In case we run into oom we might get around it by setting GOMEMLIMIT, in case of a timeout maybe increase it and see if something changes. Though it fails only after about 8 mins which is quite fast.

**Comment by hugelgupf** [comment]
The failing test is due to timeout. I'm working on it with https://github.com/hugelgupf/vmtest/pull/58 and https://github.com/hugelgupf/vmtest/pull/60

**Comment by hugelgupf** [comment]
> fantastic. What might it take to get tamago over?

Probably not much, but it's already a monster PR.

**Review by rminnich — APPROVED** [review]
quite amazing. 

I'm thinking it's time to let the tcz command go away. 

Given all this work you've done, I hesitate to ask, but I think I ought to: could vmtest go in the u-root project, i.e. github.com/u-root/vmtest, or do you want it to stay in hugelgupf. I can understand if you'd prefer to keep it where it is. Just checking, as it is so central to u-root.

**Review by MDr164 — APPROVED** [review]
Just minor stuff in the yaml, all in all lgtm

**Pull request merged**
