### PR TITLE
.circleci/config.yml: use uroottest/test-image-amd64:latest

### PR DESCRIPTION
**Pull request by TimRots**
This PR updates .circleci/config.yml to use
uroottest/test-image-amd64:latest which uses QEMU v4.2.0

Signed-off-by: Tim Rots <tim.rots@protonmail.ch>

### CODE REVIEW

**Comment by hugelgupf** [comment]
I've thought about doing the "latest" thing in the past, but @rjoleary brought up the good point that this means we cannot easily go back in time, so to speak.

With the explicit version number, you can check out a commit from 10 days ago and know exactly which Docker image its tests ran under. With `latest`, that's a lot harder.

**Comment by TimRots** [comment]
Fair points.

Would it be possible to (help) push a v3.2.11 version of the image to docker hub, at this moment the most recent image is tagged 'latest' instead of using explicit versioning.

**Comment by rjoleary** [comment]
I pushed a test-image-amd64-v3.2.11 tag which should trigger a build and we'll see a new image appear here in around 30 minutes: https://hub.docker.com/r/uroottest/test-image-amd64/tags

**Comment by TimRots** [comment]
Updated the PR to use v3.2.11 accordingly.
Thank you both for the help :)

**Pull request merged**
