### PR TITLE
Cover/cmds/core/date

### PR DESCRIPTION
**Pull request by ChriMarMe**

### CODE REVIEW

**Review by rminnich — APPROVED** [review]
This still improves things, so I'm inclined to say it should go in? It is up to you.

**Comment by rminnich** [comment]
damn codecov, can we make it happier? It's never happy.

**Comment by ChriMarMe** [comment]
Codecove is such a drama queen.....

**Comment by ChriMarMe** [comment]
Im trying, Im trying. Why is codecove so cruel T_T

**Comment by ChriMarMe** [comment]
( ˘ ͜ʖ ˘)

**Review by rminnich — APPROVED** [review]

**Pull request merged**
