### PR TITLE
cmds/ip: each function returns error to main

### PR DESCRIPTION
**Pull request by isi-lincoln**
This commit addresses the concerns mentioned in PR 707:
https://github.com/u-root/u-root/pull/707

main should be the only function to log.Fatal, in this commit,
each function will return an error and propogate the error to main,
who log.Fatal

### CODE REVIEW

**Comment by rminnich** [comment]
so, no. I don't agree with chris. It's a good rule, but rules can be broken.

The way this parser works is similar to https://github.com/golang/go/wiki/PanicAndRecover, and in fact I got this model of parsing from a talk by Rob Pike IIRC ca. 2010. The use is similar to what we used to do in Plan 9 with erorr()/waserror() and it's a handy way to exit a parser when things go badly wrong.

**Comment by rminnich** [comment]
another example of panic/recover style parsing in go
https://golang.org/src/encoding/json/decode.go

**Comment by hugelgupf** [comment]
As you know, Ron, I disagree... panic and recover is a poor model of error handling. It's the Go version of exceptions, except Go explicitly chose not to have exceptions, for good reasons!

I think this is besides the fact that eventually, we probably want ip to become more modular, so that in other parts of the code base we don't have to rewrite logic for messing with routes and addresses on NICs. For this, the ip code base must have standard error handling.

Just my 2c.

**Comment by hugelgupf** [comment]
This, btw, also makes the individual ip functions more traditionally testable (we can eg add to a table test).

**Comment by isi-lincoln** [comment]
If the consensus is to move cmds/ip to a panic/recover model, I am willing to revert these changes and implement that model for error recovery.  This conversation however is above my head, as it relates to the direction of how `u-root` modules should be implemented and what level of consistency there should be across all modules in how they report errors.

**Comment by rminnich** [comment]
I'll remove my -1 and let you two do what seems best. I don't agree but it's not a huge deal to me.

**Comment by rminnich** [comment]
OK, OK, you were right. I ended up doing what you did a different way, but point taken. Sorry. I'm going to close this because so much has changed, but if I messed something up please submit another PR with corrections.

**Pull request closed without merging**
