### PR TITLE
add one more glob to pkg/uroot/util/root.go for NiChrome

### PR DESCRIPTION
**Pull request by rminnich**
This is one more pattern typical of Go packages
and ensures that the symlink for /ubin/wingo gets
created.

We *could* replace all this with a walk, save that
it seems to create more false positives.

Possibly, what it should do is a walk, then an ast, and see
if package main is defined in that directory, then add a symlink?

That's for another day, and another PR, I think.

Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>

### CODE REVIEW

**Comment by hugelgupf** [comment]
I'm not sure I understand this:

> We could replace all this with a walk, save that it seems to create more false positives.

What false positives?

I think what we could do is Walk all source file directories, use the go/build package (Context.ImportDir) to get the build.Package, and then call build.Package.IsCommand(). This is *essentially* the same thing you propose with the ast, just a bit easier.

**Comment by rminnich** [comment]
however, even if your idea is better long term, I kind of need this now, ...

**Comment by hugelgupf** [comment]
Let's just get it in for now

**Comment by rminnich** [comment]
Thanks. I'm not disagreeing with your idea, btw, we need to do what you said.

**Pull request merged**
