### PR TITLE
ls: correctly list '..' with -a

### PR DESCRIPTION
**Pull request by rminnich**
For 12 years, ls has never listed .. with -a, and someone just noticed it while testing 9p on linux!

Add '..' to the files that are stat'ed; add a test.

### CODE REVIEW

**Comment by rminnich** [comment]
if we're lucky this won't break any scripts.

**Comment by rminnich** [comment]
the reason this never worked is we used filepath.Walk, and that, not surprisingly, does  not walk to ..

**Review by binjip978 — COMMENTED** [review]
I think there is a problem:

If I create a folder say "fff", cd to "fff",  move binary in it and run I see this:
```
./ls -a .. 
.
fff
ls.go
ls_linux_test.go
ls_plan9.go
ls_test.go
ls_unix.go
.
```

Two dots, but one of them should be ".."

If a run regular ls I see that:
```
.                ..               fff              ls.go            ls_linux_test.go ls_plan9.go      ls_test.go       ls_unix.go
```

**Comment by rminnich** [comment]
thanks for the test. So we're going to need to add more tests, to catch this, and then write this properly. 

.. is hard to get right.

I think the big issue here was using filepath.Walk at the starting point. Seems fine for -R, but not as step one.

**Comment by rminnich** [comment]
this was nowhere near right. Have to try again.

**Pull request closed without merging**
