### PR TITLE
Add go module support

### PR DESCRIPTION
**Pull request by kenshaw**
Add go module support, removing unnecessary vendor directory, and
updating to latest dependencies.

Signed-off-by: Kenneth Shaw <kenshaw@gmail.com>

### CODE REVIEW

**Comment by hugelgupf** [comment]
Hey, thanks for doing this.

Unfortunately, I don't think this will be easy.

u-root has a custom build system with some AST and Type Checking logic, and it has yet to be integrated with go modules.

See pretty much everything in pkg/uroot/builder.

**Comment by kenshaw** [comment]
Yes, there is likely some more conversion that still needs to happen. I'll go through more today, and see if I can't fix circleci and any other issues.

**Comment by kenshaw** [comment]
@hugelgupf this is actually fairly straightforward. I just need to do some testing, but I believe I have this completed already (ie, using the Go module cache for building). I need to catch a flight soon, but expect something in the next day or so. I just want to ensure it's using the same build lists/files as previously (it should).

**Comment by kenshaw** [comment]
In the interest of atomic commits / review purposes, I'm going split this up into multiple PRs, and separate the changes for the CI from the module dependencies. There are some design problems with the CI scripts that can be addressed separately, and I imagine the totality of changes here will end up causing much discussion that I'd like to avoid confusing the issue.

**Comment by hugelgupf** [comment]
You'll have to write a types.Importer that works with modules -- the build system has to be able to resolve modules' types for the source to source transformation. 

Also, source mode will need a way to download the source for all those modules and make it buildable in the initramfs. That part might be doable by just forcing a "go mod vendor"?

**Comment by kenshaw** [comment]
Apologies on the delay for finishing this. I'm currently traveling for work, and have not had adequate time to finish all of the necessary changes. Additionally, I will be splitting this PR up into multiple issues/PRs in order to separate the major functionality changes. The first PR will be one to fix the CI and linter issues, and possibly will split other base code changes necessary for the module adoption up as needed. At the moment, that is likely to be 2 PRs, but could be more.

**Comment by hugelgupf** [comment]
Sounds good. Thank you!

**Pull request closed without merging**
