### PR TITLE
trampoline: revise to work with Go 1.17 register ABI

### PR DESCRIPTION
**Pull request by thanm**
Revises the recipe for obtaining the address (starting PC) of assembly
routines from Go, so as to have something that works with the new
(1.17+) register ABI.

Fixes #2701.

Signed-off-by: Than McIntosh <thanm@google.com>

### CODE REVIEW

**Comment by thanm** [comment]
Build and test appears to be failing with link errors of this form:

```
# github.com/u-root/u-root/cmds/core/kexec
/usr/local/go/pkg/tool/linux_amd64/link: pcln table file missing from DWARF line table
```

This seems mildly surprising -- this message dates back a while (it was added in Go 1.10, and exists up until Go 1.13, then removed prior to the release of 1.14 when the linker line table generation was revamped).

Is there an easy way for me to see the version of the Go toolchain being used for this CI setup? Thanks.

**Comment by thanm** [comment]
OK, I am pretty much stumped at this point. I found the .circleci setup at the top level of the repo, then did

```
sudo docker pull circleci/golang:1.15
sudo docker run -it --entrypoint sh circleci/golang:1.15
```

From looking at the Go install in the container, it is definitely 1.15 -- I looked at the linker sources there and I don't see the string. I also verified that the error string in question is not part of the linker binary:

$ strings /usr/local/go/pkg/tool/linux_amd64/link | fgrep 'pcln table file missing'
$

If any of the reviewers/maintainers have suggestions, I would love some help on this one.

**Comment by rminnich** [comment]
I'll try to look next week, today is oreboot day .... that's a mess.

**Comment by thanm** [comment]
Thanks Ron, much appreciated.

I poked at it a bit more this morning. I think the problem is here:

https://github.com/u-root/u-root/blob/ab819d854d080062caf6f195ec8dc231f03e4177/.circleci/config.yml#L6

which reads 

      - image: uroottest/test-image-amd64:v3.2.13

I pulled this container and looked at the Go version:

```
$ sudo docker pull uroottest/test-image-amd64:v3.2.15
$ sudo docker run -it --entrypoint sh  uroottest/test-image-amd64:v3.2.15
$ go version
go version go1.13.15 linux/amd64
```

Go 1.13 is outside the support window (not clear how/why this odd linker error is being triggered, but whatever it is, that version of Go is not going to be fixed).

**Comment by hugelgupf** [comment]
I think we can safely upgrade our Go version to something newer now

**Comment by rjoleary** [comment]
This updates the Go version: https://github.com/u-root/u-root/pull/2041. However it is causing one of the VM tests to fail, so can't be pushed until that's fixed.

**Comment by rjoleary** [comment]
> This updates the Go version: #2041. However it is causing one of the VM tests to fail, so can't be pushed until that's fixed.

It still seems to be failing with go1.15

**Comment by thanm** [comment]
Hi u-root folks -- it looks as though the CI for this PR is failing due to "codecov/patch".  As I understand it, the coverage tooling is asking me to make sure that the unit test covers at least 55% of the lines touched in the patch. While this rule seems like a good idea, this package doesn't have a unit test at all, at the moment.

Could someone please advise me on the best way forward with this PR? Should I attempt to write a unit test for it? Or can the PR be merged in spite of the coverage failure (given that the package currently has no unit test)? Thanks.

**Comment by thanm** [comment]
Friendly ping to maintainers -- it would be nice to get this patch merged at some point, thanks.

**Review by rjoleary — APPROVED** [review]

**Pull request merged**
