### PR TITLE
Move some code from cmds/switch_root to pkg/mount; export useful funcs.

### PR DESCRIPTION
**Pull request by mpictor**
Signed-off-by: Mark Pictor <mpictor@gmail.com>

### CODE REVIEW

**Comment by mpictor** [comment]
Looks like the CircleCI failure was a 10 minute time-out. Do we run the test again, or ...?

**Comment by rjoleary** [comment]
That shouldn't happen. I reran it.

I'll open an issue if it happens again.

**Comment by mpictor** [comment]
not sure how my changes would've caused this...
```
    --- FAIL: TestMultiboot//kernel.gz (7.79s)
        integration.go:113: Filename is /tmp/uroot-integration856086765/initramfs.cpio
        integration.go:113: No default shell: command or path "elvish" not included in u-root build
        integration.go:170: QEMU command line for testMultiboot:
            /home/circleci/qemu-system-x86_64 -L /home/circleci/pc-bios -m 1G -nographic -kernel /tmp/uroot-integration856086765/bzImage -append 'console=ttyS0 earlyprintk=ttyS0' -initrd /tmp/uroot-integration856086765/initramfs.cpio -drive file=fat:rw:/tmp/uroot-integration856086765,if=none,id=tmpdir -device ich9-ahci,id=ahci -device ide-drive,drive=tmpdir,bus=ahci.0 -device virtio-rng-pci
        multiboot_test.go:61: Cannot unmarshal multiboot information from executed kernel: unexpected end of JSON input
        integration.go:176: keeping temp dir:  /tmp/uroot-integration856086765
```

**Comment by rjoleary** [comment]
Sorry about the flaky tests. I filled an issue: #1209

Usually, this doesn't happen. I'll re-run again...

**Pull request merged**
