### PR TITLE
Netcat udp

### PR DESCRIPTION
**Pull request by rminnich**

### CODE REVIEW

**Comment by binjip978** [comment]
I made small change to compile it and after that It works only in one way for me:

So I can send messages from client to server, no problem
```
netcat git:(simple-udp) ✗ ./netcat -net="udp" 127.0.0.1:8080
sdfsdf
sdfsdfsdf
sdfsdf
```

But when I send message from server to client I got an error.

```
netcat git:(simple-udp) ✗ ./netcat -net="udp" -l 127.0.0.1:8080
sdfsdf
sdfsdfsdf
sdfsdf
sdfsdfsdf sdfsdf
write udp 127.0.0.1:8080: write: destination address required
```

So, I will try to update tests with this scenario. My first approach was similar `net.ListenUDP`, but with two function but it failed when I tested it with mac_OS nc.

**Comment by rminnich** [comment]
I'd still like to figure this out, so we don't need two nearly identical run functions. If you're agreeable I'd like to take a littel more time. This PR is an example, not to be submitted.

**Comment by binjip978** [comment]
> I'd still like to figure this out, so we don't need two nearly identical run functions. If you're agreeable I'd like to take a littel more time. This PR is an example, not to be submitted.

Sure, I hope updated test will help.

**Comment by rminnich** [comment]
but that said you could implement your own type that embeds the UDPConn interface, and has a copy of the IP, implements Write, and does what you need. I think it is better to just assume we can created connected UDP sockets.

**Comment by rminnich** [comment]
works on windows
https://learn.microsoft.com/en-us/dotnet/api/system.net.sockets.udpclient.connect?view=net-7.0

**Comment by rminnich** [comment]
it was just a demo.

**Pull request closed without merging**
