### PR TITLE
Add status flag to dd

### PR DESCRIPTION
**Pull request by rjoleary**
I found this is necessary to estimate how long a dd will take.

The `progress` flag may be one of the following:

- `none`: nothing extra is printed to stderr
- `xfer`: print transfer stats after completion (default)
- `progress`: progressively print transfer stats during copy (GNU)

I performed a bit of benchmarking and the addition of the feature has no
noticeable penalty on performance.

Signed-off-by: Ryan O'Leary <ryanoleary@google.com>

### CODE REVIEW

**Comment by mirtchovski** [comment]
I can't offer much more besides what Rob Pike already said in "Programming in the UNIX environment". I note that his stance has not changed as it refers to Go code. Do the simple thing, avoid excessive decoration. 

> The output produced by UNIX programs is in a format understood by other UNIX programs.

We have a great cacophony of programs which don't universally understand each other: you can't grep a twitter feed for a message and you can't concatenate your friends' facebook streams together. On the terminal there should be simplicity, not excessive typography.

Another piece of advice from old unix hands can be found here: https://lasr.cs.ucla.edu/ficus-members/geoff/interfaces.html#parsable ('make programs easy to parse', 'make the default case be the simplest', 'don't make it interactive by default').

Gnu have unfortunately failed at this a few too many times. BSD though provides an elegant hack, pipe viewer: http://www.ivarch.com/programs/pv.shtml

**Comment by rjoleary** [comment]
GNU dd has two methods of reading progress:
- `kill -USR1`: send a signal to the `dd` process. `dd` prints its progress and resumes.
- `status=progress`: this is a relatively new addition, <2 yrs old
Neither of these print a "progress bar" because %progress is impossible to determine for some files. Instead, they print the number of bytes transferred thus far.

**Comment by rminnich** [comment]
OK, I did a check with an old hand and he tells me that something reasonable is a good idea. I was wrong.

HOWEVER, if we do this, let's pick something reasonable and then make all the tools work the same. My friend suggests is output something like this:
" ... this will take from 30 minutes to an hour.  Expect your system to <and explain what to see>.
To know that things have not frozen, any kind of blinking or counting will do. "

So, IOW, something simple, that probably can't be too wrong, on stderr. 

Thanks all, sorry for my confusion.

**Comment by rminnich** [comment]
OK, here's the conclusion. Andrey won't like this, but we ran out of options. We've got an idea that everyone will slightly dislike.

we've been strongly encouraged by a former Unix person to allow these progress bars. Ron is ok as long as the output remains sane, i.e. progress bars are not intermixed with other things, which further implies the output should be readable by programs. So, .... here we go.

stderr output in u-root probably should be parseable as JSON. It needs to be done in a way that humans are comfortable looking at it. So we'll figure this out. 

let the games begin.

**Comment by rminnich** [comment]
so ryan we'll try to change this per our thoughts on json on stderr and level out the unhappiness for all :)

**Comment by rjoleary** [comment]
Just did a rebase and a slight refactor. Nothing should have changed functionally.

What should be the structure of the json? Would this do:

```
{"ElapsedSeconds": 10.4, "BytesWritten": 230293}
```

Another problem is frequency. Right now the progress indicator rewrites over the same line by using control characters. If it writes once per second and there are 1000 seconds, there will be only one line displayed on the terminal which is a convenience.

However, to make it easily parseable, you need to remove the control characters. Then a 1000 second dd might write 1000 lines of progress to the terminal and you might drown.

It might be possible to get the best of both worlds by switching between the two methods based on the presence of a tty vs pipe. GNU's "ls" does this to decide whether to print columns or lines.

But, you might find yourself in the wrong world and end up with text files filled with unwanted control characters or terminal windows filled with lines of json. Anecdotally, I've never had a problem with "ls" properly detecting the tty. Thoughts?

**Comment by rminnich** [comment]
on Plan 9 and harvey, there is no such thing as a tty. There's not even an ioctl.

The GNU tests work because "everything's a Unix" but it would be nice not to have to wire that behaviour in.

Can you escape using the escape (ha ha) and just send \r? Or is the issue the fact that you want to clear the line? If all the lines you send were the same length (not hard to do) would that remove the need for the escape sequence? Or you can remember the length of the last line printed and, if the next one is shorter, add spaces after the } to fill it out?

maybe for now keep it simple, write a \r between json expressions, make the JSON expressions always exactly the same length to avoid the need to clear the line, and we let needs dictate where we go next? The JSON you show seems eminently reasonable. if you like it I like it. Thanks for your patience on this PR. Presotto told me I was insane and that changed my mind :-)

Also we have had problems on some production systems where terminal emulation was decidedly not ANSI, so it would be nice to avoid embedded ANSI whenever possible.

**Comment by rminnich** [comment]
Let's just get this in and see how we like it. I think it would make sense to create a progress package and have this same capability available to any program wanting a progress bar but Ryan was right about this from the beginning and we can tinker with a few bits I'm not totally comfortable with (embedded ANSI escape sequence) when we need to.

**Pull request merged**
