### PR TITLE
pkg/cpio: regarding hard link when link count greater than one

### PR DESCRIPTION
**Pull request by tw4452852**
I found this issue in my environment where a hard link with link count == 1

### CODE REVIEW

**Comment by tw4452852** [comment]
Ah, I figured out the root cause, the directory hierarchy as follows:

```
/usr/lib/a.so
/lib -> /usr/lib
```

If I add `/usr/lib/a.so` and `/lib/a.so` to cpio, then one of then will be recognized as hard link to the other which is not right.

So I will prepare another PR to fix this and close this one to avoid confusion.

**Comment by rminnich** [comment]
This is a pretty consequential change. Also, that hierarchy looks like a symlink, not a hard link.

We've been using this package for many years, and I really need to see more of a test case before I can be certain this is right. Ideally, if you can add a test for this to the test code, and show it fails, and that your change fixes it, I would be a lot more comfortable. 

This cpio package is pretty widely used, so we have to be careful.

**Comment by rminnich** [comment]
I need to see a repro, because I can not recreate what you are seeing. 
If you want to show the commands here then that would help.

**Comment by tw4452852** [comment]
Here a simple reproduce demo:

```
~/code/u-root> tree -h ./t
[4.0K]  ./t
├── [   3]  bar -> foo
└── [4.0K]  foo
    └── [   4]  test.txt
~/code/u-root> ./u-root -files ./t/foo/test.txt -files ./t/bar/test.txt  -o test.cpio
10:14:35 Disabling CGO for u-root...
10:14:35 Build environment: GOARCH=amd64 GOOS=linux GOPATH=/home/tw/go CGO_ENABLED=0 GO111MODULE= GOROOT=/usr/lib/go PATH=/usr/lib/go/bin:$PATH
10:14:35 NOTE: building with the new gobusybox; to get the old behavior check out commit 8b790de
10:14:35 Skipping package github.com/u-root/u-root/cmds/core/bind because build constraints exclude all Go files
10:14:49 Successfully built "test.cpio" (size 14983536).
~/code/u-root> lsinitrd test.cpio | grep t/
drwxr-xr-x   0 root     root            0 Jan  1  1970 t/bar
-rw-r--r--   0 root     root            4 Jan  1  1970 t/bar/test.txt
drwxr-xr-x   0 root     root            0 Jan  1  1970 t/foo
-rw-r--r--   0 root     root            0 Jan  1  1970 t/foo/test.txt

```

You can see size of `t/foo/test.txt` is 0, this is because current logic think it's a hard link to `t/bar/test.txt` which is wrong.

**Comment by tw4452852** [comment]
BTW, I append a test for this case.

**Comment by rminnich** [comment]
I still think that's not really the problem. 
I did this:
```
t
├── bar -> ./foo
└── foo
    └── text
```
Then this:
```
find t | ./cpio o | ./cpio t
drwxr-x---	rminnich	89939	0 B	May 11 16:31	t
Lrwxrwxrwx	rminnich	89939	5 B	May 11 16:31	t/bar -> ./foo
drwxr-x---	rminnich	89939	0 B	May 11 16:30	t/foo
-rw-r-----	rminnich	89939	0 B	May 11 16:30	t/foo/text
ls -l t/bar/text 
-rw-r----- 1 rminnich primarygroup 0 May 11 16:30 t/bar/text
```
and
```
find t | ./cpio o | (cd tt && ../cpio i)
rminnich@glenda:~/go/src/github.com/u-root/u-root/cmds/core/cpio$ tree tt
tt
└── t
    ├── bar -> ./foo
    └── foo
        └── text
```

it's being extracted correctly. 

The problem is with your invocation of u-root, I think:

```
./u-root -files ./t/foo/test.txt -files ./t/bar/test.txt  -o test.cpio
```

Since you are naming two files, I don't see a good way for u-root correctly handle the symlink in the middle.

for example:
```
~/go/bin/u-root -files t -nocmd -base=/dev/null -o /dev/stdout | cpio -itv
drwxr-x---   0 root     root            0 Jan  1  1970 t
lrwxrwxrwx   0 root     root            5 Jan  1  1970 t/bar -> ./foo
drwxr-x---   0 root     root            0 Jan  1  1970 t/foo
-rw-r-----   0 root     root            0 Jan  1  1970 t/foo/text
2 blocks
```

That's the right tree.

Further, in your example above, they actually are the same file. 
```
/usr/lib/a.so
/lib -> /usr/lib
```
/lib/a.so and /usr/lib/a.so have the same inumber, and hence both a.so are hard links to the same file.

e.g.
```
ls -li t/*/text
125047860 -rw-r----- 1 rminnich primarygroup 0 May 11 16:30 t/bar/text
125047860 -rw-r----- 1 rminnich primarygroup 0 May 11 16:30 t/foo/text

tree t
tree t
t
├── bar -> ./foo
└── foo
    └── text

```

I tried to see how regular cpio would handle this:
```
(echo t/bar/text && echo t/foo/text)  | cpio -o | cpio -itv
1 block
-rw-r-----   1 24977    24403           0 May 11 16:30 t/bar/text
-rw-r-----   1 24977    24403           0 May 11 16:30 t/foo/text
1 block
```

I don't know if there's a good way around what happens when there are symlinks in the middle of paths passed to cpio. But I also believe this fix is wrong. The level of complexity needed to handle such intermediate symlinks is probably more than we want to take on.

The solution is pretty easy.
u-root -files /lib -files /usr/lib/a.so ...
since /lib is a symlink.

I'm going to close this because IMHO this is not a real issue.

**Pull request closed without merging**
