### PR TITLE
RFC proposal

### PR DESCRIPTION
**Pull request by rminnich**
We need an RFC mechanism so here is one idea.

I'm pretty adamant on Latex. We tried markdown for the book
and it did not end well in my view. With Latex we can get
good looking output with good support for automated
figure numbers, citations, image inclusion, and so on.
Latex is a standard for publication nowadays.

### CODE REVIEW

**Comment by hugelgupf** [comment]
Wait... Our RFC process is the Issues on github, no? I'd prefer we make better use of that?

See #1134, or #496?

**Comment by hugelgupf** [comment]
> We tried markdown for the book and it did not end well in my view

We haven't really tried that hard...

**Comment by rminnich** [comment]
Issues are almost be definition temporary, not part of the repo and hence not as long lived as the repo. Should we move away from github, ever, those issues are gone.

Issues are not permanent. You can't point back to them to understand why things are they way they are. That's the value of RFCs. I can go back 50 years and see why things happened the way they did.

We've gone through several different SCMs on coreboot and, had we used the equivalent of issues, they'd be gone. As will this conversation, whether we accept this PR or not, should we ever leave github. That's why we maintain the Documentation directory on coreboot. But it lacks structure so has not been as useful as we hoped.

**Comment by hugelgupf** [comment]
> Issues are not permanent. You can't point back to them to understand why things are they way they are. That's the value of RFCs. I can go back 50 years and see why things happened the way they did.

But they are! If they are not this way, we are not using issues correctly. The Go team is able to use issues this way, we don't need to introduce a new process like this.

We can have an issue template if you like?

**Comment by rafaelcn** [comment]
@hugelgupf does an issue template really does a difference in the matter we are discussing? The problem I see that is still open is that we can't track the development of the project with only the issues, but that might be my inexperienced eye. 

Creating milestones and specific projects within this repository and also use release with _git tags_ might improve what has been implemented and what will be implemented amongst different versions of u-root.

**Comment by hugelgupf** [comment]
Counterpoint: if GitHub goes away at some point, you can scrape it all and dump it in git...

**Comment by hugelgupf** [comment]
> Counterpoint: if GitHub goes away at some point, you can scrape it all and dump it in git...

To me, this PR is a solution without a problem. It only makes it harder for people to comment on things. And it's not like GitHub PR comment history is going to be preserved...

**Pull request closed without merging**
