### PR TITLE
pkg/boot/grub: add support for grub devicetree command

### PR DESCRIPTION
**Pull request by tobhe**
I've been using u-root to boot linux on an arm64 chromebook and noticed that the grub "devicetree" command didn't work. This is widely used in Debian/Ubuntu for arm64 in combination with flash-kernel to keep kernel and DTBs in sync.

### CODE REVIEW

**Comment by tobhe** [comment]
Fixed a go-fmt problem and got a new test failure which seems to be a flipper.

**Review by rminnich — APPROVED** [review]
Looks fine to me, not that I really understand grub any more :-)

**Comment by rminnich** [comment]
take a look at the failing tests.

**Comment by tobhe** [comment]
no failures when I run it locally:
```
PASS
ok  	github.com/u-root/u-root/cmds/core/strace	0.019s
```
Can you hit the retry button?

**Pull request merged**
