### PR TITLE
[localboot] Add fsuuid option to boot from block device

### PR DESCRIPTION
**Pull request by yurinnick**
Devices like Pinephone has partitions mapped as a separate block devices. Add fsuuid option to support this usecase.

### CODE REVIEW

**Comment by yurinnick** [comment]
For reference, this is how block device table looks like on Pinephone:
```
localboot -d
1970/01/01 00:08:30 Device: BlockDevice(name=loop0, fs_uuid=)
1970/01/01 00:08:30 Device: BlockDevice(name=loop1, fs_uuid=)
1970/01/01 00:08:30 Device: BlockDevice(name=loop2, fs_uuid=)
1970/01/01 00:08:30 Device: BlockDevice(name=loop3, fs_uuid=)
1970/01/01 00:08:30 Device: BlockDevice(name=loop4, fs_uuid=)
1970/01/01 00:08:30 Device: BlockDevice(name=loop5, fs_uuid=)
1970/01/01 00:08:30 Device: BlockDevice(name=loop6, fs_uuid=)
1970/01/01 00:08:30 Device: BlockDevice(name=loop7, fs_uuid=)
1970/01/01 00:08:30 Device: BlockDevice(name=mmcblk0, fs_uuid=)
1970/01/01 00:08:30 Device: BlockDevice(name=mmcblk0p1, fs_uuid=87a9-294d)
1970/01/01 00:08:30 Device: BlockDevice(name=mmcblk2, fs_uuid=)
1970/01/01 00:08:30 Device: BlockDevice(name=mmcblk2boot0, fs_uuid=)
1970/01/01 00:08:30 Device: BlockDevice(name=mmcblk2boot1, fs_uuid=)
1970/01/01 00:08:30 Device: BlockDevice(name=mmcblk2p1, fs_uuid=e118fc8f-6db9-417f-acc5-2afb8dbb9834)
1970/01/01 00:08:30 Device: BlockDevice(name=mmcblk2p2, fs_uuid=0308da97-4e99-48f7-b5d4-18fb4c858cf9)
```

**Comment by hugelgupf** [comment]
Happy to take patches, but have you considered the `boot` command? We're trying to, in the long-term, steer users and features towards that one.

**Comment by yurinnick** [comment]
After you mentioned it, I think `boot` command fits even better for my purpose. What I what to do it to boot an arm64 linux based on `extlinux` config. `boot` command already does most of what I need, would you mind if I'll extend it to support `extlinux` configuration?

Also, I am planning to add device tree binary support, however it looks like it's outside of normal `syslinux` spec. Should I create an extended parser or it's okay to use `syslinux` one?

**Comment by hugelgupf** [comment]
Go for it

**Comment by hugelgupf** [comment]
And my default answer is to add features to the standard things we have rather than add duplicates / copies, so standard syslinux

**Comment by yurinnick** [comment]
Implemented `extlinux` support in #2385

**Pull request closed without merging**
