### PR TITLE
Fix argument name for shasum command

### PR DESCRIPTION
**Pull request by a-urth**
Seems like there was a typo

### CODE REVIEW

**Review by rminnich — APPROVED** [review]

**Comment by rminnich** [comment]
please git commit --amend -s and we are good to go!

**Comment by a-urth** [comment]
Signed off. Didn't want to push with force, so it produced unnecessary commit. If its not ok, I'll change.

**Review by MDr164 — APPROVED** [review]

**Comment by MDr164** [comment]
> Signed off. Didn't want to push with force, so it produced unnecessary commit. If its not ok, I'll change.

You'll have to force push to change the commit message, otherwise the checks won't pass

**Comment by hugelgupf** [comment]
Thanks for the contribution. I force-pushed to your branch to clean up the conflicting commits, going to merge.

**Pull request merged**
