### PR TITLE
cmds/core/init: exiting twice in elvish will cause kernel panic

### PR DESCRIPTION
**Pull request by 0xzcs**
add a infinite loop run defaultsh to avoid it

### CODE REVIEW

**Review by rminnich — COMMENTED** [review]
This has come up before. I still am not sure this is the right answer.

**Comment by 0xzcs** [comment]
This modification is indeed not universal, I wonder if there is a better method to solve this problem?
Holding down Ctrl+C in uinit may also kill the shell and cause kernel panic.

**Comment by 0xzcs** [comment]
> This has come up before. I still am not sure this is the right answer.

This modification is indeed not universal, I wonder if there is a better method to solve this problem?
Holding down Ctrl+C in uinit may also kill the shell and cause kernel panic.

**Review by rminnich — COMMENTED** [review]
I'm basically inclined to like this, there's also a problem: what if there's no /bin/defaultsh? The system will sit there, silently trying to run a command that does not exist. So you will suddenly hear all the fans go to infinite RPMs as the processors get very hot. I think this needs to be thought out a bit more.

**Comment by rminnich** [comment]
one option you might try: you can create a uinit, that implements this loop, and init will run your uinit. That way, it's an option if people want it.

**Pull request closed without merging**
