### PR TITLE
[WIP]Add CentOS Stream release 8 GRUB_ENABLE_BLSCFG set to true and false test data

### PR DESCRIPTION
**Pull request by johnnylinwiwynn**
The /boot folder data is also shared to Google drive at https://drive.google.com/drive/u/1/folders/1iRs6FdzSnqUlXM3GXYeoY_XGEBidLc74
boot-bls.tar.gz is the tar for GRUB_ENABLE_BLSCFG=true,
boot-nobls.tar.gz is the tar file for GRUB_ENABLE_BLSCFG=false.

### CODE REVIEW

**Comment by johnnylinwiwynn** [comment]
This is my attempt to add test data for the same issue mentioned in https://github.com/u-root/u-root/pull/2223
@jonzhang-fb @JingleHsuWiwynn

**Review by rminnich — CHANGES_REQUESTED** [review]
let's make sure we never commit this file, it has 15M of kernel :-)

**Comment by rminnich** [comment]
a diff of the two .cfg files is interesting. 

There's only one real difference. 

BLS is on the right.

Looks like we don't support the menuentry keyword.

### BEGIN /etc/grub.d/10_linux ###								### BEGIN /etc/grub.d/10_linux ###
											      >	menuentry 'CentOS Stream (5.14.1) 8' --class centos --class gnu-linux --class gnu --class os
											      >		load_video
											      >		set gfxpayload=keep
											      >		insmod gzio
insmod part_gpt												insmod part_gpt
insmod ext2												insmod ext2
if [ x$feature_platform_search_hint = xy ]; then							if [ x$feature_platform_search_hint = xy ]; then
  search --no-floppy --fs-uuid --set=root  53cfb120-9300-4afd-9ba7-a60a7277c252				  search --no-floppy --fs-uuid --set=root  53cfb120-9300-4afd-9ba7-a60a7277c252
else													else
  search --no-floppy --fs-uuid --set=root 53cfb120-9300-4afd-9ba7-a60a7277c252				  search --no-floppy --fs-uuid --set=root 53cfb120-9300-4afd-9ba7-a60a7277c252
fi													fi
											      >		linux	/boot/vmlinuz-5.14.1 root=UUID=53cfb120-9300-4afd-9ba7-a60a7277c252 ro crashk
											      >		initrd	/boot/initramfs-5.14.1.img
											      >	}
											      >	menuentry 'CentOS Stream (0-rescue-3370cc3add884b58835edcc89eeb00a0) 8' --class centos --clas
											      >		load_video
											      >		insmod gzio
insmod part_gpt												insmod part_gpt
insmod fat										      |		insmod ext2
if [ x$feature_platform_search_hint = xy ]; then							if [ x$feature_platform_search_hint = xy ]; then
  search --no-floppy --fs-uuid --set=boot  B555-118C					      |		  search --no-floppy --fs-uuid --set=root  53cfb120-9300-4afd-9ba7-a60a7277c252
else													else
  search --no-floppy --fs-uuid --set=boot B555-118C					      |		  search --no-floppy --fs-uuid --set=root 53cfb120-9300-4afd-9ba7-a60a7277c252
fi											      <
											      
if [ -z "${kernelopts}" ]; then								      <
  set kernelopts="root=UUID=53cfb120-9300-4afd-9ba7-a60a7277c252 ro crashkernel=auto net.ifna <
fi													fi
											      >		linux	/boot/vmlinuz-0-rescue-3370cc3add884b58835edcc89eeb00a0 root=UUID=53cfb120-93
											      >		initrd	/boot/initramfs-0-rescue-3370cc3add884b58835edcc89eeb00a0.img
											      >	}

insmod blscfg										      <
blscfg											      <
### END /etc/grub.d/10_linux ###								### END /etc/grub.d/10_linux ###

**Comment by johnnylinwiwynn** [comment]
The successful one has 'menuentrey' but the failed one does not and cannot display item 01 and 02 below. Seems like some kind of hiding menu somewhere else BLS syntax is not supported?

01. CentOS Stream (0-rescue-3370cc3add884b58835edcc89eeb00a0) 8

02. CentOS Stream (5.14.1) 8

03. Reboot

04. Enter a LinuxBoot shell

**Comment by johnnylinwiwynn** [comment]
Can be fixed by PR https://github.com/u-root/u-root/pull/2237

**Pull request closed without merging**
