### PR TITLE
kmodule: Support zstd compressed modules

### PR DESCRIPTION
**Pull request by Foxboron**
Signed-off-by: Morten Linderud <morten.linderud@mullvad.net>

### CODE REVIEW

**Review by rminnich — COMMENTED** [review]
this looks good, I'm wondering though: is the xz fully native? It does not call out to some external xz I guess?

**Comment by Foxboron** [comment]
I haven't checked. Do you want me to investigate this a bit?

**Comment by hugelgupf** [comment]
klauspost' stuff is usually native, if that's what you're asking

**Comment by abrender** [comment]
Today we have pkg/gzip which provides generic Compress/Decompress functions so that other code in u-root doesn't have to worry about implementation details and we can swap it out in the future.

May I ask that we consider adding something similar - creating pkg/zst and putting the implementation details in there, in case we want to swap it out in the future, and to provide the functionality for other u-root code? Thanks!

**Comment by abrender** [comment]
> Today we have pkg/gzip which provides generic Compress/Decompress functions so that other code in u-root doesn't have to worry about implementation details and we can swap it out in the future.
> 
> May I ask that we consider adding something similar - creating pkg/zst and putting the implementation details in there, in case we want to swap it out in the future, and to provide the functionality for other u-root code? Thanks!

PS - the reason I'm asking for this is because Linux bzimage files can be compressed with zstd, so we'd like to support uncompressing them as well. If the code were in a generic u-root/pkg/zstd package then it'd be a nice generic way for us to reuse the same underlying implementation.

**Comment by Foxboron** [comment]
I can write `pkg/zstd` for u-root, but is this a blocker for this PR? The current module support doesn't use these packages and I don't see a good reason to block on this.

Would probably be good to have merged before then as well https://github.com/u-root/u-root/pull/2481

**Comment by abrender** [comment]
> I can write `pkg/zstd` for u-root, but is this a blocker for this PR? The current module support doesn't use these packages and I don't see a good reason to block on this.
> 
> Would probably be good to have merged before then as well #2481

No need from me to block on this right now, it'd just be a nice cleanup in the future.

**Review by rminnich — APPROVED** [review]

**Pull request merged**
