### PR TITLE
Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by rminnich**
setting up for azure pipelines

### CODE REVIEW

**Comment by rminnich** [comment]
This, from start to running it, took about 3 minutes to set up.
Azure is very impressive.

**Comment by rminnich** [comment]
for open source projects we get 10 free pipelines. 
I suggest we just run both for now and transition if we want or just use both so we get more resources.

**Comment by hugelgupf** [comment]
Why this over circleci?

**Comment by hugelgupf** [comment]
Or in other words - what problem does this solve that circleci does not?

**Comment by rminnich** [comment]
we get 10 free pipelines on azure and, yes, osx builds ... it would be nice to at least try to keep building on osx.

**Pull request merged**
