### PR TITLE
RFC - Revert "cmds/core/gosh: replace go-prompt with bubbline"

### PR DESCRIPTION
**Pull request by 10000TB**
Reverts u-root/u-root#2606

Let's *consider* switch back to go-prompt, which has more public interests        
which can be assumed better maintained, w.r.t reliability and security.

Did we consider submitting the "new features" into go-prompt ?

### CODE REVIEW

**Comment by 10000TB** [comment]
Duplicate to https://github.com/u-root/u-root/pull/2606#issuecomment-1523876096, looking for author replies

**Comment by MDr164** [comment]
> Duplicate to [#2606 (comment)](https://github.com/u-root/u-root/pull/2606#issuecomment-1523876096), looking for author replies

https://github.com/u-root/u-root/pull/2606#issuecomment-1527107724

**Comment by 10000TB** [comment]
Thanks for coming back to me Marvin. Left my clarification in your original PR

https://github.com/u-root/u-root/pull/2606#issuecomment-1528876935

re: size. can't import latest u-root atm, don't know size impact yet

**Comment by 10000TB** [comment]
In addition, Google has been following an upstream first approach, where we strives to put every golang cmd / pkg we develop for Google, into u-root as much as possible. Making it harder for us to ingest u-root would disincentive people from contributing to u-root where possible, and instead check them into internal only repos.

**Comment by 10000TB** [comment]
ping

**Comment by MDr164** [comment]
I see your point. I'm also in favor of having less dependencies. The issue right now is the following:
Using go-prompt:
- Somewhat broken (leave the term in a weird state, can't handle edgecases, as several open issues)
- Original repo abandoned -> we needed a fork in order to get fixes in -> more maintainance
- Less dependencies

Using bubbline:
- Not broken as go-prompt
- Still maintained upstream
- More dependencies -> higher investment for Googles internal use

Ideal solution: Write tab completer from scratch using only the standard library.

So using either library will upset some users. Bubbline upsets Google, go-prompt upsets everyone else (and probably Google as well as it's still somewhat broken). If someone has the time to implement the completer from scratch then I'm more than happy to review a PR for that but I'm swamped in work so I can't take that on myself.

**Comment by hugelgupf** [comment]
I think bubbline is fine - I don't yet see the amount of work David is
attaching here. I also think such Google-oddities shouldn't spill into the
open source projects constraints without us at least having tried.

I'm asking David to try the import, and giving a hand.

**Comment by jelischer** [comment]
Ironic that the tab completion  is seen as a positive when inside Google we are trying to find a way to disable it.

**Pull request closed without merging**
