### PR TITLE
cmds/core/gosh: support cd

### PR DESCRIPTION
**Pull request by letian0805**
#3153

### CODE REVIEW

**Comment by rminnich** [comment]
cd has worked forever, I can't figure out what problem you're seeing.

Until we have a better reproducer I think we have to wait.

**Comment by rminnich** [comment]
./gosh
> cd /
> cd ~
> pwd
/Users/rminnich
> cd -
/
> pwd
/
>

**Review by rminnich — CHANGES_REQUESTED** [review]
I am not seeing the problem.

**Comment by letian0805** [comment]
> I am not seeing the problem.

You can try it in a docker container based on the scratch image.

**Comment by binjip978** [comment]
gosh already have builtins and `cd` is one of them. I think your scratch example fails because of wrong permissions. I don't see any issues with u-root or mvdan.cc/sh here.

Here is mvdan.cc/sh/v3/interp/builtin.go: 
```go
func (r *Runner) changeDir(ctx context.Context, path string) int {
	if path == "" {
		path = "."
	}
	path = r.absPath(path)
	info, err := r.stat(ctx, path)
	if err != nil || !info.IsDir() {
		return 1
	}
	if !hasPermissionToDir(info) {
		return 1
	}
	r.Dir = path
	r.setVarString("OLDPWD", r.envGet("PWD"))
	r.setVarString("PWD", path)
	return 0
}
```

**Pull request closed without merging**
