### PR TITLE
cpio/utils: use path, not filepath, on archives

### PR DESCRIPTION
**Pull request by rminnich**
cpio/utils: use path, not filepath, for archives

    cpio is a Unix standard, the separator has to be /.
    Absolute paths are prefixed with / in cpio archives,
    not strings like C:/ as in Windows.
    Paths must be cleaned with /, not \.

    Lessons learned the hard way when poring the cpu client
    to Windows.

    Before this change, the cpio test would not pass on windows.
    With this change, it passes on darwin, linux, and windows.

### CODE REVIEW

**Review by hugelgupf — APPROVED** [review]

**Comment by 10000TB** [comment]
Just curious what was the edge case filepath didn't work for on windows ? --

UNC path seems the only thing the doc calls out, between path.Join and filepath.Join 

https://pkg.go.dev/path/filepath#Join

**Comment by hugelgupf** [comment]
On windows, filepath.Join will produce paths with \. But this is creating a
cpio archive, in which all paths should be /

**Review by binjip978 — DISMISSED** [review]

**Comment by rminnich** [comment]
I'm going to do further testing on windows tonight, to make sure go test runs correctly on unix and windows.

**Comment by rminnich** [comment]
on testing this morning, the Normalize tests failed on Windows; now they work.

Just look at https://cs.opensource.google/go/go/+/refs/tags/go1.21.3:src/path/filepath/path_windows.go;l=102 to see how different things are.

**Review by binjip978 — APPROVED** [review]

**Pull request merged**
