### PR TITLE
Replace path.join with filepath.join

### PR DESCRIPTION
**Pull request by bkochendorfer**
## Description
This pull request resolves https://github.com/u-root/u-root/issues/206

## Testing
I ran the `travis.sh` tests inside of a _travis like_ container using the following command.  I expect this pr will run the same but wanted a way to test locally as well.
```
% docker run -e "PATH=/home/travis/gopath/bin:$PATH" --privileged -u travis -it -v /Users/bkochendorfer/go/src/github.com/u-root/u-root:/home/travis/gopath/src/github.com/u-root/u-root quay.io/travisci/travis-go:latest bash
% # setup golang 1.9 using gimme
% bash travis.sh
... output ...
Mon Sep 18 18:49:42 UTC 2017
Did it blend
root@d2a1a53b5130:/home/travis/gopath/src/github.com/u-root/u-root# echo $?
0
root@d2a1a53b5130:/home/travis/gopath/src/github.com/u-root/u-root# exit
```

### CODE REVIEW

**Comment by bkochendorfer** [comment]
@rminnich Rebased and pushed

**Comment by hugelgupf** [comment]
We don't use memmap anywhere anymore. When I moved things to pkg, I kept it around because it seemed like it could be useful for us in the future.

**Comment by rminnich** [comment]
I think we both felt that way. Maybe we should remove it and vendor it back should we ever need it?

**Comment by bkochendorfer** [comment]
Would you like me to remove it from this PR? I could, and would not mind, submitting a quick follow up PR which just removes `memmap`.

**Comment by rminnich** [comment]
no, this PR is excellent, and if you want to remove mmap I like your idea of a separate PR. Go ahead and push this in when you're ready.

Thanks!
Would you like to be added to our contributors group if you are not there? Could you do some reviews?

**Comment by bkochendorfer** [comment]
I do not believe I have access to merge or write to this repository. I am still learning this tool, but can certainly try to do some reviews!

**Pull request merged**
