### PR TITLE
For some reason which_test.go disappeared, I'm just uploading it again.

### PR DESCRIPTION
**Pull request by rafaelcn**
Signed-off-by: Rafael Campos Nunes <rafaelnunes@engineer.com>

### CODE REVIEW

**Comment by rminnich** [comment]
Please don't merge this yet.

**Comment by rafaelcn** [comment]
No problem, actually you will have to approve it.

**Comment by rafaelcn** [comment]
Finally I got it. I tested inside u-root and it works, let me know if something went wrong :-)

**Comment by rminnich** [comment]
LGTM

**Comment by rminnich** [comment]
darn it! you need to rebase.

**Comment by rafaelcn** [comment]
I did a rebase just now. 

```git pull origin master --rebase
git push rafaelcn which -f````

**Pull request merged**
