### PR TITLE
Correct description and synopsis for ed

### PR DESCRIPTION
**Pull request by osresearch**

### CODE REVIEW

**Comment by hugelgupf** [comment]
Looking into why CI failed. I just added that check.

**Comment by hugelgupf** [comment]
Hah, not a failure -- there's some whitespace character (trailing space?) gofmt doesn't like in the package comment.

**Comment by rminnich** [comment]
hmm. I should probably just remove ed unless someone other than me ever uses it. I don't much like it. except for binary editing. If I'm the only user, ever, I'm ok with removal.

**Comment by rminnich** [comment]
I suppose for the corrected synopsis alone we have to keep it.

**Pull request merged**
