### PR TITLE
Example uinit.go

### PR DESCRIPTION
**Pull request by SvenDowideit**
writing down some of what I unearthed - for eg #328

I'd love some suggestions - I like what I'm seeing :)

### CODE REVIEW

**Comment by rminnich** [comment]
Sorry this took so long. What about this _examples directory -- where would you want to put it? Should this just be in the wiki somewhere?

**Comment by SvenDowideit** [comment]
I'm happy to go with whatever you want - though the benefit of it being in a git repo, is that it can then also be used directly in an example - in the way I've used it in the Makefile.

**Comment by rminnich** [comment]
I liked the idea of an Examples directory too. You are newer on this project than me so I value your ideas ...if you'd like it in the git repo, let's pick a name other than _example?

**Comment by hugelgupf** [comment]
Mind rebasing and squashing these commits? I'd like to get it in.

**Comment by SvenDowideit** [comment]
@hugelgupf done - with a few fixes here & there :)

**Pull request merged**
