### PR TITLE
cmds/core/truncate: Add optional -o flag

### PR DESCRIPTION
**Pull request by TimRots**
This PR will add an optional -o flag to cmds/core/truncate
which will treat SIZE as number of IO blocks instead of bytes.

```shell
$ ./truncate -h
Usage of truncate [-c] [-o] -s size file...:
  -c	Do not create files.
  -o	treat SIZE as number of IO blocks instead of bytes
  -s value
    	Size in bytes, prefixes +/- are allowed (default 1B)
$ for i in {1..4};{ ./truncate -o -s ${i} foo ;ls -l foo; }
-rw-r--r-- 1 x x 4096 Mar 13 00:55 foo
-rw-r--r-- 1 x x 8192 Mar 13 00:55 foo
-rw-r--r-- 1 x x 12288 Mar 13 00:55 foo
-rw-r--r-- 1 x x 16384 Mar 13 00:55 foo
$for i in 1 1 1 1;{ ./truncate -o -s -${i} foo ;ls -l foo; }
-rw-r--r-- 1 x x 12288 Mar 13 00:55 foo
-rw-r--r-- 1 x x 8192 Mar 13 00:55 foo
-rw-r--r-- 1 x x 4096 Mar 13 00:55 foo
-rw-r--r-- 1 x x 0 Mar 13 00:55 foo
```

Signed-off-by: Tim Rots <tim.rots@protonmail.ch>

### CODE REVIEW

**Comment by rminnich** [comment]
This is a weird option to me, given that size can be in units of K and so on. What's the case for adding this complexity? I am happy to hear there is a reason, just want to be sure.

**Comment by TimRots** [comment]
> What's the case for adding this complexity?

obscure sparse files

**Comment by rminnich** [comment]
I am really not trying to be too annoying about this but the classic truncate with block size is done via dd.

dd of=whatever bs=bigk seek=bignumber if=/dev/zero count=something


Do we need this additional way?

I guess we do as that will still write some blocks and we don't want that?

**Comment by TimRots** [comment]
You are asking the right questions, and I should've replied more mindful. Sorry for this.

This additional way is not needed indeed. I made the wrong assumption some-one else had a use case, as this was mentioned in the projects roadmap. 

Would you like me to close the PR?

**Pull request closed without merging**
