### PR TITLE
Update pci-ids and embed them

### PR DESCRIPTION
**Pull request by majst01**
Update the pci-ids with the most recent version from https://pci-ids.ucw.cz/ to get newer models of Nvidia GPUs supported. Also use go:embed to instead of a copy inside the go file.

Test was adopted to the company name change which happened since then.

### CODE REVIEW

**Review by Gerrit91 — APPROVED** [review]

**Comment by majst01** [comment]
some unrelated tests fail, but duno why

**Comment by hugelgupf** [comment]
Can you compare the binary size pre-embedding and post-embedding? I believe the string was chosen because the binary size is smaller.

**Comment by hugelgupf** [comment]
> some unrelated tests fail, but duno why

```
2024-03-18T11:35:57.9245609Z === RUN   TestSetVendorDeviceName/Lookup_Using_ID_1055_Device_e420
2024-03-18T11:35:57.9246558Z     devices_test.go:134: Vendor mismatch, got: "Microchip Technology / SMSC", want: "Efar Microsystems"
2024-03-18T11:35:57.9246923Z --- FAIL: TestSetVendorDeviceName (0.03s)
2024-03-18T11:35:57.9247806Z     --- PASS: TestSetVendorDeviceName/Lookup_Using_ID_80ee_Device_cafe (0.02s)
2024-03-18T11:35:57.9248531Z     --- FAIL: TestSetVendorDeviceName/Lookup_Using_ID_1055_Device_e420 (0.00s)
```

**Comment by majst01** [comment]
> > some unrelated tests fail, but duno why
> 
> ```
> 2024-03-18T11:35:57.9245609Z === RUN   TestSetVendorDeviceName/Lookup_Using_ID_1055_Device_e420
> 2024-03-18T11:35:57.9246558Z     devices_test.go:134: Vendor mismatch, got: "Microchip Technology / SMSC", want: "Efar Microsystems"
> 2024-03-18T11:35:57.9246923Z --- FAIL: TestSetVendorDeviceName (0.03s)
> 2024-03-18T11:35:57.9247806Z     --- PASS: TestSetVendorDeviceName/Lookup_Using_ID_80ee_Device_cafe (0.02s)
> 2024-03-18T11:35:57.9248531Z     --- FAIL: TestSetVendorDeviceName/Lookup_Using_ID_1055_Device_e420 (0.00s)
> ```

Thanks, fixed

**Comment by majst01** [comment]
> Can you compare the binary size pre-embedding and post-embedding? I believe the string was chosen because the binary size is smaller.

The pci-ids i submitted are bigger, so the resulting binary will be bigger.

But when i create two main.go one which embeds a file and the other one which adds the content of the file inline as byte slize and compile both i got this:

```go
package main

import (
	_ "embed"
	"fmt"
)

//go:embed content.txt
var content []byte

func main() {
	fmt.Println(string(content))
}
```

vs:

```go
package main

import (
	_ "embed"
	"fmt"
)

var content = []byte(`
#
#	List of PCI ID's
#
#	Version: 2024.02.02
#	Date:    2024-02-02 14:41:33
#
#	Maintained by Albert Pool, Martin Mares, and other volunteers from
#	the PCI ID Project at https://pci-ids.ucw.cz/.
#
#	New data are always welcome, especially if they are accurate. If you have
#	anything to contribute, please follow the instructions at the web site.
#
#	This file can be distributed under either the GNU General Public License
#	(version 2 or higher) or the 3-clause BSD License.
#
#	The database is a compilation of factual data, and as such the copyright
#	only covers the aggregation and formatting. The copyright is held by
#	Martin Mares and Albert Pool.
#

# Vendors, devices and subsystems. Please keep sorted.
`)

func main() {
	fmt.Println(string(content))
}
``` 

Result:

```
-rw-rw-r-- 1 stefan stefan     715 Mär 19 07:28 content.txt
-rwxrwxr-x 1 stefan stefan 1893233 Mär 19 07:29 embed
-rw-rw-r-- 1 stefan stefan     833 Mär 19 07:29 main.go
-rwxrwxr-x 1 stefan stefan 1893241 Mär 19 07:30 no-embed
```

there is a small benefit for the embed case, but i doubt there will be a relevant difference for larger content.

Is this a valid comparison ?

**Comment by rminnich** [comment]
thanks for doing the embedding, I wrote that before embedding existed :-)
very nice to see htis improvement.

**Review by rminnich — APPROVED** [review]

**Comment by majst01** [comment]
Thanks guys !

**Pull request merged**
