### PR TITLE
Fix /etc/ lossage in CreateRootfs

### PR DESCRIPTION
**Pull request by rjkroege**
With this PR, `CreateRootfs()` in `root_linux.go` uses the `NoFollowSymlinks` option to correctly handle broken symlinks found in `/etc` when setting up the filesystems.\n

### CODE REVIEW

**Review by rminnich — COMMENTED** [review]
Thanks!
Can you run gofmt, then I can approve this.

**Comment by rjkroege** [comment]
Rebased and hopefully fixed the issues.

**Comment by rjkroege** [comment]
@rminnich Can you take another look. Also: the failing `build_and_test` is significant?

**Comment by rminnich** [comment]
it certainly looks fine, I wonder if your fix found a broken test?

**Comment by rjkroege** [comment]
@rminnich with your merge, all the tests pass except the in-the-noise change to coverage. LGTM maybe or should I go write some tests? 😊

**Review by rminnich — APPROVED** [review]

**Review by rminnich — APPROVED** [review]

**Pull request merged**
