### PR TITLE
ESXi pxeboot support

### PR DESCRIPTION
**Pull request by hugelgupf**
Requires #1747 to be merged first. I'll be very happy when we do this the EFI way.

### CODE REVIEW

**Comment by yurinnick** [comment]
Thanks for doing this! #1747 is merged, could you please merge this PR?

**Comment by rminnich** [comment]
is there a path forward? Or is this still relevant? Seems nice to have!

**Comment by hugelgupf** [comment]
Would you mind seeing if David wants to pick it up? It prob takes some
testing. A combination of the pxeboot and esxiboot VM tests would probably
be cool.

I can rebase this some time but it'd be good to get someone new familiar
with the code base etc. Lmk after vaca

**Comment by 10000TB** [comment]
>  It prob takes some testing

what testing gap I can help with ? 

--------------------------------------

ME: looking at changes from #1747, and here:  I can read changes / refactorings done to esxi, esxiboot and boot so boot can work, and looks like here hook it up in netboot. ----- can read changes, but couldn't quite connect those dots; I also have a lot questions on the bg of this work (just curious, but testing and close this can probably happen first)

**Comment by 10000TB** [comment]
I had a chat with @hugelgupf yesterday, what remains is adding a qemu based integration test similar to `esxit_boot_test.go`.

I'll help with that.

for update, so far:

* I managed to pull together the setup locally (with an internal version of ESXi disk img), and running `esxi_boot_test.go`. But the kernel `bzImage` I built is panicking, so I was not able to repro the test on my end.

next:

* get that test working for me
* add a new one but involves a pxeboot

**Comment by rminnich** [comment]
Cleaning out PRs > 1yo

**Pull request closed without merging**
