### PR TITLE
Update go to 1.21 in go.mod

### PR DESCRIPTION
**Pull request by rminnich**
Code that uses error.Join is failing in CI.

### CODE REVIEW

**Comment by orangecms** [comment]
The Go versions used in CI also need upgrading.

**Comment by orangecms** [comment]
`.github/workflows/go.yml` replace all the 1.19 with 1.21 there

**Review by orangecms — APPROVED** [review]
We could recommend Go 1.21 for RISC-V because it fixes the unaligned access issues.
But that'd be an extra thing. Let's get this here in! 🚀

**Comment by rminnich** [comment]
I think as soon as 1.22 comes out we should roll the u-root command forward.

**Comment by MDr164** [comment]
> I think as soon as 1.22 comes out we should roll the u-root command forward.

I'm in favor to stay always one version behind unless there is a crucial new feature you need. The rationale is that the Go team always supports the **two** latest stable releases and distributions are not always that fast to catch up. So in general I like targeting a modern toolchain but always the oldest one supported with security fixes to get the largest amount of users to actually build without any hassle.

**Pull request merged**
