### PR TITLE
Fix strings.TrimRight/TrimSuffix usage bug

### PR DESCRIPTION
**Pull request by sjwheel**
Fixes issue #2402

### CODE REVIEW

**Review by 10000TB — APPROVED** [review]
Thank you Steven

**Comment by 10000TB** [comment]
Run `git commit --amend --signoff` to sign off --- so it will pass our `DCO` check.

the arm test failure is likely a red herring

**Review by rminnich — APPROVED** [review]
ow. That's a nice catch.

**Comment by rminnich** [comment]
Problem is that one of these commits is missing the DCO. I have fixed it in #2416. Closing this one now.

**Pull request closed without merging**
