### PR TITLE
Use ioutil.Discard instead of self-written nothingWriter.

### PR DESCRIPTION
**Pull request by hugelgupf**
Just found this, figured I'd slim down my code a bit.

### CODE REVIEW

**Comment by hugelgupf** [comment]
It already does that. Note that inFile will use io.NewSectionReader if it isn't using stdin.

**Comment by hugelgupf** [comment]
It should probably be slightly different -- it should attempt to Seek, and use the streamingSectionReader if ESPIPE is returned from seek(2).

**Comment by rminnich** [comment]
yes.

**Comment by rminnich** [comment]
do you have the ability to push the button and merge this? If not I will add you. I just don't remember.

**Pull request merged**
