### PR TITLE
dd: use unit package

### PR DESCRIPTION
**Pull request by rck**
This is just a follow up to the unit package that got recently merged.

As my time is currently a bit limited, this conversions will drop in as individual pull requests, tool per tool. Hope that is okay.

I tested it as committed, with the exception that the last test (the multiple GB memory bomb) was disabled.

### CODE REVIEW

**Comment by rck** [comment]
okayyyy. The failed test does not really look like it was caused by my code...

**Comment by bensallen** [comment]
Rerunning it.

**Comment by rck** [comment]
Thanks @bensallen

**Comment by bensallen** [comment]
Should github.com/rck/unit be brought into the main project, eg. pkg/unit?

**Comment by bensallen** [comment]
- In github.com/rck/unit all exported functions/methods/variables should have a commented added for Godoc. 
- Two gometalinter items:

```
unit.go:25:18:warning: should omit type map[string]int64 from declaration of var DefaultUnits; it will be inferred from the right-hand side (golint)
unit_test.go:9:7:warning: should omit type map[string]int64 from declaration of var m; it will be inferred from the right-hand side (golint)
```

**Comment by rck** [comment]
- For the docs and metalinter: I will fix that and update the PR
- Vendor vs. pkg/unit: Hm, I don't really care. As it is generic and not specific to u-root, I slightly favor vendoring it.

**Comment by rck** [comment]
Okay, "famous last words", but I think this package will not have to many changes. It worked for truncate (which has these nasty explicit signs), dd (which has uncommon units like "c"), and it works for cmp (where the offsets are actually not flags). So I think it is stable and already has all the features. The last pull was just "silencing metalinter".

That said, I still don't care ;-). You guys make that decision, and I continue with the next PR wherever it then is.

**Pull request merged**
