### PR TITLE
Update circleci docker image

### PR DESCRIPTION
**Pull request by rjoleary**
The big change is the switch to Go 1.15 and QEMU 6.0.0.

Signed-off-by: Ryan O'Leary <ryanoleary@google.com>

### CODE REVIEW

**Comment by rjoleary** [comment]
It looks like the arm64 Docker container does not build anymore. Some issue in the qemu configure script (logs are sparse).

**Review by rminnich — APPROVED** [review]

**Review by rminnich — DISMISSED** [review]

**Comment by rjoleary** [comment]
```
        qemu-system-x86_64: -device ide-drive,drive=disk,bus=ahci.0: 'ide-drive' is not a valid device model name
```

Maybe we should switch to SATA.

**Comment by rjoleary** [comment]
https://lists.gnu.org/archive/html/qemu-block/2019-10/msg00491.html

**Comment by rjoleary** [comment]
@hugelgupf I think this might be a bug in how we're parsing the output of `go test` from the QEMU serial?

See:

```
    integration.go:146: 2021/07/26 20:45:35 serial: === RUN   TestOpenSignedFile
    integration.go:146: 2021/07/26 20:46:00 serial: testing: warning: no tests to run
    integration.go:146: 2021/07/26 20:46:00 serial: PASS
```

Which seems fine.

And then further down:

```
    gotest.go:127: Test github.com/u-root/u-root/pkg/vfile.TestOpenSignedFile left in state running:
        === RUN   TestOpenSignedFile
```

Why only arm64? Is the output of `go test` stable across Go versions?

**Comment by rjoleary** [comment]
> === RUN   TestOpenSignedFile

Hmmmm, this log output isn't making much sense. There should be a line after this like "--- PASS: TestOpenSignedFile (0.02s)"

**Comment by thanm** [comment]
> the output of "go test" is not stable from release to release

With that said, I agree that it does seem as though the "Pass: TestOpenSignedFile" is missing. Don't have a good theory there.

**Comment by rjoleary** [comment]
I reran the circleci and this seems to be consistent.

```
    integration.go:146: 2021/07/28 02:58:02 serial: === RUN   TestFromZip
    integration.go:146: 2021/07/28 02:58:02 serial: --- PASS: TestFromZip (0.15s)
    integration.go:146: 2021/07/28 02:58:02 serial: PASS
    integration.go:146: 2021/07/28 02:58:03 serial: === RUN   TestOpenSignedFile
    integration.go:146: 2021/07/28 02:58:28 serial: testing: warning: no tests to run
    integration.go:146: 2021/07/28 02:58:28 serial: PASS
    integration.go:146: 2021/07/28 02:58:28 serial: testing: warning: no tests to run
    integration.go:146: 2021/07/28 02:58:28 serial: PASS
```

**Comment by rjoleary** [comment]
If I only run the tests in the vfile package, it works:

```
    integration.go:146: 2021/07/28 04:32:41 serial: === RUN   TestOpenSignedFile~
    integration.go:146: 2021/07/28 04:32:48 serial: === RUN   TestOpenSignedFile/signed_file~
    integration.go:146: 2021/07/28 04:32:48 serial: === RUN   TestOpenSignedFile/signed_file_w/_two_signatures_(key1_ring)~
    integration.go:146: 2021/07/28 04:32:48 serial: === RUN   TestOpenSignedFile/signed_file_w/_two_signatures_(key2_ring)~
    integration.go:146: 2021/07/28 04:32:48 serial: === RUN   TestOpenSignedFile/nil_keyring~
    integration.go:146: 2021/07/28 04:32:48 serial: === RUN   TestOpenSignedFile/non-nil_empty_keyring~
    integration.go:146: 2021/07/28 04:32:48 serial: === RUN   TestOpenSignedFile/signed_file_does_not_match_keyring~
    integration.go:146: 2021/07/28 04:32:48 serial: === RUN   TestOpenSignedFile/unsigned_file~
    integration.go:146: 2021/07/28 04:32:48 serial: === RUN   TestOpenSignedFile/file_does_not_exist~
    integration.go:146: 2021/07/28 04:32:48 serial: --- PASS: TestOpenSignedFile (6.59s)~
    integration.go:146: 2021/07/28 04:32:48 serial:     --- PASS: TestOpenSignedFile/signed_file (0.02s)~
    integration.go:146: 2021/07/28 04:32:48 serial:     --- PASS: TestOpenSignedFile/signed_file_w/_two_signatures_(key1_ring) (0.00s)~
    integration.go:146: 2021/07/28 04:32:48 serial:     --- PASS: TestOpenSignedFile/signed_file_w/_two_signatures_(key2_ring) (0.00s)~
    integration.go:146: 2021/07/28 04:32:48 serial:     --- PASS: TestOpenSignedFile/nil_keyring (0.01s)~
    integration.go:146: 2021/07/28 04:32:48 serial:     --- PASS: TestOpenSignedFile/non-nil_empty_keyring (0.00s)~
    integration.go:146: 2021/07/28 04:32:48 serial:     --- PASS: TestOpenSignedFile/signed_file_does_not_match_keyring (0.00s)~
    integration.go:146: 2021/07/28 04:32:48 serial:     --- PASS: TestOpenSignedFile/unsigned_file (0.00s)~
    integration.go:146: 2021/07/28 04:32:48 serial:     --- PASS: TestOpenSignedFile/file_does_not_exist (0.00s)~
    integration.go:146: 2021/07/28 04:32:48 serial: === RUN   TestOpenHashedFile~
    integration.go:146: 2021/07/28 04:32:48 serial: === RUN   TestOpenHashedFile/correct_hash~
    integration.go:146: 2021/07/28 04:32:48 serial: === RUN   TestOpenHashedFile/wrong_hash~
    integration.go:146: 2021/07/28 04:32:48 serial: === RUN   TestOpenHashedFile/no_hash~
    integration.go:146: 2021/07/28 04:32:48 serial: === RUN   TestOpenHashedFile/empty_file~
    integration.go:146: 2021/07/28 04:32:48 serial: === RUN   TestOpenHashedFile/nonexistent_file~
    integration.go:146: 2021/07/28 04:32:48 serial: --- PASS: TestOpenHashedFile (0.03s)~
    integration.go:146: 2021/07/28 04:32:48 serial:     --- PASS: TestOpenHashedFile/correct_hash (0.01s)~
    integration.go:146: 2021/07/28 04:32:48 serial:     --- PASS: TestOpenHashedFile/wrong_hash (0.01s)~
    integration.go:146: 2021/07/28 04:32:48 serial:     --- PASS: TestOpenHashedFile/no_hash (0.00s)~
    integration.go:146: 2021/07/28 04:32:48 serial:     --- PASS: TestOpenHashedFile/empty_file (0.00s)~
    integration.go:146: 2021/07/28 04:32:48 serial:     --- PASS: TestOpenHashedFile/nonexistent_file (0.00s)~
    integration.go:146: 2021/07/28 04:32:48 serial: PASS~
    integration.go:146: 2021/07/28 04:32:48 serial: 1970/01/01 00:00:08 Not collecting kernel coverage because "/sys/kernel/debug/gcov" does not exist~
    integration.go:146: 2021/07/28 04:32:48 serial: 1970/01/01 00:00:08 TESTS PASSED MARKER~
```

**Comment by rjoleary** [comment]
I was able to reproduce the error with testing only two packages in the gotest vm test:

```
cmd := exec.Command("go", "list",
        "github.com/u-root/u-root/pkg/uzip",
        "github.com/u-root/u-root/pkg/vfile",
)
```

It is flaky and fails 9/10 times. When it passes, the logs look normal as expected.

On the other hand:

```
        cmd := exec.Command("go", "list",
                "github.com/u-root/u-root/pkg/vfile",
        )
```

Passes 10/10 times.

**Comment by rjoleary** [comment]
For the record, it also passes 10/10 times when run on the x86 host outside of qemu:

```
for i in $(seq 10); do go test -count=1 -v github.com/u-root/u-root/pkg/uzip github.com/u-root/u-root/pkg/vfile; done
```

**Comment by rjoleary** [comment]
I improved the logging for the gotest vmtest. Previously, the exit status was ignored and the context was cancelled without enough time to get the stack trace out.

When it fails, it is timing out. I tried increasing the timeout to 40s to no avail:

```
    integration.go:146: 2021/07/28 05:52:49 serial: === RUN   TestOpenSignedFile~
    integration.go:146: 2021/07/28 05:53:29 serial: panic: test timed out after 40s~
    integration.go:146: 2021/07/28 05:53:29 serial: ~
    integration.go:146: 2021/07/28 05:53:29 serial: goroutine 7 [running]:~
    integration.go:146: 2021/07/28 05:53:29 serial: testing.(*M).startAlarm.func1()~
    integration.go:146: 2021/07/28 05:53:29 serial: 	/usr/local/go/src/testing/testing.go:1618 +0xc8~
    integration.go:146: 2021/07/28 05:53:29 serial: created by time.goFunc~
    integration.go:146: 2021/07/28 05:53:29 serial: 	/usr/local/go/src/time/sleep.go:167 +0x40~
    integration.go:146: 2021/07/28 05:53:29 serial: ~
    integration.go:146: 2021/07/28 05:53:29 serial: goroutine 1 [chan receive]:~
    integration.go:146: 2021/07/28 05:53:29 serial: testing.(*T).Run(0x4000001080, 0x1b0f66, 0x12, 0x1baaf0, 0x2)~
    integration.go:146: 2021/07/28 05:53:29 serial: 	/usr/local/go/src/testing/testing.go:1169 +0x234~
    integration.go:146: 2021/07/28 05:53:29 serial: testing.runTests.func1(0x4000000f00)~
    integration.go:146: 2021/07/28 05:53:29 serial: 	/usr/local/go/src/testing/testing.go:1439 +0x74~
    integration.go:146: 2021/07/28 05:53:29 serial: testing.tRunner(0x4000000f00, 0x4000050dc8)~
    integration.go:146: 2021/07/28 05:53:29 serial: 	/usr/local/go/src/testing/testing.go:1123 +0xec~
    integration.go:146: 2021/07/28 05:53:29 serial: testing.runTests(0x400000c1e0, 0x2a7640, 0x2, 0x2, 0xa7f81dea99dc43c0, 0x955b0f151, 0x2af680, 0x7f840838f0)~
    integration.go:146: 2021/07/28 05:53:29 serial: 	/usr/local/go/src/testing/testing.go:1437 +0x20c~
    integration.go:146: 2021/07/28 05:53:29 serial: testing.(*M).Run(0x4000084000, 0x0)~
    integration.go:146: 2021/07/28 05:53:29 serial: 	/usr/local/go/src/testing/testing.go:1345 +0x1ac~
    integration.go:146: 2021/07/28 05:53:29 serial: main.main()~
    integration.go:146: 2021/07/28 05:53:29 serial: 	_testmain.go:45 +0xd4~
    integration.go:146: 2021/07/28 05:53:29 serial: ~
    integration.go:146: 2021/07/28 05:53:29 serial: goroutine 6 [runnable]:~
    integration.go:146: 2021/07/28 05:53:29 serial: math/big.nat.montgomery(0x40002c2900, 0x20, 0x24, 0x40002b4640, 0x10, 0x26, 0x40002b4640, 0x10, 0x26, 0x40001b3680, ...)~
    integration.go:146: 2021/07/28 05:53:29 serial: 	/usr/local/go/src/math/big/nat.go:226 +0x160~
    integration.go:146: 2021/07/28 05:53:29 serial: math/big.nat.expNNMontgomery(0x40002b4640, 0x10, 0x26, 0x40002b2dc0, 0x10, 0x14, 0x40002b2c80, 0x10, 0x14, 0x40001b3680, ...)~
    integration.go:146: 2021/07/28 05:53:29 serial: 	/usr/local/go/src/math/big/nat.go:1447 +0x5d0~
    integration.go:146: 2021/07/28 05:53:29 serial: math/big.nat.expNN(0x40002b2e60, 0x10, 0x14, 0x40002b2dc0, 0x10, 0x14, 0x40002b2c80, 0x10, 0x14, 0x40001b3680, ...)~
    integration.go:146: 2021/07/28 05:53:29 serial: 	/usr/local/go/src/math/big/nat.go:1261 +0x650~
    integration.go:146: 2021/07/28 05:53:29 serial: math/big.nat.probablyPrimeMillerRabin(0x40001b3680, 0x10, 0x14, 0x15, 0x5a4dd0c2a1bf6501, 0x5a4dd0c2a1bf6500)~
    integration.go:146: 2021/07/28 05:53:29 serial: 	/usr/local/go/src/math/big/prime.go:106 +0x348~
    integration.go:146: 2021/07/28 05:53:29 serial: math/big.(*Int).ProbablyPrime(0x400000c280, 0x14, 0x4000037838)~
    integration.go:146: 2021/07/28 05:53:29 serial: 	/usr/local/go/src/math/big/prime.go:78 +0x2d0~
    integration.go:146: 2021/07/28 05:53:29 serial: crypto/rand.Prime(0x1c76a0, 0x40000581e0, 0x400, 0x400000c200, 0x0, 0x0)~
    integration.go:146: 2021/07/28 05:53:29 serial: 	/usr/local/go/src/crypto/rand/util.go:99 +0x120~
    integration.go:146: 2021/07/28 05:53:29 serial: crypto/rsa.GenerateMultiPrimeKey(0x1c76a0, 0x40000581e0, 0x2, 0x800, 0x1, 0x4000018120, 0x17)~
    integration.go:146: 2021/07/28 05:53:29 serial: 	/usr/local/go/src/crypto/rsa/rsa.go:302 +0x118~
    integration.go:146: 2021/07/28 05:53:29 serial: crypto/rsa.GenerateKey(0x1c76a0, 0x40000581e0, 0x800, 0x4, 0x1aed2f, 0x9)~
    integration.go:146: 2021/07/28 05:53:29 serial: 	/usr/local/go/src/crypto/rsa/rsa.go:242 +0x40~
    integration.go:146: 2021/07/28 05:53:29 serial: github.com/u-root/u-root/vendor/golang.org/x/crypto/openpgp.NewEntity(0x1adf26, 0x4, 0x1adf26, 0x4, 0x1aed2f, 0x9, 0x0, 0x0, 0x0, 0x0)~
    integration.go:146: 2021/07/28 05:53:29 serial: 	/home/circleci/go/src/github.com/u-root/u-root/vendor/golang.org/x/crypto/openpgp/keys.go:518 +0xbc~
    integration.go:146: 2021/07/28 05:53:29 serial: github.com/u-root/u-root/pkg/vfile.TestOpenSignedFile(0x4000001080)~
    integration.go:146: 2021/07/28 05:53:29 serial: 	/home/circleci/go/src/github.com/u-root/u-root/pkg/vfile/vfile_test.go:69 +0x6c~
    integration.go:146: 2021/07/28 05:53:29 serial: testing.tRunner(0x4000001080, 0x1baaf0)~
    integration.go:146: 2021/07/28 05:53:29 serial: 	/usr/local/go/src/testing/testing.go:1123 +0xec~
    integration.go:146: 2021/07/28 05:53:29 serial: created by testing.(*T).Run~
    integration.go:146: 2021/07/28 05:53:29 serial: 	/usr/local/go/src/testing/testing.go:1168 +0x218~
    integration.go:146: 2021/07/28 05:53:29 serial: 1970/01/01 00:00:42 Not collecting kernel coverage because "/sys/kernel/debug/gcov" does not exist~
    gotest.go:127: Test github.com/u-root/u-root/pkg/vfile.TestOpenSignedFile left in state running:
        === RUN   TestOpenSignedFile
        Error: test for "github.com/u-root/u-root/pkg/vfile" exited early: exit status 2
```

It seems to be stuck doing some math crypto stuff.

**Comment by rjoleary** [comment]
Oh no, amd64 is failing now too!

**Comment by rjoleary** [comment]
Perhaps this has something to do with virtio-rng?

**Comment by hugelgupf** [comment]
> > Why only arm64? Is the output of `go test` stable across Go versions?
> 
> [From the peanut gallery]
> 
> FWIW, the output of "go test" is not stable from release to release; the Go team does periodically make changes to the output format to improve clarity and readability. In this CL you are moving from Go 1.13 to Go 1.15; in that range there were 27 commits to the Go testing package, including
> 
> https://go-review.googlesource.com/c/go/+/127120
> https://go-review.googlesource.com/c/go/+/179599
> https://go-review.googlesource.com/c/go/+/229085
> https://go-review.googlesource.com/c/go/+/235997
> 
> all of which change test output in some way. From the test log it looks as though maybe you are parsing the output of "go test -test.v" ?

@thanm we use Go's very own cmd/test2json to parse the output of go test -test.v. The tests are compiled as binaries, shared with the VM, and run in the VM basically as ./testbinary -test.v | test2json -t -p <pkgname> as seen here: https://github.com/u-root/u-root/blob/6a6772a6c7b468df4a717f5eb45506750b1d5233/integration/testcmd/gotest/uinit/gotest.go#L55

I'm checking out the failure.

**Comment by hugelgupf** [comment]
Running locally with Go 1.15 and my pre-installed QEMU passes. Checking out qemu 6.0.0 now.

**Comment by hugelgupf** [comment]
I used:

- go1.15.14,
- qemu from HEAD (slightly ahead of v6.0.0)
- kernel built exactly like the one in docker image (although built with gcc-6, and I don't know what the Docker image builds it with)

and I can't repro the issue locally yet. I'll switch to sshing into circleci and checking that out. Maybe it just runs out of memory or nearly runs out of memory and spends a lot of time swapping around.

**Comment by hugelgupf** [comment]
Something peculiar about running the test locally, however, is that it takes 8 seconds to run, and that time is not attributed to any individual test:

```
    integration.go:146: 2021/07/28 18:04:41 serial: === RUN   TestOpenSignedFile~
    integration.go:146: 2021/07/28 18:04:49 serial: === RUN   TestOpenSignedFile/signed_file~
    integration.go:146: 2021/07/28 18:04:49 serial: === RUN   TestOpenSignedFile/signed_file_w/_two_signatures_(key1_ring)~
    integration.go:146: 2021/07/28 18:04:49 serial: === RUN   TestOpenSignedFile/signed_file_w/_two_signatures_(key2_ring)~
    integration.go:146: 2021/07/28 18:04:49 serial: === RUN   TestOpenSignedFile/nil_keyring~
    integration.go:146: 2021/07/28 18:04:49 serial: === RUN   TestOpenSignedFile/non-nil_empty_keyring~
    integration.go:146: 2021/07/28 18:04:49 serial: === RUN   TestOpenSignedFile/signed_file_does_not_match_keyring~
    integration.go:146: 2021/07/28 18:04:49 serial: === RUN   TestOpenSignedFile/unsigned_file~
    integration.go:146: 2021/07/28 18:04:50 serial: === RUN   TestOpenSignedFile/file_does_not_exist~
    integration.go:146: 2021/07/28 18:04:50 serial: --- PASS: TestOpenSignedFile (8.10s)~
    integration.go:146: 2021/07/28 18:04:50 serial:     --- PASS: TestOpenSignedFile/signed_file (0.03s)~
    integration.go:146: 2021/07/28 18:04:50 serial:     --- PASS: TestOpenSignedFile/signed_file_w/_two_signatures_(key1_ring) (0.01s)~
    integration.go:146: 2021/07/28 18:04:50 serial:     --- PASS: TestOpenSignedFile/signed_file_w/_two_signatures_(key2_ring) (0.00s)~
    integration.go:146: 2021/07/28 18:04:50 serial:     --- PASS: TestOpenSignedFile/nil_keyring (0.03s)~
    integration.go:146: 2021/07/28 18:04:50 serial:     --- PASS: TestOpenSignedFile/non-nil_empty_keyring (0.00s)~
    integration.go:146: 2021/07/28 18:04:50 serial:     --- PASS: TestOpenSignedFile/signed_file_does_not_match_keyring (0.00s)~
    integration.go:146: 2021/07/28 18:04:50 serial:     --- PASS: TestOpenSignedFile/unsigned_file (0.00s)~
    integration.go:146: 2021/07/28 18:04:50 serial:     --- PASS: TestOpenSignedFile/file_does_not_exist (0.00s)~
```

On circleci, a timeout after 25 seconds is the issue.

**Comment by hugelgupf** [comment]
I think it's quite possible that QEMU emulation is just 3x slower on circleci, and that causes the timeout to happen. However, even on Go 1.13, the test takes 8-12 seconds to run. (But let me make sure that it actually uses Go 1.13 to compile the tests -- checking that out.)

**Comment by hugelgupf** [comment]
> I think it's quite possible that QEMU emulation is just 3x slower on circleci, and that causes the timeout to happen. However, even on Go 1.13, the test takes 8-12 seconds to run. (But let me make sure that it actually uses Go 1.13 to compile the tests -- checking that out.)

Of course it doesn't, that part is here:

https://github.com/u-root/u-root/blob/dd0caf30f7efe8affb3205b95072146e7f38a7da/pkg/vmtest/gotest.go#L63

I'll fix that to look for the compiler in GOROOT/bin/go.

**Comment by hugelgupf** [comment]
Posted #2076 for that, but it actually didn't change anything.

Go 1.15.14 (+ qemu-v6 + kernel-v4.17 + no KVM) with only pkg/{vfile,uzip}:

```
--- PASS: TestOpenSignedFile (10.18s)~
```

Go 1.13 (+ all the same):

```
 --- PASS: TestOpenSignedFile (14.05s)
```

If anything, the runtime got better...

**Comment by rjoleary** [comment]
Ron wrote us a `time` command. I'm going to ssh into circleci to see if most the time is sys time or user time.

If it's mostly user time, then it's probably just slow. If it's most sys time, then it's probably blocked on something.

**Comment by rjoleary** [comment]
Looks like it's just slow:

```
    integration.go:146: 2021/07/29 22:45:35 serial: real 32.925~
    integration.go:146: 2021/07/29 22:45:35 serial: user 32.645~
    integration.go:146: 2021/07/29 22:45:35 serial: sys 0.104~
```

**Comment by rjoleary** [comment]
I increased the timeout to 100s and ran it a few times:

```
    integration.go:146: 2021/07/29 22:46:49 serial: real 30.957~
    integration.go:146: 2021/07/29 22:46:49 serial: user 30.740~
    integration.go:146: 2021/07/29 22:46:49 serial: sys 0.100~
```

```
    integration.go:146: 2021/07/29 22:47:18 serial: real 14.848~
    integration.go:146: 2021/07/29 22:47:18 serial: user 14.665~
    integration.go:146: 2021/07/29 22:47:18 serial: sys 0.084~
```

```
    integration.go:146: 2021/07/29 22:48:05 serial: real 33.682~
    integration.go:146: 2021/07/29 22:48:05 serial: user 33.508~
    integration.go:146: 2021/07/29 22:48:05 serial: sys 0.076~
```

```
    integration.go:146: 2021/07/29 22:48:57 serial: real 36.836~
    integration.go:146: 2021/07/29 22:48:57 serial: user 36.629~
    integration.go:146: 2021/07/29 22:48:57 serial: sys 0.100~
```

```
    integration.go:146: 2021/07/29 22:49:58 serial: real 46.793~
    integration.go:146: 2021/07/29 22:49:58 serial: user 46.520~
    integration.go:146: 2021/07/29 22:49:58 serial: sys 0.112~
```

```
    integration.go:146: 2021/07/29 22:50:54 serial: real 41.832~
    integration.go:146: 2021/07/29 22:50:54 serial: user 41.653~
    integration.go:146: 2021/07/29 22:50:54 serial: sys 0.080~
```

```
    integration.go:146: 2021/07/29 22:51:45 serial: real 35.567~
    integration.go:146: 2021/07/29 22:51:45 serial: user 35.374~
    integration.go:146: 2021/07/29 22:51:45 serial: sys 0.080~
```

I wonder why is fluctuates so much? Sometimes it is less than 25s, sometimes 10s of seconds more.

**Comment by rjoleary** [comment]
Any ideas besides these two options?

* Generate the entity one and load it from a file on all subsequent tests.
* Disable this test from running inside qemu.

**Comment by rjoleary** [comment]
> Any ideas besides these two options?
> 
> * Generate the entity once and load it from a file on all subsequent tests.
> * Disable this test from running inside qemu.

I went with the first option.

**Review by rminnich — APPROVED** [review]

**Pull request merged**
