### PR TITLE
Remove elvish

### PR DESCRIPTION
**Pull request by jensdrenhaus**
There are two shell commands in /cmds/core, gosh and enlvish. The default since some time is gosh. 
Both of them take up quite a bit of the overall busybox size, but elvish is by far a heavyweight:

u-root commit 4b12bdb6, May 5:
`makebb ./cmds/core/*` -> 16,98 MB
without elvish 13,29 MB (-3,69)
without gosh 15,17 MB (-1,81)

Remove elvish may be a bit drastic, another option is to move it somewhere else. The point is, that we are telling somehow "With `u-root core` you'll get a neat busybox with lots of common tools at your fingertips in pure go". Is it worth having a redundant shell in that scenario with blows up the bb?

### CODE REVIEW

**Comment by jensdrenhaus** [comment]
What do you think @rminnich , @10000TB , @hugelgupf ?

**Comment by rminnich** [comment]
I can not seeing anyone caring. If there is a concern, move it to exp/, and let's see if there is an issue?

**Comment by hugelgupf** [comment]
Deletion was announced in v0.13.0 slated for v0.14.0 (which became the "new build system" release), so I think this is a good idea now for v0.15.0.

https://github.com/u-root/u-root/releases/tag/v0.13.0

**Comment by rminnich** [comment]
elvish filled a need we had in the past, but I'm happy to see it be dropped.

**Review by rminnich — APPROVED** [review]

**Review by rminnich — APPROVED** [review]

**Review by rminnich — APPROVED** [review]

**Comment by jensdrenhaus** [comment]
This PR reduced the sice of a compressed initramfs incl. cmds/core/* and cmds/exp/* as follows: 
GOARCH='amd64'
GOOS='linux'
```
git checkout d4db45e
go build -a
./u-root ./cmds/core/* ./cmds/exp/*
gzip initramfs.cpio
du initramfs.cpio.gz
```
-> 7956
```
git checkout 2c952d8
go build -a
rm initramfs.cpio.gz
./u-root -o initramfs.cpio ./cmds/core/* ./cmds/exp/*
gzip initramfs.cpio
du initramfs.cpio.gz
```
-> 6372

(7956 - 6372) / 7956 * 100% = 19,91%

**Pull request merged**
