### PR TITLE
Add basic support for ACPI RSDP as to allow linuxboot handovered kernel to detect ACPI tables

### PR DESCRIPTION
**Pull request by vejmarie**
Everything into the subject (I hope)

### CODE REVIEW

**Comment by paulmenzel** [comment]
Could you please rebase the branch instead of having the two merge commits in there?

    $ git rebase origin/master

If you want an interactive rebase, pass the switch `-i`.

**Comment by vejmarie** [comment]
I just tried, but it didn't do anything :(

**Comment by vejmarie** [comment]
In fact 
Add basic infrastructure to support legacy boot in u-root from linuxboot 1423a24
Merge remote-tracking branch 'origin/master' dd88ce8
Merge remote-tracking branch 'origin/master' 0c27456
shouldn't be there. I rebased origin/master before creating the rsdp branch by

git checkout master
git fetch upstream master
git merge origin/master
git rebase origin/master
git branch rsdp
git checkout rsdp

**Comment by vejmarie** [comment]
can't we cherry pick the relevant commit ?

**Comment by GanShun** [comment]
try doing it with -i, then manually drop the merge commits

**Pull request closed without merging**
