### PR TITLE
Rewrite cpio pkg tests as fuzzy tests

### LINKED ISSUE #935: Reenable cpio test
This cpio test compares strings for results. #919 changes the string format. I don't feel like fixing the huge string of results. 

https://github.com/u-root/u-root/blob/master/pkg/cpio/newc_test.go#L26

### PR DESCRIPTION
**Pull request by RiSKeD**
Commit [20f840e](https://github.com/u-root/u-root/pull/2528/commits/20f840e7c1dee7140c4e6b1495000294f6cdd8dc):
I rewrote some of the cpio testing as fuzzing tests, added new ones, and fixed #935. 
The baseline coverage when running `go test` will remain the same, because we are using the same inputs as before as seed inputs for the fuzzing tests.  Additionally if specified using `go test-fuzz=FuzzXXX` any of the tests can be run according to the [Go Fuzzing Docs](https://tip.golang.org/security/fuzz/) as a fuzzing test as well. 

Commit[ 9f57b69](https://github.com/u-root/u-root/pull/2528/commits/9f57b69af7f7ea79f2947ece41eb8cef78a45729):
Provided a failing input which results in a panic for one of the tests when reading a record of a specific format.
I will file a new issue to get it fixed.

I would like to propose extending the CI environment to incorporate these new fuzzing tests in the next step.
[OSS-Fuzz](https://google.github.io/oss-fuzz/) offers a good solution for continuously fuzzing entirely separated from GitHub and CircleCI.

### CODE REVIEW

**Comment by RiSKeD** [comment]
Because of the provisioned input in commit 9f57b69 one of the fuzzing tests will fail until #2529 gets fixed.

More context:  With this fuzzing approach, I also wanted to test for inconsistencies when doing multiple parsing rounds (multiple read-writes). Parsing an object, writing it back, and parsing it again should result in the same struct that was parsed in the first round. By doing this we can also ensure that no unexpected panics are occurring either.

**Comment by RiSKeD** [comment]
So i simplified and condensed the fuzzing into a singular test. What it does:
It tries to parse any generated fuzzing input. If an error occurs, which is not unexpected as even unparseable inputs are generated, the test will just skip to the next input. If an input is parseable though the test will make sure it can be written back to an byte array and parsed back again. The reparsed object then must be identical to the first one. This makes sure that both directions (parsing and write-back) do not alter the underlying object.
Additionally any panics will also be caught.

**Comment by RiSKeD** [comment]
Added a second commits which adds more checks when parsing cpio records.
I ran just short of 4 million different executions in about 30 minutes locally without encountering more errors. 
The fuzzing is reproducible by running the following in the pkgs directory: 
```
GOMAXPROCS=4 GOMEMLIMIT=4GiB go test -fuzz=FuzzReadWriteNewc
```

**Comment by rminnich** [comment]
quick question. We don't want only fuzzy tests, I assume? IOW there is value in the regular tests, since they run quickly and catch simple errors, and then fuzzing tests as well?

**Comment by RiSKeD** [comment]
I would see fuzzing as an addition to the unit tests. But you are right, in newc_test.go one of the the unit tests is very close to the fuzzing tests. But only doing fuzzing would come with some disadvantages. You can use the unit test testvalues as fuzzing seed inputs (which are executed every time), but debugging a fuzzing test can be finicky due to the nondeterministic selection of inputs. And you only want to fuzz in some cases. This was not clear in my previous commit in which rewrote every test to fuzz.

For example: If we have a fuzzing tests (which parses, writes-back, parses, ...) the only "randomly" generated input is the parsed byte-array and not the struct object itself, therefore focusing on a realworld-cases. 

´I will push another commit in this PR for some more extensive documentation.

**Comment by RiSKeD** [comment]
I added the inputs which caused panics in the second commit as seed inputs for the fuzzing test as well. This does two things:
1. These are run everytime we executing `go test` in the CI
2. Coverage is improved as the additional parsing checks i included are now hit as well

**Review by rminnich — APPROVED** [review]

**Pull request merged**
