### PR TITLE
docs/index.html: fix Slack invite link

### PR DESCRIPTION
**Pull request by orangecms**
looks like a confusion with the TLDs :shrug: ^^

### CODE REVIEW

**Comment by hugelgupf** [comment]
how on earth did that even get in?

**Comment by orangecms** [comment]
Please calm down - it happens... :)

Regarding pandoc: It gets slightliy different results depending on the version, I think; I'm on Arch, so it's `yay -S pandoc` for me (or `pacman -S pandoc`, I just use yay so I also get AUR packages...) - and my version is the following:

```sh
$ yay -Qs pandoc
local/haskell-doctemplates 0.8.2-11
    Pandoc-style document templates
local/haskell-pandoc-types 1.20-39
    Types for representing a structured document
local/pandoc 2.9.2.1-56
    Conversion between markup formats
```

What do you prefer, a smaller diff or a more up-to-date build? I don't mind either, really; git makes it easy.

**Comment by hugelgupf** [comment]
an up to date build sounds good to me?

**Comment by orangecms** [comment]
Then it's resolved now :)

**Pull request merged**
