### PR TITLE
cpio: fix to allow a same file as source for multiple extra files

### PR DESCRIPTION
**Pull request by bobuhiro11**
If a same file is specified as source for multiple extra files,
e.g. -files 'README.md:a.txt' -files 'README.md:b.txt', the
contents of the second and subsequent files, e.g. b.txt, are empty.
This is because `ReaderAt` is not initialized after the second time
if the inode of source is duplicated.

```bash
$ go run . -files 'README.md:a.txt' -files 'README.md:b.txt' cmds/core/{init,elvish}
$ lsinitramfs -l /tmp/initramfs.linux_amd64.cpio
-rw-rw-r--   0 root     root        16228 Jan  1  1970 a.txt # file is written successfully.
-rw-rw-r--   0 root     root            0 Jan  1  1970 b.txt # file is empty.
```

### CODE REVIEW

**Comment by 10000TB** [comment]
The original code skips reading it if the same file is attempted to be added into same cpio (`inumber` and `devnumber` have been seen). I don't know why we had that. Just need check if removing it would cause regression for other case(s). Otherwise, this look like a good fix.

Alternative you can do, I guess, is duplicate the file locally first (that may bot be an elegant :)

```
cp README.md README2.md
go run . -files 'README.md:a.txt' -files 'README2.md:b.txt' cmds/core/{init,elvish}
```

**Comment by bobuhiro11** [comment]
@10000TB Thanks for the review!

The unit test was failing and I have fixed it. For some reason the integration test on arm is failing, but I don't know why. Is CI on pull request enough to check regression? If there is anything else to check, please let me know.

Of course I can deal with this issue using workaround you provided, but I think the behavior is counter-intuitive to users and I want to fix it.

**Comment by rminnich** [comment]
oh my gosh was I confused. 
I misunderstood this utterly.
Can you add a test?

**Comment by rminnich** [comment]
> The original code skips reading it if the same file is attempted to be added into same cpio (`inumber` and `devnumber` have been seen). I don't know why we had that. Just need check if removing it would cause regression for other case(s). Otherwise, this look like a good fix.

You have to have that for hard links. Think of two files with the same inumber -- they have the same content. They are literally the same file, just with a different name in different directories.

Breaking hard links breaks all kinds of things, so you have to be careful.

Also, double checking, because I don't recall, but is the path you are checking the full path or just the basename? Just checking the basename will not work well. 

This is really going to need a test in the cpio package, it's very easy to break cpio, some of these issues are tricky.

**Review by rminnich — DISMISSED** [review]
I think this is not quite correct. In fact I am certain it is not. I may be wrong ;-)

If two files have the same number, it is a hard link. That's the definition of a hard link in fact: two files with the same inumber. The name has nothing to do with it.

There's some other problem here and I don't think it is cpio.

I may be wrong but need to be convinced.

**Comment by rminnich** [comment]
Here's a simple example of how it works. h and hosts are the same file (same inode). It's not correct to say
h is a hardlink to hosts
or
hosts is a hardlink to h

rather, h and hosts are both hard links to the same file, with inumber 4213332.
Note that when I create the cpio file, the contents only appears once.

I think the real problem here may be a bug in the u-root package. Still not sure.

rminnich@a300:/tmp$ cat hosts
ONCE
rminnich@a300:/tmp$ ls -li hosts h
4213332 -rw-r--r-- 2 rminnich rminnich 5 May 12 10:31 h
4213332 -rw-r--r-- 2 rminnich rminnich 5 May 12 10:31 hosts
rminnich@a300:/tmp$ cat | cpio -o >h.cpio -H newc
h
hosts
1 block
rminnich@a300:/tmp$ grep -c ONCE hosts
1
rminnich@a300:/tmp$

**Comment by rminnich** [comment]
Further, note that extracting h, even though it shows up as 0 length in the archive, gets the right result:
rminnich@a300:/tmp$ cd /var/tmp
rminnich@a300:/var/tmp$ cpio -iv < /tmp/h.cpio h
h
1 block
rminnich@a300:/var/tmp$ cat h
ONCE
rminnich@a300:/var/tmp$

And, if we extract it all, they have the same inumber.
rminnich@a300:/var/tmp$ cpio -iv < /tmp/h.cpio
h
cpio: hosts linked to h
hosts
1 block
rminnich@a300:/var/tmp$ ls -l hosts h
-rw-r--r-- 2 rminnich rminnich 5 May 12 10:38 h
-rw-r--r-- 2 rminnich rminnich 5 May 12 10:38 hosts

Does u-root cpio do the same thing?

rminnich@a300:~/go/src/github.com/u-root/u-root/cmds/core/cpio$ ./cpio i < /tmp/h.cpio h
rminnich@a300:~/go/src/github.com/u-root/u-root/cmds/core/cpio$ ls -l h
-rw-r--r-- 1 rminnich rminnich 0 May 12 10:39 h
rminnich@a300:~/go/src/github.com/u-root/u-root/cmds/core/cpio$ cat h
rminnich@a300:~/go/src/github.com/u-root/u-root/cmds/core/cpio$ ./cpio i < /tmp/h.cpio hosts
rminnich@a300:~/go/src/github.com/u-root/u-root/cmds/core/cpio$ ls -l hosts
-rw-r--r-- 1 rminnich rminnich 5 May 12 10:39 hosts
rminnich@a300:~/go/src/github.com/u-root/u-root/cmds/core/cpio$ rm hosts h
rminnich@a300:~/go/src/github.com/u-root/u-root/cmds/core/cpio$ ./cpio i < /tmp/h.cpio
rminnich@a300:~/go/src/github.com/u-root/u-root/cmds/core/cpio$ ls -li hosts h
39068555 -rw-r--r-- 1 rminnich rminnich 0 May 12 10:39 h
39068556 -rw-r--r-- 1 rminnich rminnich 5 May 12 10:39 hosts
rminnich@a300:~/go/src/github.com/u-root/u-root/cmds/core/cpio$

nope, it's completely wrong on extract!!!

but it generates ok

rminnich@a300:~/go/src/github.com/u-root/u-root/cmds/core/cpio$ ./cpio o > h.cpio
h
hosts
rminnich@a300:~/go/src/github.com/u-root/u-root/cmds/core/cpio$ cpio -iv < h.cpio
h
hosts
cpio: h linked to hosts
1 block
rminnich@a300:~/go/src/github.com/u-root/u-root/cmds/core/cpio$ ls -li h hosts
39068556 -rw-r--r-- 2 rminnich rminnich 5 May 12 10:41 h
39068556 -rw-r--r-- 2 rminnich rminnich 5 May 12 10:41 hosts

Is your code fixing the extract (i) or create (o) case?

thanks

**Comment by hugelgupf** [comment]
> I checked again. I believe you are fixing the geneate case (i), when what is broken is the extract case (o)

It's the generate case. The original PR message says:

> go run . -files 'README.md:a.txt' -files 'README.md:b.txt' cmds/core/{init,elvish}

is broken. This is a use case where no hard links are involved at all.

**Comment by 10000TB** [comment]
Use same hardlink twice (or more times) to `-files` flag as source file(s) and build into cpio different files (names).

Do we expect those files in cpio, be 1) different directory names / hardlinks to same data. 2) different hardlinks to different data (happen to be identical in content) ?

**Comment by hugelgupf** [comment]
The thing is that u-root initramfses actually don't preserve the link numbers at all.

All [link numbers are set to 0](https://github.com/u-root/u-root/blob/db15641d3c710f1685f6c54bf7e60be726d6425e/pkg/cpio/utils.go#L219) in an effort to make them reproducible. So checking whether README.txt is the same link twice doesn't make sense in that context.

The link is stripped here for u-root initramfses: https://github.com/u-root/u-root/blob/db15641d3c710f1685f6c54bf7e60be726d6425e/pkg/uroot/initramfs/files.go#L230

**Comment by hugelgupf** [comment]
So the PR is trying to solve a reasonable problem: you should be able to include the same file in a u-root initramfs twice. They all end up with the same duplicate inode number of 0 anyway.

I don't have opinions on the how.

**Comment by bobuhiro11** [comment]
Thank you all for your informative comments. They are very helpful.

Now, the function we are modifying in this PR is complicated because it is called from both `u-root` and `cpio` command.
So, based on your comments, please let me first confirm the behavior of those two commands.

1. u-root command: For reproducible, all file paths in `initramfs.linux_amd64.cpio` are replaced with inode number 0. This means that all file paths must be treated as separate files and their contents written to them. In this situation, hardlink does not exist. In other words, even if the same source is specified multiple times, as in `-files 'README.md:a.txt' -files 'README.md:b.txt'`, a.txt and b.txt are unrelated files whose contents must both be written. In this PR, in both cases of a.txt and b.txt, `d.Name ! = i.Name` is false, so the contents are written to both a.txt and b.txt, which is the expected behavior.
2. cpio command: If there are multiple paths pointing to the same inode number, it is sufficient to write their contents only once, since they are hardlinks. Also, in the output cpio file, their inode numbers are the same. In this PR, `d.Name ! = i.Name` is false once (true the second and subsequent times), so the content is written only once, which is the expected behavior.

> Also, double checking, because I don't recall, but is the path you are checking the full path or just the basename? Just checking the basename will not work well.

It is full path, so it seems no problem.

> This is really going to need a test in the cpio package, it's very easy to break cpio, some of these issues are tricky.

For the cpio command, it seems that [a unit test](https://github.com/u-root/u-root/blob/db15641d3c710f1685f6c54bf7e60be726d6425e/cmds/core/cpio/cpio_test.go#L37-L38) involving hardlink already exists.

> I checked again. I believe you are fixing the geneate case (i), when what is broken is the extract case (o)

Yes, it’s for generate case. 

>  feels like behavior should be made similar to linux cpio.

In this PR, I was able to verify that u-root cpio is correctly handling inode numbers.
I think it behaves the same as Linux cpio.

```bash
# building
$ cd ~/u-root;  go build ./cmds/core/cpio/

# creating hardlink
$ cd /tmp
$ echo ONCE > a
$ ln a b
$ ls -il a b
3810801 -rw-rw-r-- 2 bobuhiro11 bobuhiro11 5 May 13 03:29 a
3810801 -rw-rw-r-- 2 bobuhiro11 bobuhiro11 5 May 13 03:29 b

# generating & extracting cpio
$ find [ab] | ~/u-root/cpio  o > test.cpio
$ rm -f a b
$ ~/u-root/cpio i < test.cpio
$ ls -il a b
3810801 -rw-rw-r-- 2 bobuhiro11 bobuhiro11 5 May 13 03:30 a
3810801 -rw-rw-r-- 2 bobuhiro11 bobuhiro11 5 May 13 03:30 b
```

This is my first time touching u-root's codebase, so any comments would be appreciated. Thanks.

**Comment by rminnich** [comment]
so, I am now seeing your point(s)
```
bash-3.2$ cat | cpio -o > /tmp/x.cpio
hosts
hosts
2 blocks
bash-3.2$ cpio -ivt < /tmp/x.cpio
-rw-r--r--   1 rminnich wheel         213 May 14 23:07 hosts
-rw-r--r--   1 rminnich wheel         213 May 14 23:07 hosts
2 blocks
bash-3.2$
```

OK, this PR makes sense to me now, thanks for the comments all.

It does make sense to treat it separately.

**Review by rminnich — APPROVED** [review]

**Pull request merged**
