### PR TITLE
Idea on how to fix issue #2609

### PR DESCRIPTION
**Pull request by robertmin1**
Idea on how to fix i[ssue #2609](https://github.com/u-root/u-root/issues/2609)

### CODE REVIEW

**Review by rminnich — COMMENTED** [review]
This looks pretty nice to me!

I am wondering if you might add a test?

**Comment by robertmin1** [comment]
@rminnich Sure, I am not sure where I should implement the tests.

**Comment by rminnich** [comment]
https://github.com/u-root/u-root/pull/2614

see what you think. Do you want to join u-root, if so I'll send an intro

**Comment by robertmin1** [comment]
Nice! I'll test the code.
Definitely, you can send the intro here: mindo.robert1@gmail.com

**Pull request closed without merging**
