### PR TITLE
cmds/core/du: fix for relative links

### PR DESCRIPTION
**Pull request by binjip978**

### CODE REVIEW

**Review by rminnich — COMMENTED** [review]
I'm not sure what you're fixing here. 

The du of a symlink should be the number of bytes in the symlink, I believe, and that's all. 

consider:
ln -s /tmp/bigfile /tmp/x
ln -s /tmp/bigfle /tmp/y
du should not show 3* the size of bigfile. Hence, for symlinks, one need only count the number of bytes in the symlink. As I read this, aren't you following the link?

**Comment by binjip978** [comment]
> I'm not sure what you're fixing here.
> 

I try to fix here relative symlinks. For example from current main: 
```
du git:(main) ./du -sL /tmp
0	/tmp
```

And with this patch:
```
du git:(fix-private-tmp) ./du -sL /tmp
28720	/tmp
```

And this happens because of relative links. `lrwxr-xr-x@ 1 root  wheel  11 Aug  4 13:31 /tmp -> private/tmp`

> The du of a symlink should be the number of bytes in the symlink, I believe, and that's all.
> 
> consider: ln -s /tmp/bigfile /tmp/x ln -s /tmp/bigfle /tmp/y du should not show 3* the size of bigfile. Hence, for symlinks, one need only count the number of bytes in the symlink. As I read this, aren't you following the link?

About size, it a bit confusing, because I have no idea how it should be done.
From POSIX:

```
-L
If a symbolic link is specified on the command line or encountered during 
the traversal of a file hierarchy, du shall count the size of the file or file hierarchy referenced by the link.

The use of the -L option, or of multiple file operands, requires that du track all file entries encountered, 
even with a link count of one. However, when -L is not used and only a single file operand is given, 
an implementation can optimize by only tracking files with a link count greater than one, since in 
that scenario, those are the only files that could be encountered more than once.
```

But it I run macOS du on /testdata folder I got this:

```
du git:(fix-private-tmp) du -L testdata
16	testdata/rel-symlinks/links
32	testdata/rel-symlinks
32	testdata

and 

du git:(fix-private-tmp) du testdata  
0	testdata/rel-symlinks/links
16	testdata/rel-symlinks
16	testdata
```

So I'm I bit confused how it should count symlinks, but this patch is more about relative symlinks.

**Comment by rminnich** [comment]
root@freebsd:/tmp # ls -lR a
lrwxr-xr-x  1 root wheel 1 Sep 28 08:28 a -> .
root@freebsd:/tmp # ls -Llr a
total 24
-rw-r--r--  1 root wheel 2396 Sep 23 02:56 list
drwxrwxrwt  6 root wheel  512 Sep 28 08:28 a
drwxrwxrwt  2 root wheel  512 Sep 21 20:20 .font-unix
drwxrwxrwt  2 root wheel  512 Sep 21 20:20 .XIM-unix
drwxrwxrwt  2 root wheel  512 Sep 21 20:20 .X11-unix
drwxrwxrwt  2 root wheel  512 Sep 21 20:20 .ICE-unix
root@freebsd:/tmp # du -a /tmp
4       /tmp/.X11-unix
4       /tmp/.XIM-unix
4       /tmp/.ICE-unix
4       /tmp/.font-unix
4       /tmp/list
0       /tmp/a
24      /tmp
root@freebsd:/tmp # du -aL /tmp
4       /tmp/.X11-unix
4       /tmp/.XIM-unix
4       /tmp/.ICE-unix
4       /tmp/.font-unix
4       /tmp/list
24      /tmp

symlinks are so much fun. I don't know the answer.

**Review by rminnich — APPROVED** [review]
I guess this is ok.

**Pull request merged**
