### PR TITLE
cmds/core/uniq: add ignore case flag

### PR DESCRIPTION
**Pull request by binjip978**
gofmt and typo fix

Signed-off-by: Siarhiej Siemianchuk <pdp.eleven11@gmail.com>

### CODE REVIEW

**Review by rminnich — APPROVED** [review]

**Review by rminnich — DISMISSED** [review]

**Comment by rminnich** [comment]
circleci is in a bad place lately

**Comment by binjip978** [comment]
seems like circleci worked this time

**Comment by rminnich** [comment]
I realized I have two questions.
1. The standard unix way to do this: tr A-Z a-z file | uniq. Is there a real need for -i
2. we'd like to make u-root conform more to posix, and this is not in posix

request: fix coverage issue.

**Comment by binjip978** [comment]
> I realized I have two questions.
> 
> 1. The standard unix way to do this: tr A-Z a-z file | uniq. Is there a real need for -i
> 2. we'd like to make u-root conform more to posix, and this is not in posix

Yea I agree there are now need to -i flag and it's definitely not part of posix https://pubs.opengroup.org/onlinepubs/9699919799/utilities/uniq.html, but it was requested explicitly in roadmap.md so I decided to add it, also -i is a part of freebsd, linux and macOS uniq so maybe some people need it.

But I agree it's better idea to remove it, but not 100% sure, due the roadmap request.

**Comment by binjip978** [comment]
@rminnich probably I messed up with force push, but it reports other files in coverage diff, but it should be improved

**Comment by rminnich** [comment]
I really appreciate you paying attention to the roadmap! Thank you!

I guess if this is felt to be important, we can accept it?

**Comment by binjip978** [comment]
I'm ok to accept it, if it was required in roadmap, maybe it save some typing time for someone :)

**Review by rminnich — APPROVED** [review]

**Comment by rminnich** [comment]
In this case, because we know that some script or makefile will break if we do not support it, I guess we can accept -i!

Thanks for your careful reading of the roadmap and your contribution.

**Pull request merged**
