### PR TITLE
Fixed linter warnings

### PR DESCRIPTION
**Pull request by insomniacslk**
I just ran `gofmt -w *.go` under `pkg/gzip` to solve the CI failures at http://github.com/u-root/u-root/pull/740

### CODE REVIEW

**Comment by insomniacslk** [comment]
If I run this with go 1.9 everything is fine. If I use go 1.10 it breaks

**Comment by insomniacslk** [comment]
this is actually failing also with go1.9

**Comment by hugelgupf** [comment]
this is strange stuff. let me pull it.

**Comment by insomniacslk** [comment]
did some more investigation. go 1.10 wants comments aligned with where the code would be (i.e. indented after the open brackets) while go 1.9 wants them differently, one indentation level less.

```
$ gvm use 1.9
Now using version go1.9


$ gofmt -s -l cmds pkg u-root.go
pkg/gzip/file_test.go
pkg/gzip/options_test.go


$ diff -Naur pkg/gzip/file_test.go <(gofmt pkg/gzip/file_test.go)
--- pkg/gzip/file_test.go	2018-03-06 22:53:55.218155963 +0000
+++ /dev/fd/63	2018-05-09 11:48:13.241753084 +0100
@@ -59,7 +59,7 @@
 		fields  fields
 		wantErr bool
 	}{
-		// TODO: Add test cases.
+	// TODO: Add test cases.
 	}
 	for _, tt := range tests {
 		t.Run(tt.name, func(t *testing.T) {
@@ -84,7 +84,7 @@
 		fields  fields
 		wantErr bool
 	}{
-		// TODO: Add test cases.
+	// TODO: Add test cases.
 	}
 	for _, tt := range tests {
 		t.Run(tt.name, func(t *testing.T) {
@@ -169,7 +169,7 @@
 		fields  fields
 		wantErr bool
 	}{
-		// TODO: Add test cases.
+	// TODO: Add test cases.
 	}
 	for _, tt := range tests {
 		t.Run(tt.name, func(t *testing.T) {
@@ -194,7 +194,7 @@
 		fields  fields
 		wantErr bool
 	}{
-		// TODO: Add test cases.
+	// TODO: Add test cases.
 	}
 	for _, tt := range tests {
 		t.Run(tt.name, func(t *testing.T) {
```

the same doesn't happen with go 1.10

```
$ gvm use 1.10
Now using version go1.10


$ gofmt -s -l cmds pkg u-root.go
$
```

**Comment by insomniacslk** [comment]
proposed fix: I am moving the comments up for now, so both versions of gofmt will be happy, but I would remove gofmt from being a push blocker

**Comment by insomniacslk** [comment]
@BigValen is going to do this change in https://github.com/u-root/u-root/pull/740

**Comment by insomniacslk** [comment]
abandoning in favour of the other PR

**Pull request closed without merging**
