### PR TITLE
grub: unconditionally unquote any GRUB config

### PR DESCRIPTION
**Pull request by pmazzini**
The code was wrongly detecting `/mnt/sda2/grub2/grub.cfg` as v1.

* remove grub version detecting
* unconditionally unquote any GRUB config

### CODE REVIEW

**Comment by insomniacslk** [comment]
I remember that grub v1 doesn't have quoting so backslashes and other quoting types are interpreted literally (despite the user intention). Maybe it's worth improving the version detection instead?

**Comment by pmazzini** [comment]
> I remember that grub v1 doesn't have quoting so backslashes and other quoting types are interpreted literally (despite the user intention). Maybe it's worth improving the version detection instead?

Right, I double checked this and v1 doesn't have the quoting. I need to find a more reliable way of detecting the grub version then.

**Comment by pmazzini** [comment]
Does it actually support grub v1 configs? Doesn't it only parse `menuentry`s?

**Comment by pmazzini** [comment]
Closing in favour of #1345/

**Pull request closed without merging**
