### PR TITLE
ueficat: cat EFI_SECTION_RAW from a set of file GUIDS

### PR DESCRIPTION
**Pull request by rminnich**
usage
ueficat re [..re]

cats the EFI_SECTION_RAW from files it finds whose GUID
matches one or more of the res

We don't check the REs to see if they are valid GUIDS since,
e.g., . is a valid RE but not a valid GUID.

Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>

### CODE REVIEW

**Comment by rminnich** [comment]
I give up. This was a clean checkout, add one thing, dep ensure.

damn I hate dep.

**Comment by rminnich** [comment]
rminnich@uroot:~/go/src/github.com/u-root/u-root$ dep ensure -vendor-only
rminnich@uroot:~/go/src/github.com/u-root/u-root$ git status
On branch ueficat
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

what a piece of shit.

**Comment by rjoleary** [comment]
The problem is the CI is using a really old version of dep (Jan 2018 which is considered old). Newer versions of dep behave differently. It's a huge mess unless everyone uses the exact same version of dep. We spent an hour debugging the same issue in fiano last week. I'll make a quick PR to u-root to bump the version.

**Comment by rjoleary** [comment]
You're going to hate this: #922

It's strongly recommended to use the latest release of dep (v0.5.0). If you use `go get -u github.com/golang/dep/cmd/dep`, you get the master branch which may contain new features which breaks other developers working on u-root. For best results, everyone should use the same version of dep (and hopefully we'll move to vgo before the next release of dep in January). The part you'll hate is the `go get` tool didn't support checking out a specific branch (until vgo), so they provide an `install.sh` script to run which gets the latest version:

    ( cd ${GOPATH-$HOME/go}/src/github.com/golang/dep && git fetch && git checkout v0.5.0 && ./install.sh ) && dep version

**Comment by hugelgupf** [comment]
Should this be a part of fiano?

**Comment by rminnich** [comment]
yeah, good question, I'm fine if we want it there too.

**Comment by rjoleary** [comment]
Yes, making it part of fiano is a great idea. Also, I just remembered fiano vendors u-root as well. I don't quite understand how this circular dependencies works, but let's avoid doing it.

**Comment by rjoleary** [comment]
https://github.com/linuxboot/fiano/pull/137

**Pull request closed without merging**
