### PR TITLE
Move gosh to cmds/core

### PR DESCRIPTION
**Pull request by jensdrenhaus**
With recent work in #2554 #2555 and #2569 gosh isn't experimental anymore.
Consideration if it should be the default shell, here: #2591

### CODE REVIEW

**Comment by MDr164** [comment]
CI fails currently because our used shell parser doesn't seem to support Plan9 yet. Every other target OS should work fine, as we got general Unix and Windows support. Either blacklist the package using build constraints for Plan9 or add Plan9 support to the shell parser library.

**Review by rminnich — CHANGES_REQUESTED** [review]
I need to remind you -- you aren't following the rules for submitting PRs, listed here:
https://github.com/u-root/u-root/blob/main/CONTRIBUTING.md
"Fork the project on GitHub, work in your fork and in branches, push these to your GitHub fork, and when ready, do a GitHub pull requests against https://github.com/u-root/u-root."

Can you please redo this PR, following the rules? Thanks.

**Comment by rminnich** [comment]
u-root has no plan 9 users at this point, so it may be time to remove all plan 9 support and artifacts. 

Rather than scattering plan 9 build constraints everywhere, I'd be fine with removing plan 9 entirely; it's not clear it will be supported by Go for much longer anyway.

**Comment by jensdrenhaus** [comment]
> I need to remind you -- you aren't following the rules for submitting PRs, listed here: https://github.com/u-root/u-root/blob/main/CONTRIBUTING.md "Fork the project on GitHub, work in your fork and in branches, push these to your GitHub fork, and when ready, do a GitHub pull requests against https://github.com/u-root/u-root."
> 
> Can you please redo this PR, following the rules? Thanks.

Sure. #2598

**Pull request closed without merging**
