### PR TITLE
Remove redundant implementation of rsdp in pkg/boot/acpi

### PR DESCRIPTION
**Pull request by ChriMarMe**
Signed-off-by: Christopher Meis <christopher.meis@9elements.com>

### CODE REVIEW

**Comment by ChriMarMe** [comment]
CircleCi doesn't kick off

**Comment by rjoleary** [comment]
This is a weird bug in CircleCi. The CI is not being run in the u-root organization (https://app.circleci.com/pipelines/github/u-root/u-root) and is instead being run in the 9elements organization (https://app.circleci.com/pipelines/github/9elements/u-root).

Since it is being run under the wrong CircleCI organization, the results are not finding their way back to the pull request.

The only way I know to fix this is to delete the CircleCI organization for 9elements (https://app.circleci.com/pipelines/github/9elements/u-root) or to create a new Github repository to send the PR from. Once that is done, push an empty commit to the PR to re-trigger it.

**Comment by orangecms** [comment]
> This is a weird bug in CircleCi. The CI is not being run in the u-root organization (https://app.circleci.com/pipelines/github/u-root/u-root) and is instead being run in the 9elements organization (https://app.circleci.com/pipelines/github/9elements/u-root).
> 
> Since it is being run under the wrong CircleCI organization, the results are not finding their way back to the pull request.
> 
> The only way I know to fix this is to delete the CircleCI organization for 9elements (https://app.circleci.com/pipelines/github/9elements/u-root) or to create a new Github repository to send the PR from. Once that is done, push an empty commit to the PR to re-trigger it.

Ah... can it be that 9elements has something set so that all their repos automatically get Circle CI integrated? I have some vague memory that there is such an org-wide setting. It might be that it can't be changed. I'd also suggests using another fork, maybe just from personal accounts.

**Comment by rjoleary** [comment]
> > This is a weird bug in CircleCi. The CI is not being run in the u-root organization (https://app.circleci.com/pipelines/github/u-root/u-root) and is instead being run in the 9elements organization (https://app.circleci.com/pipelines/github/9elements/u-root).
> > Since it is being run under the wrong CircleCI organization, the results are not finding their way back to the pull request.
> > The only way I know to fix this is to delete the CircleCI organization for 9elements (https://app.circleci.com/pipelines/github/9elements/u-root) or to create a new Github repository to send the PR from. Once that is done, push an empty commit to the PR to re-trigger it.
> 
> Ah... can it be that 9elements has something set so that all their repos automatically get Circle CI integrated? I have some vague memory that there is such an org-wide setting. It might be that it can't be changed. I'd also suggest using another fork, maybe just from personal accounts.

Yes, trying again from another fork should work. This has happened a few times before with different folks. I'm not sure exactly what triggers it. Somehow the 9elements/u-root CircleCI is taking priority over the u-root/u-root CirclecCI.

**Comment by tlaurion** [comment]
CircleCI has a setting to build all forks of a project from the organization I guess this is what is happening here.

Otherwise, CircleCI changed their policies recently and it is not possible to build any step that takes more then 2 hours. Looking for answers myself for open source projects like Heads here on how to go from here. If this is related don't hesitate to tag me for follow ups.

**Comment by ChriMarMe** [comment]
So. The simple fix is to push our branch directly to u-root repo instead of opening the PR from our repo to u-root.

This at least avoids the problem for now.

**Pull request closed without merging**
