### PR TITLE
pkg/boot/linux.go: Decompress kernel before doing kexec

### PR DESCRIPTION
**Pull request by CodingVoid**
It is possible/likely that the kernel is compressed. In order for kexec to actually find the magic value for aarch64 Linux kernels it needs to be decompressed before refering it to the kexec syscall.

Test: aarch64 Fedora 36 Server image can now be started via localboot.

### CODE REVIEW

**Comment by hugelgupf** [comment]
A kernel should decompress itself on kexec, shouldn't it? What kind of compression is on this thing? (Is that a feature not available on aarch64?)

u-root's kexec is in use in memory-constrained environments sometimes, so we'd likely prefer if this was either behind a flag or could be avoided altogether due to its use of memory.

**Comment by CodingVoid** [comment]
On aarch64 kexec does not decompress the kernel (that may not be true for the new zimage in Linux though). As far as I know that is only happening on x86 (bzImage). That is actually what the kexec u-root command already does (so if I do "kexec ..." in u-root it works but not with the localboot cmd). No Idea why there are different code paths for kexec and kexec localboot cmd in the first place, but I guess that is something for another patch.
kexec u-root cmd decompression:
https://github.com/u-root/u-root/blob/585ee8365e4c2d7724031d0788ba2e0a38044774/pkg/boot/linux.go#L284
I used a aarch64 fedora server image for testing.

**Comment by hugelgupf** [comment]
> On aarch64 kexec does not decompress the kernel (that may not be true for the new zimage in Linux though). As far as I know that is only happening on x86 (bzImage). That is actually what the kexec u-root command already does (so if I do "kexec ..." in u-root it works but not with the localboot cmd). No Idea why there are different code paths for kexec and kexec localboot cmd in the first place, but I guess that is something for another patch. kexec u-root cmd decompression:
> 
> https://github.com/u-root/u-root/blob/585ee8365e4c2d7724031d0788ba2e0a38044774/pkg/boot/linux.go#L284
> 
> 
> I used a aarch64 fedora server image for testing.

Oh this is for jsonboot. I didn't even notice that. It probably ultimately shouldn't be a different codepath, but jsonboot doesn't yet.

**Comment by hugelgupf** [comment]
Ultimately, IMO any remaining `localboot` functionality should merge into the `boot` command (which uses the code path kexec uses), and `localboot` should be deleted.

**Review by hugelgupf — DISMISSED** [review]

**Review by rminnich — APPROVED** [review]

**Pull request merged**
