### PR TITLE
Switch to upstream elvish

### PR DESCRIPTION
**Pull request by rjoleary**
This change does the following:

* Move u-root's fork of elvish to exp/felvish
* Import the new elvish as core/elvish
* Update vendor directory with new dependencies

Size difference:

```
With go version 1.13:
16571556 new_elvish.cpio
 4398452 new_elvish.cpio.xz
15309988 old_elvish.cpio
 4052772 old_elvish.cpio.xz

With go version 1.16:
13679780 new_elvish.cpio
 3519348 new_elvish.cpio.xz
11701412 old_elvish.cpio
 3059740 old_elvish.cpio.xz
```

Signed-off-by: Ryan O'Leary <ryanoleary@google.com>

### CODE REVIEW

**Comment by rjoleary** [comment]
For #1645

**Comment by rminnich** [comment]
did you look at any of the security issues in elvish? Does it still keep a socket open over which commands are issued, for example?

**Comment by rminnich** [comment]
I don't see a reason for felvish. 
If the upstream works, use it. If it ends up being too big, then why would we use it? Let's make this a simple decision maybe?

**Comment by rminnich** [comment]
also is there some way to NOT include elvish in our tree at all? Modules would seem to make this pretty easy.

**Comment by rjoleary** [comment]
> also is there some way to NOT include elvish in our tree at all? Modules would seem to make this pretty easy.

You can't depend on a binary in Go modules (as far as I know). We'd have to tell users in the README to download elvish separately. The work-around here is to include ~3 lines of elvish in cmds/core/elvish and the rest is in the vendor directory.

**Comment by rjoleary** [comment]
> I don't see a reason for felvish.
> If the upstream works, use it. If it ends up being too big, then why would we use it? Let's make this a simple decision maybe?

It's a trade-off between keeping up to date with the latest elvish and size. The trade-off depends on the individual users.

**Comment by hugelgupf** [comment]
You can actually depend on commands in Go modules. Kinda. gobusybox doesn't
have anything nice to handle this yet, but stay tuned.

**Comment by rjoleary** [comment]
> did you look at any of the security issues in elvish? Does it still keep a socket open over which commands are issued, for example?

This is blocked on completely removing the connection to the daemon at build time.

**Comment by krader1961** [comment]
FWIW, I have an experimental Elvish branch that provides for building an `elvish` binary that has no support for a daemon process (which exists to support shared interactive history) and does not result in any unexpected user visible error messages. It currently depends on changing a handful of `import` statements in the source code which is not acceptable. I was hoping a *go.mod* `replace` directive would make those edits unnecessary but my initial attempt did not work. TBD is how to make using an alternative implementation of the daemon possible with the least amount of effort, pain, and risk. My experimental branch changes the  `elvish` binary size from 7.9m to 6.9m on macOS.

**Comment by rminnich** [comment]
what do you want to do here? We could probably just gvc and fix this pretty quick.

**Comment by rminnich** [comment]
btw, the other part of standard elvish that's not really acceptable:
pkg/rpc/server.go
if memory serves, it used to open a socket and accept commands to be executed on that socket. 

You're not going to be able to pull in elvish as is, you are going to need to fork it to remove these problems. But a more full-featured elvish would be nice, unless we can find something better.

**Comment by krader1961** [comment]
@rminnich, The change I'm working on to the Elvish project will eliminate the RPC code as a byproduct of replacing the daemon package with a stub that acts as if there is no global, shared, interactive history. That means it won't create a socket or spawn the daemon process. Since I don't use u-root I can't speak to the merits of renaming the current, very old and non-standard, version of elvish to `felvish` but I don't think it is justified. My recommendation is to close this P.R. and open a new one when there is a mechanism, supported by the Elvish project, to build the elvish binary with no daemon support. I expect that to happen soon; e.g., in a few weeks to a couple of months from now.

Part of the problem is that at the moment I am hand editing all imports of the `src.elv.sh/pkg/daemon` package to use the stub package. I'm hoping to avoid that by using a *go.mod* `replace` directory but that isn't working for some reason. So I'm still working on figuring out the best way to build elvish with no daemon support.

Note: My change reduces the size of the elvish binary from 7.9M to 6.7M (-15%) on macOS. Although it should be possible to further reduce that size by refactoring the code to avoid the need to import the Bbolt database code when the daemon is disabled.

**Comment by krader1961** [comment]
If https://github.com/elves/elvish/pull/1337 is merged as is you'll be able to build an elvish binary with no daemon (and thus no RPC code or creation of a socket) by running `make get ELVISH_MAKE_BIN=./elvish ELVISH_MAKE_TAGS=elv_daemon_stub`. This reduces the size of the binary 15% on macOS.

TODO:  eliminating the unused bbolt DB code.

**Comment by rjoleary** [comment]
Thank you @krader1961 . I will restart this in another pull request!

**Comment by krader1961** [comment]
@rjoleary, Just an FYI that my experimental change was rejected in favor of a more comprehensive refactoring of the code that also allowed eliminating the inclusion of the Bbolt DB code. See the [packaging directions](https://github.com/elves/elvish/blob/master/PACKAGING.md) and replace *./cmd/elvish* with *./cmd/nodaemon*.

**Pull request closed without merging**
