### PR TITLE
ps: fix bug when /proc is not mounted

### PR DESCRIPTION
**Pull request by rminnich**
I debated just having it print nothing but that's kinda
counterintuitive.

Testing this would add another test that requires we run as root.
Maybe we should anyway.

Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>

### CODE REVIEW

**Comment by rminnich** [comment]
It's kind of a tough call as to whether LoadTable should fail if /proc is empty, but was concerned about calling that an error. Maybe some day /proc might be empty, although how that can happen I have no idea. I'm open to suggestions here.

**Comment by rminnich** [comment]
to test: 
sudo unshare -m /bin/bash
mount -t tmps none /proc
./ps
gets a segv when the list is empty. Nasty.

**Comment by ryukinix** [comment]
>  to test:sudo unshare -m /bin/bashmount -t tmps none /proc./psgets a segv when the list is empty. Nasty.



event with this fix?

**Comment by rjoleary** [comment]
@ryukinix I just gave it a test. Before this PR it printed "panic: runtime error: index out of range" when proc is empty. This change adds a better error message and exits more gracefully.

**Comment by ryukinix** [comment]
> This change adds a better error message and exits more gracefully.
+1 for merging that, thanks for the fix @rminnich

**Comment by rminnich** [comment]
I changed it, I hated the way I'd done it. It still fixes the bug.

**Pull request merged**
