### PR TITLE
cmds/core/wget: handle "-" as stdout

### PR DESCRIPTION
**Pull request by binjip978**

### CODE REVIEW

**Comment by binjip978** [comment]
somewhat fixes #2961 don't work with redirects on macOS, but ok in Linux

**Review by RoboSchmied — APPROVED** [review]
looks good

**Review by rminnich — COMMENTED** [review]
So, if we *must* do this, I am sad, because /dev/stdout exists for a reason. 
It means every command that writes to stdout has to do this special test for -.
That's now how it's supposed to work.

it's very non-unix-like. do we HAVE to do this?

**Comment by binjip978** [comment]
> So, if we _must_ do this, I am sad, because /dev/stdout exists for a reason. It means every command that writes to stdout has to do this special test for -. That's now how it's supposed to work.
> 
> it's very non-unix-like. do we HAVE to do this?

I was always thinking that special handling of "-" is somewhat a bonus, we still can use wget in this way with more characters:
```
./wget -O=/dev/stdout https://raw.githubusercontent.com/u-root/u-root/main/cmds/core/base64/base64.go
```

In cat we already doing such thing if memory serves, but anyway we can close this PR and corresponding issue with "no fix" ;)

**Review by rminnich — APPROVED** [review]

**Pull request merged**
