### PR TITLE
integration: Fix flaky multiboot integration test

### PR DESCRIPTION
**Pull request by rjoleary**
This fixes a race-condition when reading from serial.

Signed-off-by: Ryan O'Leary <ryanoleary@google.com>

### CODE REVIEW

**Comment by rjoleary** [comment]
Fixes #1209

**Comment by n-canter** [comment]
Looks fine, please update the comment for wc struct in integration/wc.go, because it doesn't say anything about race-condition.
And we should also update other tests, like dhcclient, tcz (maybe in a separate pull request).

**Comment by rjoleary** [comment]
That's a good point. Perhaps this is also related to #1071. If all the tests use wc, one other solution is to add a mutex to wc.

**Comment by rjoleary** [comment]
Actually, @rminnich and @hugelgupf, is there a reason the dhcclient and tcz tests need to log their serial output?

By default, the integration test will write the serial output to the serial directory. Locally, you can find this directory in u-root/integration/serial. Also, in the circleci UI, the artifacts tab appears which contains this directory.

Perhaps the serial directory needs to be better documented? Like when a test runs, it says where the serial is being written to.

**Comment by hugelgupf** [comment]
+1 to better docs. I think before the serial directory was there, the output was logged ..... somewhere and I clicked around circleci and couldn't find it, hence dumping it in the log. (Also don't know where it goes when run locally.)

**Comment by rminnich** [comment]
the reason was the bugs were obscure and hard to find. Feel free to take it out, but I can tell you debugging this was painful.

**Comment by rminnich** [comment]
the tcz test, in particular, had issues in circle-ci that I could never repro in local testing.

**Comment by rminnich** [comment]
closed per discussion with Ryan

**Pull request closed without merging**
