### PR TITLE
add plan9 style cpu command

### PR DESCRIPTION
**Pull request by rminnich**
CPU is an ssh client that starts up a shell on a remote machine,
as usual; but, further, makes a namespace of the local machine
available in a private mount rooted at /tmp/cpu on the remote.

On the remote machine, you can access your local files with
cp, moving things back and forth, running binaries, and
so on.

Whereever you go, there your files are.

Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>

### CODE REVIEW

**Comment by rjoleary** [comment]
The flaky tcz test is a known issue, ignore it.

**Comment by rminnich** [comment]
What's the tcz issue? We'll need to resolve it if we want a test for cpu.

**Comment by rjoleary** [comment]
I made some suggestions in this commit: https://github.com/rjoleary/u-root/commit/131406233c148a6de2e0e3c2e7107fc76ee38899

**Comment by rminnich** [comment]
OK I think I got all the review comments fixed.

**Comment by rjoleary** [comment]
We'll need to add support for encrypted keys at some point.

**Pull request merged**
