### PR TITLE
dmesg: use sys/unix/ Add golang.org/x/sys/unix to glide.yaml

### PR DESCRIPTION
**Pull request by mathgamain**
Signed-off-by: Mateus Pinto Rodrigues <mathgamain@openaliasbox.org>

### CODE REVIEW

**Comment by rminnich** [comment]
LGTM

**Comment by rminnich** [comment]
sorry, you have to rebase and I can't do it ...

**Comment by rafaelcn** [comment]
We'll have to change the syscalls on unshare.go as well. Gonna look into it, we have to merge this asap.

**Comment by mathgamain** [comment]
I replied via email and I thought the answer would appear here, but seems it doesnt. Well, how can I rebase from command line? Do I need any special parameters?

**Comment by rafaelcn** [comment]
Just do a git pull origin master --rebase. As long as the origin points to the u-root/u-root repository.

--
Regards,
Rafael Campos Nunes.
rafaelnunes737@hotmail.com

**Comment by mathgamain** [comment]
ok, next thing is, how do I use the same PR now?

**Comment by rafaelcn** [comment]
You don't need to, whenever you rebase your branch you just have to push the updates to the branch in question and the PR will automatically index the last commit of that branch.

--
Regards,
Rafael Campos Nunes.
rafaelnunes737@hotmail.com

**Comment by ryukinix** [comment]
If  `git pull --rebase origin master && git push -f mathgamain dmesg` doesn't works, you can try that complete procedure step by step to avoid ambiguity:
```
git checkout master # enter in the master
git pull origin master # pull the branch
git checkout dmesg # enter in 
git rebase master
git push mathgamain dmesg 
```

**Comment by mathgamain** [comment]
On Wed, 16 Mar 2016 10:26:40 -0700
ron minnich <notifications@github.com> wrote:

> sorry, you have to rebase and I can't do it ...
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/u-root/u-root/pull/38#issuecomment-197442975

How can I rebase from command line, do I need any special parameters?

-- 
Best Regards.

Mateus Pinto Rodrigues (mprodrigues) [66679238]
free software enthusiast and developer
E462 69C4 73EF 91F9 25E2  8249 0F8B 6C54 6667 9238

**Comment by ryukinix** [comment]
@mathgamain, look to my answer.

**Pull request merged**
