### PR TITLE
Revert "neuter cirrus"

### PR DESCRIPTION
**Pull request by hugelgupf**
Reverts u-root/u-root#1666

I'd rather we mark it "optional" in u-root settings than kill it like this. It'll let it report status, but not sit there blocking PRs.

### CODE REVIEW

**Comment by rminnich** [comment]
we're going to have to fix it.

I just want to leave it off while we get some stuff through. It looks like a transient error at their end anyway; bet it's fixed in a little while.

**Comment by hugelgupf** [comment]
We are still leaving it off by marking it not required. This way, it can still run though.

**Comment by hugelgupf** [comment]
cc @orangecms why is Cirrus installing packages anyway? We should pin the versions of everything we use to test stuff. Always updating to the newest thing or always using the newest thing seems to be giving us some trouble.

**Comment by orangecms** [comment]
The FreeBSD base system does not include go, git and dep. They are our build requirements. I'll check what's wrong there, doesn't make sense. An option would be to find a way to get an image including go, git and dep, similar to https://github.com/u-root/u-root/tree/master/.circleci/images.

I agree that it shouldn't be blocking us.

**Comment by orangecms** [comment]
It might be related to using the 13.0 snapshot: https://github.com/u-root/u-root/blob/revert-1666-fixcirrus/.cirrus.yml#L2

I'll see if using a stable release works better.

I don't have `gcloud` at hand. Could one of you check for images as per https://cirrus-ci.org/guide/FreeBSD/#list-of-available-image-families ? There might be one for Go.

**Comment by orangecms** [comment]
Using the 12.1 stable image works fine. I suggest to use stable only; FreeBSD releng do not guarantee much on development snapshots. See also [the remark](https://www.freebsd.org/where.html):

> f you are interested in a purely experimental snapshot release of FreeBSD-CURRENT (AKA 13.0-CURRENT), aimed at developers and bleeding-edge testers only, then please see the FreeBSD Snapshot Releases page. For more information about past, present and future releases in general, please visit the release information page.

We should be good using stable over -snap images. :)

**Comment by hugelgupf** [comment]
well, the build is still failing. i'm gonna merge it. cirrus remains not required to merge.

**Comment by orangecms** [comment]
There is a checkmark now, actually; the build has passed. Am I missing something?

**Comment by hugelgupf** [comment]
It didn't pass the first time; I had to restart it.

**Comment by patmaddox** [comment]
FYI you want to use RELEASE FreeBSD versions.

RELEASE = official major release
STABLE = snapshot of development branch of next point release
CURRENT = snapshot of development branch of next major release

**Pull request merged**
