### PR TITLE
menu: allow passing in loadOptions

### PR DESCRIPTION
**Pull request by 10000TB**

### CODE REVIEW

**Comment by hugelgupf** [comment]
This is not the way to do that. You can see an internal CL where I've done
something like this.

The specific entry struct should have that as an argument, not
menu.Entry.Load().

**Comment by 10000TB** [comment]
IIUC, w/o this there is no way to propagate down the load options

**Comment by hugelgupf** [comment]
Argh, my apologies, I misread the PR. This is all good.

**Comment by 10000TB** [comment]
Thank Chris -- ( Approve ?

**Review by hugelgupf — APPROVED** [review]

**Pull request merged**
