### PR TITLE
cmds/ip: fix output for addr subcommand

### PR DESCRIPTION
**Pull request by insomniacslk**
Fixes https://github.com/u-root/u-root/issues/931

```
$ ./ip a
1: lo: <UP,LOOPBACK> mtu 65536 state UNKNOWN
    link/loopback 
    inet 127.0.0.1 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1 scope host 
       valid_lft forever preferred_lft forever
2: wlp2s0: <UP,BROADCAST,MULTICAST> mtu 1500 state UP
    link/ether 00:fa:ce:b0:0c:00
    inet 172.16.x.y brd 172.16.3.255 scope global wlp2s0
       valid_lft 6545sec preferred_lft 6545sec
    inet6 2620:[snip] scope global 
       valid_lft 603248sec preferred_lft 84510sec

```

### CODE REVIEW

**Comment by insomniacslk** [comment]
meh, dep -.-

The CircleCI test fails on:
```
#!/bin/bash -eo pipefail
./dep version
./dep status
./dep ensure -vendor-only
git status
if [[ -n "$(git status --porcelain vendor)" ]]; then
  echo 'vendor/ is out-of-date: run `dep ensure -vendor-only` and then check in the changes'
  echo 'If `dep ensure` results in no changes, make sure you are using the latest relase of dep'
  git status --porcelain vendor
  exit 1
fi
```

However, with a freshly updated `dep`, I get no local changes when running `dep ensure` or `dep ensure -vendor-only`. Anyone has a clue?

**Comment by insomniacslk** [comment]
After a quick online search, the error on CircleCI seems a transient networking issue, but I don't have permissions to restart the build

```
unable to deduce repository and source type for "golang.org/x/sys": unable to read metadata: go-import metadata not found
```

**Comment by rjoleary** [comment]
Make sure your using dep v0.5.0 (not the latest). I don't have permission to rerun the workflow either it seems. One quick work around is to push an empty commit. Empty commits get deleted during the rebase.

**Comment by insomniacslk** [comment]
Thanks @rjoleary - v0.5.0 didn't help, so I pushed an empty commit as you suggested. Let's see :)

**Comment by insomniacslk** [comment]
that did the trick, thanks!

**Pull request merged**
