### PR TITLE
xcmds: create xcmds directory, mv ash to it

### PR DESCRIPTION
**Pull request by rminnich**
we have lots of "in progress" commands and packages and it's time
to break things out.

xcmds is where we put experimental stuff there is no clear need for.

I want to go with xcmds/ instead of cmds/x/ because the latter
is going to break every glob everyone is using. xcmds nicely
separates things out in a way that is easy to glob.

Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>

### CODE REVIEW

**Comment by rminnich** [comment]
if this is acceptable I'll need to add xcmds to the various tests, but I want to see if the naming is ok first

**Comment by bensallen** [comment]
Sounds good to me.

**Comment by rminnich** [comment]
Why didn't ryan's approval make it pushable. It had to wait for ben. Weird.

**Comment by rminnich** [comment]
OK, it's now added to tests.

**Comment by bensallen** [comment]
Also noticed:

```go test -a -ldflags '-s' ./pkg/... ./*cmds/...
warning: "./*cmds/..." matched no packages```

**Pull request closed without merging**
