### PR TITLE
kexec: change flag type for modules

### PR DESCRIPTION
**Pull request by krystian-hebel**
StringSliceVar splits string on commas, even when they are surrounded
by quotation marks or escaped. Comma is sometimes used in kernel command
line (e.g. in nfsroot). StringArrayVar does not split on commas, so
it is better suited for this.

Signed-off-by: Krystian Hebel <krystian.hebel@3mdeb.com>

### CODE REVIEW

**Comment by hugelgupf** [comment]
Integration test for Multiboot seems to be failing - can you check that out? (Easiest is to pull down the docker container we use and use that env)

**Comment by hugelgupf** [comment]
I was debugging this, but I got side-tracked by the test setup

https://twitter.com/hugelgupf/status/1173844114732806146

https://twitter.com/hugelgupf/status/1173815173766733824

if you have ideas...

**Comment by rjoleary** [comment]
> I was debugging this, but I got side-tracked by the test setup
> 
> https://twitter.com/hugelgupf/status/1173844114732806146
> 
> https://twitter.com/hugelgupf/status/1173815173766733824
> 
> if you have ideas...

I was thinking you could have a standalone Go program which downloads the docker image from DockerHub and extract its contents (qemu, linux, ...) to a directory like "integration/dependencies/amd64". I think it would be possible to run this program without a docker server (or even installing docker) if you link directly against the internal APIs of docker https://github.com/moby/moby/tree/master/image . The integration test could then use the qemu from the "integration/dependencies/amd64" directory rather than looking at the environment variables.

**Comment by rjoleary** [comment]
I restarted the tests. Sometimes it can just be flaky.

**Comment by hugelgupf** [comment]
I'd already restarted them a few times. This one's not a flake. I'm still on it though.

**Comment by hugelgupf** [comment]
I'm gonna be honest with you... I think I just figured it out, and I have no idea why this wasn't already a problem. I'll open another PR.

**Comment by hugelgupf** [comment]
I couldn't push to your remote branch, so I opened https://github.com/u-root/u-root/pull/1364

**Pull request closed without merging**
