### PR TITLE
docs: update u-root.org website

### PR DESCRIPTION
**Pull request by MDr164**
Updates the current website and adds a github action for automatic branch deployments into the gh-pages branch.

### CODE REVIEW

**Comment by jensdrenhaus** [comment]
Nice :+1: 
Let's give it a try.

**Review by jensdrenhaus — APPROVED** [review]

**Comment by tecosaur** [comment]
It's probably worth pointing out the rather, let's say striking, similarity between the three dots logo that seems to have been introduced here and the logo/graphics of https://julialang.org/ :slightly_smiling_face:

**Comment by MDr164** [comment]
Oh right, I didn't even know. The reason we went with those is because those are the original gopher colors the old u-root logo had so we wanted to keep the colors. I'll discuss this internally as well how we should proceed on that overlap of logos.

**Comment by MDr164** [comment]
We will either update the color ordering or simply replace this one occurrence in the headline with one of the Gophers that previously made up the old logo. Given that the colors aren't the exact colors anyway we'll very likely keep the color scheme but make sure not to copy someone elses logo by accident.

**Comment by tecosaur** [comment]
That sounds like a solid resolution :slightly_smiling_face: (though given the rotational symmetry of the logo, I'd be unsure that just changing the colour order would be enough -- very funny that you folks ended up on the same arrangement though :smile:).

**Comment by MDr164** [comment]
We changed this part now to be boxes (as in busybox) but we definitely wanted to keep the colors as those were the original logo colors. :)

**Pull request merged**
