### PR TITLE
Use the forked u-root dhcp6

### PR DESCRIPTION
**Pull request by rminnich**
This lets us remove our dhcp6client package.

We need to test it a bit more, but I think it's ok.
I forked it to u-root as the dhcp6 owner never responded
to my requests to add our client.

Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>

### CODE REVIEW

**Comment by hugelgupf** [comment]
I don't see the client in the master branch yet?

**Comment by rminnich** [comment]
The u-root fork of dhcp6 has it in the addclient branch. I have a PR in to the dhcp6 owner but never heard back.

**Comment by rminnich** [comment]
https://github.com/mdlayher/dhcp6/pull/21

**Comment by hugelgupf** [comment]
Hmm. I guess we should do one of two things to actually be able to use it:
 * Merge addclient into master in our fork, so that's what gets vendored in (that's how it works, right? the master branch is used?)
 * Just create a u-root/dhcp6client repository.

I would tentatively advocate for the dhcp6client version, but it's up to you.

**Comment by GanShun** [comment]
I believe so? I'm leaning towards moving it to master just so we don't have to change our tools or worry about a separate repo when using bb to build a ramfs.

**Comment by rminnich** [comment]
I don't see that big an issue with vendoring the correct ref from u-root/dhcp -- govendor always goes by refs anyway. I don't want to continue our oddball dhcp6client variant.

**Comment by rminnich** [comment]
aaannnndddd that worked.

go get github.com/u-root/dhcp6
change there, checkout the right thing
govendor automagically uses that ref, and it's all good

wow that's nice.

**Comment by bkochendorfer** [comment]
I think you can also remove the vendored version of [dhcp6](https://github.com/u-root/u-root/tree/master/vendor/github.com/mdlayher/dhcp6) as you are adding the u-root version here.

**Comment by rminnich** [comment]
The vendored versiom *is* the u-root version :-)

**Comment by rminnich** [comment]
but since it's not in this repo, but in another one, vendoring is still a good idea.

**Comment by rminnich** [comment]
oh sorry I misunderstood you. Yes, that can come out and will soon.

**Comment by rminnich** [comment]
as in 'now' :-)

**Comment by rminnich** [comment]
Hey brett, I like your idea, I worry that tracking the branch will cause trouble if we update it. Could versionExact be the ref maybe?

I'm going to rebase and merge this for now and then try your nice idea. I just want to make sure we can do a bisect back to this version if we hit some weird issue. This is probably just my lack of knowledge showing.

Thanks for your careful review!

**Comment by bkochendorfer** [comment]
@rminnich Indeed it tracks the revision (ref/sha) at the branch or tag. In that diff I posted it still maintains the revision just adds a version (which really means tag or branch) pointer. I don't think git really cares about that but it might make it easier for humans to reason about where that revision lives and where to direct changes / pull requests if things to need to be updated.

**Comment by rminnich** [comment]
Is there an incantation of the govendor tool I can use to make that happen? We might want to document it somewhere. I'm probably using it wrong :-)

**Pull request merged**
