### PR TITLE
[scripts/checlicences] Generalized tool to be used in other projects

### PR DESCRIPTION
**Pull request by insomniacslk**
Signed-off-by: Andrea Barberio <insomniac@slackware.it>

### CODE REVIEW

**Comment by insomniacslk** [comment]
Local run:
```
$ go run scripts/checklicenses/checklicenses.go -c scripts/checklicenses/config-example.json 
$
```

TODO:
* rename config file
* modify invocation in circleCI config

**Comment by rjoleary** [comment]
This looks good, but circleci is failing. Looks to be a failure in the dmesg test which is unrelated. Perhaps rebasing and resolving the conflicts will help?

**Comment by insomniacslk** [comment]
yeah the failures were due to wrong paths on my side... now I've used the right path, repo, and rebased from upstream

**Comment by insomniacslk** [comment]
wrong path to the JSON config, update incoming

**Comment by insomniacslk** [comment]
alright, should be good now. Waiting for tests

**Comment by insomniacslk** [comment]
tests are green now. @rjoleary PTAL. Thanks!

**Pull request merged**
