### PR TITLE
travis: add 1.x instead 1.9 to go version

### PR DESCRIPTION
**Pull request by dvrkps**

### CODE REVIEW

**Comment by rminnich** [comment]
I need a bit more rationale for this. We've seen cases where we could not move forward until we redid some vendor bits. What's the purpose of this change?

**Comment by dvrkps** [comment]
Hi @rminnich 
1.x means latest stable go version.
Maybe 1.9.x is better for cases you mention.

**Comment by hugelgupf** [comment]
I'm actually not 100% sure all our programs are currently Go 1.9 compatible, especially given some of the non-standard use of os.OpenFile / os.Open and the new polling mode that is used there.

Regardless, I think it's better to explicitly state the version we support, and explicitly upgrade when a new version comes out to ensure compatibility.

**Comment by rminnich** [comment]
I'd be more comfortable with what chris is saying. automagic compiler version upgrades are dangerous.

**Comment by dvrkps** [comment]
@hugelgupf you can squash commits on merge button options.

**Comment by rminnich** [comment]
dvrkps are you able to push (I guess not?) Do you want to have that capability?

**Comment by dvrkps** [comment]
@rminnich no need for this right now. thx.

**Pull request merged**
