### PR TITLE
Add Go 1.15 to supported list

### PR DESCRIPTION
**Pull request by rjoleary**
Signed-off-by: Ryan O'Leary <ryan@ryanoleary.ca>

### CODE REVIEW

**Comment by hugelgupf** [comment]
I'd rather we test and continue to guarantee that Go 1.13 works. Why the switch? If we test with 1.15 we'll start using features only in 1.15 too.

**Comment by rjoleary** [comment]
According to https://golang.org/doc/devel/release.html#policy, go1.13 is not longer supported since go1.15 was released.

**Comment by hugelgupf** [comment]
That doesn't mean we have to stop supporting it. Plenty of users don't really move as fast as Go releases officially do.

**Comment by rjoleary** [comment]
For example, we forced go1.12 just 1 month after it was released.

Please create a policy for when to update go. Even if we could keep go1.13 support for ever, I feel we should eventually update.

I changed this to just update the u-root.go.

**Comment by hugelgupf** [comment]
We forced Go 1.12 for a feature we really needed, and i heard from many unhappy users after.

**Review by rminnich — APPROVED** [review]

**Comment by rjoleary** [comment]
Do we have a good idea of which versions of Go are being used for u-root?

**Pull request merged**
