### PR TITLE
Set FullPath in OnePCI function

### PR DESCRIPTION
**Pull request by moson-mo**
FullPath should be set, otherwise the caller has has to set this before being able to call PCI methods relying on FullPath.  
(f.e.: ReadConfigRegister / WriteConfigRegister)

### CODE REVIEW

**Comment by 10000TB** [comment]
pci_test evaded testing this by specifically creating a PCI w/ a FullPath

```
             pci: PCI{
                 FullPath: dir,
             },
```

**Review by 10000TB — DISMISSED** [review]

**Comment by moson-mo** [comment]
I've added another commit for Addr.

**Review by rminnich — APPROVED** [review]

**Review by rminnich — CHANGES_REQUESTED** [review]
Please add a DCO
git commit --amend -s
git push -f 

thanks

**Comment by moson-mo** [comment]
Sorry. Messed it up. Created a new pull request.

**Pull request closed without merging**
