### PR TITLE
Revamp ldd API

### PR DESCRIPTION
**Pull request by hugelgupf**
New:

* ldd.List(paths ..string) -> lists dependency files (interps and dynamic libraries), as named in the given binary.
* ldd.FList(paths ...string) -> like List, but also lists all files pointed to through symlinks in the dependency files.

Neither of them return the original file name in paths anymore.

Removing:

* ldd.List (equivalent is FList, but FList does not list the original file name anymore)
* ldd.Ldd (there is nothing returning FileInfo anymore, because nothing was using it)

### CODE REVIEW

**Comment by rminnich** [comment]
it all looks fine but was there some driving reason or is this part of making things better. 

Also I did stumble on this today:
r.minnich@2840nrd-rminnic tamago-example % otool -L /bin/date
/bin/date:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.0.0)

This is on osx. I wonder if we should use it when runtime.GOOS=darwin and our target is darwin?

**Review by rminnich — COMMENTED** [review]
Is the behaviour of the lddfiles command still the same? Printing the file name was useful in scripts.

**Comment by hugelgupf** [comment]
> Is the behaviour of the lddfiles command still the same? Printing the file name was useful in scripts.

I can add that back.

> it all looks fine but was there some driving reason or is this part of making things better.

Yes, I couldn't get a list of just the un-followed symlink files out of the current API for https://github.com/warptools/ldshim/pull/2

**Comment by hugelgupf** [comment]
PTAL

**Comment by rminnich** [comment]
if you can add it back, that would be nice. A common usage pattern is something like
lddfiles /bin/this /bin/that | cpio -o
and it's critical that /bin/that and /bin/that be included. That should probably be a test ...

**Comment by hugelgupf** [comment]
I already added it back

**Review by rminnich — APPROVED** [review]

**Pull request merged**
