### PR TITLE
Move less-maintained boot commands

### LINKED ISSUE #2142: "localboot -grub" can't boot arm64 platforms with Centos and Ubuntu
**Describe the bug**

 Boot CentOS and Ubuntu by "localboot -grub" command on Ampere jade(linuxboot) with linuxboot,  CentOS reports "No boot configuration found",  Ubuntu reports "Exception: localboot exited with 1"

1970/01/01 00:24:05 mounted: [MountPoint(path=/mnt/nvme0n1p1, device=/dev/nvme0n1p1, fs=vfat, flags=0x1, data=) MountPoint(path=/mnt/nvme0n1p2, device=/dev/nvme0n1p2, fs=ext4, flags=0x1, data=)]
1970/01/01 00:24:05 Parsing /mnt/nvme0n1p1/EFI/centos/grub.cfg
1970/01/01 00:24:05 Parsing /mnt/nvme0n1p2/grub2/grub.cfg
1970/01/01 00:24:05 No boot configuration found
Exception: localboot exited with 1

Even Ubuntu 20.04 has menuentry after 30_0s-prober in the /boot/grub/grub.cfg, still reports below failure:
1970/01/01 00:01:39 Found 5 boot configs
1970/01/01 00:01:39   0: 'Ubuntu'
1970/01/01 00:01:39   1: 'Ubuntu, with Linux 5.4.0-88-generic'
1970/01/01 00:01:39   2: 'Ubuntu, with Linux 5.4.0-88-generic (recovery mode)'
1970/01/01 00:01:39   3: 'Ubuntu, with Linux 5.4.0-86-generic'
1970/01/01 00:01:39   4: 'Ubuntu, with Linux 5.4.0-86-generic (recovery mode)'
1970/01/01 00:01:39 Cannot open TPM: TPM device not available
1970/01/01 00:01:39 Failed to boot kernel /mnt/nvme0n1p2/vmlinuz-5.4.0-88-generic: kexec.FileLoad() failed: sys_kexec(8, 9, root=/dev/mapper/ubuntu--vg-ubuntu--lv ro, 0) = invalid argument
1970/01/01 00:01:39 Cannot open TPM: TPM device not available
1970/01/01 00:01:39 Failed to boot kernel /mnt/nvme0n1p2/vmlinuz-5.4.0-88-generic: kexec.FileLoad() failed: sys_kexec(8, 9, root=/dev/mapper/ubuntu--vg-ubuntu--lv ro, 0) = invalid argument
1970/01/01 00:01:39 Cannot open TPM: TPM device not available
1970/01/01 00:01:39 Failed to boot kernel /mnt/nvme0n1p2/vmlinuz-5.4.0-88-generic: kexec.FileLoad() failed: sys_kexec(8, 9, root=/dev/mapper/ubuntu--vg-ubuntu--lv ro recovery nomodeset, 0) = invalid argument
1970/01/01 00:01:39 Cannot open TPM: TPM device not available
1970/01/01 00:01:39 Failed to boot kernel /mnt/nvme0n1p2/vmlinuz-5.4.0-86-generic: kexec.FileLoad() failed: sys_kexec(8, 9, root=/dev/mapper/ubuntu--vg-ubuntu--lv ro, 0) = invalid argument
1970/01/01 00:01:39 Cannot open TPM: TPM device not available
1970/01/01 00:01:39 Failed to boot kernel /mnt/nvme0n1p2/vmlinuz-5.4.0-86-generic: kexec.FileLoad() failed: sys_kexec(8, 9, root=/dev/mapper/ubuntu--vg-ubuntu--lv ro recovery nomodeset, 0) = invalid argument
1970/01/01 00:01:39 No boot configuration succeeded
Exception: localboot exited with 1
[tty], line 1: localboot -grub

**To Reproduce**
1.  Build linuxboot for arm64 platforms(Ampere/jade).
2.  Prepare bootable CentOS and Ubuntu.
3.  Type "localboot -grub" after booting into linuxboot.

**Expected behavior**
1. CentOS should be bootable by "localboot -grub"
2. Ubuntu should be bootable by "localboot -grub"

**Additional context**

I compared the /boot/grub/grub.cfg, by default no menuentry from grub.cfg, I can boot CentOS 4.18/5.10 if I add below information into grub.cfg. 

	### BEGIN /etc/grub.d/30_os-prober ###
	menuentry 'CentOS Linux 8 (on /dev/mapper/cl-root)' --class centos --class gnu-linux --class gnu --class os $menuentry_id_option 'osprober-gnulinux-simple-2edb594f-6ced-449e-ba40-7cafa4e1171e' {
	        insmod part_gpt
	        insmod ext2
	        if [ x$feature_platform_search_hint = xy ]; then
	          search --no-floppy --fs-uuid --set=root  3a55a880-6c42-4b8e-8bf0-98f9f17365c4
	        else
	          search --no-floppy --fs-uuid --set=root 3a55a880-6c42-4b8e-8bf0-98f9f17365c4
	        fi
	        linux /vmlinuz-4.18.0xbtian+ root=/dev/dm-2
	        initrd /initramfs-4.18.0xbtian+.img
	}
	
If I launch OS by kexec -l xxx -i xxx -C xx/ kexec -e, all OS(CentOS with kernel 4.18, 5.10, Ubuntu 20.04) can be launched.

### LINKED ISSUE #2483: localboot:No boot configuration found
When I try to boot into the operating system with localboot, I write commands "localboot -grub" and output "trying to mount all the available block devices with all the supported file system types" and "No boot configuration found", which is why. My server can boot into the operating system through grub.
image

### LINKED ISSUE #2487: localboot -grub -d :mounted:[];no boot configuration found
**Describe the bug**
When I run Linuxboot on a server that can boot into the operating system normally, I enter localboot -grub -d on the u-root command line but I can't recognize the hard disk in the system, and when I can directly find the grub configuration on another server and boot into the operating system, is there any problem with localboot?

**u-root command line input
/#localboot -grub -d
/#mounted: []
/#No boot configuration found

**Additional context**
 I really wanna to know why localboot do this ,can you resolve my doubts?Thanks!

### LINKED ISSUE #2911: localboot can't find partition (and thus can't boot)
**Describe the bug**
I made a minimal bootable disk with u-root and grub2 (with a generic kernel)
The disk is made of a single EFI/vfat bootable partition with u-root, grub and the kernel binary
I'm trying to test localboot to load another kernel from another disk.

**To Reproduce**
```
2024/02/08 19:00:26 Device: BlockDevice(name=sda1, fs_uuid=39b3-5c73)
2024/02/08 19:00:26 Device: BlockDevice(name=sr0, fs_uuid=)
2024/02/08 19:00:26 Looking for partition with GUID 39b3-5c73
2024/02/08 19:00:26 no partitions with GUID 39b3-5c73
Exception: localboot exited with 1
[tty 101], line 1: localboot -kernel vmlinuz -guid 39b3-5c73 -d
/#                                                                   root@(none)
```

As you can see, my disk is listed and GUID matches.

**Expected behavior**
Not sure, since I don't know what I should expect if localboot was working :)

I'm sure I'm doing something wrong here

### PR DESCRIPTION
**Pull request by hugelgupf**
`fbnetboot`, `localboot`, and `systemboot` are not well-maintained here upstream. We get questions from people about `localboot` all the time, but as we've merged most `localboot` functionality into `boot` and most current maintainers are more familiar with `boot` and `pxeboot`, let's move them "out" front and recommend those.

Fixes #2911
Fixes #2487
Fixes #2483
Fixes #2142

### CODE REVIEW

**Comment by hugelgupf** [comment]
@binjip978 I can't reproduce the golangci-lint issues locally, can you help?

```
$ go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.2
$ golangci-lint run ./...
$ echo $?
0
```

**Comment by binjip978** [comment]
> @binjip978 I can't reproduce the golangci-lint issues locally, can you help?
> 
> ```
> $ go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.2
> $ golangci-lint run ./...
> $ echo $?
> 0
> ```

To see issues you need to uncomment some checks, for example SA1019 will give you a lot of issues:
```
➜  u-root git:(main) ✗ GOOS=linux GOARCH=amd64 golangci-lint run
pkg/boot/jsonboot/bootconfig.go:47:8: SA1019: strings.Title has been deprecated since Go 1.18 and an alternative has been available since Go 1.0: The rule Title uses for word boundaries does not handle Unicode punctuation properly. Use golang.org/x/text/cases instead. (staticcheck)
	id := strings.Title(strings.ToLower(bc.Name))
	     ^
pkg/crypto/ed25519.go:72:5: SA1019: x509.IsEncryptedPEMBlock has been deprecated since Go 1.16 because it shouldn't be used: Legacy PEM encryption as specified in RFC 1423 is insecure by design. Since it does not authenticate the ciphertext, it is vulnerable to padding oracle attacks that can let an attacker recover the plaintext. (staticcheck)
	if x509.IsEncryptedPEMBlock(block) {
	  ^
pkg/crypto/ed25519.go:73:24: SA1019: x509.DecryptPEMBlock has been deprecated since Go 1.16 because it shouldn't be used: Legacy PEM encryption as specified in RFC 1423 is insecure by design. Since it does not authenticate the ciphertext, it is vulnerable to padding oracle attacks that can let an attacker recover the plaintext. (staticcheck)
		decryptedKey, err := x509.DecryptPEMBlock(block, password)
```

**Comment by binjip978** [comment]
> @binjip978 I can't reproduce the golangci-lint issues locally, can you help?
> 
> ```
> $ go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.2
> $ golangci-lint run ./...
> $ echo $?
> 0
> ```

Ah sorry, don't get it right, I will try to look.

**Comment by binjip978** [comment]
@hugelgupf I can't reproduce it locally either with binary or staticcheck. But issue is gone is version will be 1.52.1 or go 1.22, golangci-lint updated 5 days ago, maybe that's related. Maybe we should stick with 1.52.1.

**Review by johnnylinwiwynn — COMMENTED** [review]
Moving them from cmds/boot to cmds/exp is fine and makes sense to me.

**Comment by hugelgupf** [comment]
> This clears up some confusion, but, still, can we just remove them? Is anyone anywhere using them?
> 
> Exp is kind of "stuff somebody is using" but there's no evidence anyone is using these, or am I missing something.

I think I'll let @johnnylinwiwynn speak on that. For now, I'll just move them. I see that the system boot command has moved to pxeboot and boot for the most part, with a fallback to [fbnetboot](https://github.com/u-root/u-root/blob/0befc99d1c1bc20ceb08c381527332ecdd1d2e2f/cmds/boot/systemboot/main.go#L49). So perhaps we can delete localboot completely?

**Review by binjip978 — APPROVED** [review]

**Pull request merged**
