### PR TITLE
update golangci-lint

### PR DESCRIPTION
**Pull request by binjip978**

### CODE REVIEW

**Comment by binjip978** [comment]
redefines-builtin-id probably worth fixing, but it probably should be separate PR.

**Comment by hugelgupf** [comment]
It'd be nice if we could put this in a golangci-lint yml, and use the golangci-lint github action, which will annotate the PR with code reviews https://github.com/golangci/golangci-lint-action

**Comment by binjip978** [comment]
> It'd be nice if we could put this in a golangci-lint yml, and use the golangci-lint github action, which will annotate the PR with code reviews https://github.com/golangci/golangci-lint-action

yeah, that's a good idea.

**Comment by hugelgupf** [comment]
> > It'd be nice if we could put this in a golangci-lint yml, and use the golangci-lint github action, which will annotate the PR with code reviews https://github.com/golangci/golangci-lint-action
> 
> yeah, that's a good idea.

want me to merge this or do you want to do this as well?

**Comment by binjip978** [comment]
> > > It'd be nice if we could put this in a golangci-lint yml, and use the golangci-lint github action, which will annotate the PR with code reviews https://github.com/golangci/golangci-lint-action
> > 
> > 
> > yeah, that's a good idea.
> 
> want me to merge this or do you want to do this as well?

I think it better to merge this right now, and I will come with .conf file in other PR

**Review by hugelgupf — APPROVED** [review]

**Pull request merged**
