### PR TITLE
Update smbios type 38 I2C Address name

### PR DESCRIPTION
**Pull request by trincty**

### CODE REVIEW

**Review by MDr164 — CHANGES_REQUESTED** [review]
Can you explain the rationale behind this? Also you're missing the DCO aka Sign-Off and also didn't adapt the changes inside the corresponding tests so those fail now.

**Review by rminnich — COMMENTED** [review]
I understand the reason for the change, but we lose some meaning with it. Might you consider
I2cTargetAddress
I2CDestination
I2CDestAddress
to indicate the address is for the device being controlled.
thanks.

**Comment by trincty** [comment]
This change is to match the google internal dmidecode. I need to check if dmidecode accept the change as well. Will update this once I know the answer

**Comment by MDr164** [comment]
Alright, if that's another Google guideline then so be it but I agree to what Ron said, simply removing the term 'slave' without any substitute creates confusion. In addition please also adapt the tests and add a sign off.

**Comment by trincty** [comment]
We came up with conclusion to use I2cTargetAddress. I will create another PR later

**Comment by rminnich** [comment]
this PR is starting to look abandoned?

**Comment by rminnich** [comment]
I am assuming this is abandoned

**Pull request closed without merging**
