### PR TITLE
Do not print every ping of the watchdog

### PR DESCRIPTION
**Pull request by rjoleary**
This was way too verbose.

Signed-off-by: Ryan O'Leary <ryanoleary@google.com>

### CODE REVIEW

**Review by rminnich — APPROVED** [review]

**Comment by 10000TB** [comment]
/LGTM 

what scenarios we will be annoyed by this print ?, as u-root boot should be pretty fast, Total-time-in-u-root / pet frequency (5s internally) is not a lot in some boot scenarios. But if it does print a lot if it stays in u-root for a long time, e.g. without rand number generator, it waits up to 6 minutes for DHCP, then there are 6 minutes / 5 s number of such prints. But missing of the rand number generator was an issue at first.

**Review by 10000TB — APPROVED** [review]
what scenarios we will be annoyed by this print ?, as u-root boot should be pretty fast, Total-time-in-u-root / pet frequency (5s internally) is not a lot in some boot scenarios. But if it does print a lot if it stays in u-root for a long time, e.g. without rand number generator, it waits up to 6 minutes for DHCP, then there are 6 minutes / 5 s number of such prints. But missing of the rand number generator was an issue at first.

**Comment by rjoleary** [comment]
> what scenarios we will be annoyed by this print ?, as u-root boot should be pretty fast, Total-time-in-u-root / pet frequency (5s internally) is not a lot in some boot scenarios. But if it does print a lot if it stays in u-root for a long time, e.g. without rand number generator, it waits up to 6 minutes for DHCP, then there are 6 minutes / 5 s number of such prints. But missing of the rand number generator was an issue at first.

One scenario is when the boot menu is printed and there's a watchdog print overlapping it. Or at the shell and the watchdog print happens while the user is typing.

**Comment by 10000TB** [comment]
ah, now I recall, the printing after entering shell, IS super annoying

**Pull request merged**
