### PR TITLE
add pack to the tools

### PR DESCRIPTION
**Pull request by rminnich**
add pack to the tools
This is disappointing, but it seems we need a 5th binary, pack.

### CODE REVIEW

**Comment by rminnich** [comment]
add pack to the tools
This is disappointing, but it seems we need a 5th binary, pack.

**Comment by hugelgupf** [comment]
What does pack do?

**Comment by bensallen** [comment]
@hugelgupf 

I believe its referring to:

> The final step is to pack the object file into an archive file, .a, which the linker and the compiler consume.

Ref: https://dave.cheney.net/2013/10/15/how-does-the-go-build-command-work

**Comment by rminnich** [comment]
what makes no sense here is this was not needed with the old ramfs.go, so we're doing something wrong.

**Comment by rminnich** [comment]
Good news, it's just a go toolchain bug: https://github.com/golang/go/issues/22819

Those folks may decide it's not a bug. But we can fix by creating an empty pack command. Gross.

**Pull request closed without merging**
