### PR TITLE
Remove redundant implementation of rsdp in pkg/boot/acpi - 2. Try

### PR DESCRIPTION
**Pull request by ChriMarMe**
Signed-off-by: Christopher Meis <christopher.meis@9elements.com>

### CODE REVIEW

**Comment by ChriMarMe** [comment]
Ah. I see things failing. <3 love it

**Comment by ChriMarMe** [comment]
More failing. Really enjoy the pain here <3

**Comment by ChriMarMe** [comment]
Well....... sucks to be me I guess.

**Comment by rminnich** [comment]
the failures are in the github actions, not required. We need to get them fixed however.

**Review by rminnich — APPROVED** [review]

**Pull request merged**
