### PR TITLE
cmds/core/gosh: reintroduce nocomp mode without bubbline

### PR DESCRIPTION
**Pull request by MDr164**
It showed that this library causes quite a few issues in automated test, so the default will be the plain sh interactive mode which is much more slimmed down. Bubbline can be enabled during runtime still using the comp flag.

### CODE REVIEW

**Comment by rminnich** [comment]
it turned out completion was not the only issue, which is why I renamed things. bubbline insists on putting out all this ansi foo, for its fancy prompts and such, and that caused trouble for testing scripts. Also there was the size issue. 

So, I'd suggest it is not about completion, it is about complexity, and I like your use of the name simple. 

We ought to find a way to integrate this with the stuff I upstreamed already. One question, though: the code I upstreamed works. Given that, what is the extra value of this PR? What am I missing?

**Comment by MDr164** [comment]
I was ooo yesterday. I already thought of a way integrating your change. Let me rebase this PR so we can choose between bubbline and no editline implementation for automated testing via a fleg/env var without any regression in shell parsing functionality.

**Comment by jelischer** [comment]
I have implemented a change within google that does this but using the old "prompt" code in our copy.
I will try put it here for reference:
I used the termios package, though it required one tiny change to be useable with gosh as a root shell.
(ability to take an existing os.file and 'wrap' it as a TTYIO)

**Review by rminnich — APPROVED** [review]
this looks a lot better than what I did.

**Comment by rminnich** [comment]
it appears you want to do more, and now I wonder: 
can we get rid of vendor/ yet
I am going to try

**Review by rminnich — APPROVED** [review]

**Review by rminnich — APPROVED** [review]

**Pull request merged**
