### PR TITLE
The Big Merge -- Welcome SystemBoot

### PR DESCRIPTION
**Pull request by hugelgupf**
DO NOT MERGE.

TODO
 * not sure what to do with uinit yet
 * move Travis CI integration test to our u-root integration test framework.
 * review u-root dependency list with systemboot stuff. we're bloating a lil.

PLS REVIEW
 * placement of commands in directory structure
 * [New README](https://github.com/u-root/u-root/blob/a31ee378cab314841355a55a16ca39933b33b510/README.md)

NOTES
 * I will force the DCO check to pass for this tree.

cc @zaolin @tfg13 @insomniacslk @rminnich @rjoleary @jensdrenhaus 

DO NOT MERGE.

### CODE REVIEW

**Comment by tfg13** [comment]
LGTM. I think the only thing really missing from our side is the travis fix. I can give that a shot if you want.

**Comment by jensdrenhaus** [comment]
With "The Big Move" and restructuring the cmds directory, when using bb mode, why is the source code of the commands copied two times. For example for `cmds/core/cat/cat.go` there is `cmds/core/cat/.bb/cat.go` as well as `cmds/cat/.bb/cat.go`. This is true for every command except `cmds/boot/boot/boot.go` , maybe due to naming conflicts?! I think it could possibly also be the reason for #1252

**Comment by hugelgupf** [comment]
@jensdrenshaus -- oh wow.

cmds/cat/.bb is likely leftover in your *local* tree from the last bb build you did. You can safely delete all of those.

We should consider deleting them after every build, but it's also a great debugging tool.

**Comment by tfg13** [comment]
Yup, I think there is a separate issue open for leftover .bb files somewhere. We have a dirty shellscript to clean them up, and it is a bit annoying - but shouldn't be related to this PR

**Comment by jensdrenhaus** [comment]
Yes, you are right. The duplicates were leftovers from the old directory structure, so it doesn't matter anyway.

**Pull request closed without merging**
