### PR TITLE
Remove unused files

### PR DESCRIPTION
**Pull request by hugelgupf**
These haven't been updated in a long time.

### CODE REVIEW

**Review by rminnich — COMMENTED** [review]
I use the configs pretty frequently. They still work. Are you sure we want to remove them?

**Comment by rminnich** [comment]
part of the reason they have not  been updated is they are so minimal, but, key point, they still work :-) I'm not really sure we want to delete them.

**Comment by hugelgupf** [comment]
> part of the reason they have not been updated is they are so minimal, but, key point, they still work :-) I'm not really sure we want to delete them.

yeah that's fair I'll update the PR

**Comment by hugelgupf** [comment]
PTAL

**Review by rminnich — APPROVED** [review]
pour another one out for source mode ... :-) thanks!

**Pull request merged**
