### PR TITLE
cmds/exp/bzimage: change to use standard Go flag package

### PR DESCRIPTION
**Pull request by rminnich**
…p using it

in u-root, we set flag.Usage to be called when a usage is wrong.

spf13/flag will exit in at least one place without calling flag.Usage,
which means our usage message will not be printed.

Our use of spf13/flag in this command is not sophisticated
enough to require it, so stop using it.

This way, we get real usage error message.

Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>

### CODE REVIEW

**Comment by 10000TB** [comment]
kexec cmd still uses it -- "stop using it" meaning stop it just for bzimage cmd ? or as a general preference ?

If we have some cmds (e.g. `kexec`) allowing for POSIX / GNU style flags, while others (e.g .`bzimage`) not, it will be confusing

**Review by 10000TB — COMMENTED** [review]
kexec cmd still uses it -- "stop using it" meaning stop it just for bzimage cmd ? or as a general preference ?

If we have some cmds (e.g. kexec) allowing for POSIX / GNU style flags, while others (e.g .bzimage) not, it will be confusing

**Comment by 10000TB** [comment]
Perhaps, we should conceptually agree all our commands should allow POSIX/GNU style  ?

**Comment by rminnich** [comment]
> kexec cmd still uses it -- "stop using it" meaning stop it just for bzimage cmd ? or as a general preference ?
> 
> If we have some cmds (e.g. kexec) allowing for POSIX / GNU style flags, while others (e.g .bzimage) not, it will be confusing

posix flags don't require long flags. We use the flag package in 138 places, and spf13 flags in 35, so all we're doing here is deciding not to use spf13 in this command. 

I cleaned up the commit language.

**Review by 10000TB — APPROVED** [review]
Is it worth reporting the finding in an issue ? https://github.com/spf13/pflag/issues --- It claims to be a drop-in replacement for std flag, not calling flag.Usage in places seems a big counter example that they would fix

**Comment by rminnich** [comment]
it's worse than I thought. If you use spf13/flag, you can NOT call the uroot Util function, b/c it uses "flag"

so if a user uses spf13/flag, and calls util.Usage(usage), they're going to set usage in the go standard flag package, NOT in spf13/flag package. This will never work as expected. 

I think we should try to remove all use of spf13/flag in u-root, OR remove the github.com/u-root/u-root/pkg/uroot/util usage code, because there is no way I can see to use these safely together.

**Pull request merged**
