### PR TITLE
Adding BLS boot entry parsing

### PR DESCRIPTION
**Pull request by pallaud**
Adding library for parsing Boot Loader Specification entries

Based on the spec at https://systemd.io/BOOT_LOADER_SPECIFICATION/

This builds on the work in https://github.com/u-root/u-root/pull/1283 but makes a few modifications, namely using boot.LinuxImage instead of BootConfig, and making this a separate package

Signed-off-by: pallaud <plaud@google.com>

### CODE REVIEW

**Comment by pallaud** [comment]
Still needs to be done: adding parsing for EFI entries and more extensive tests

**Comment by GanShun** [comment]
I would like this to be merged soon, so we can test it for some use cases. Can you fix this up? thanks. We can separate this from the EFI target support

**Comment by hugelgupf** [comment]
Not mentioned in the spec is this configuration file: https://www.freedesktop.org/software/systemd/man/loader.conf.html

**Comment by hugelgupf** [comment]
We're picking up BLS because we're trying to boot Fedora/RHEL with someone, but it turns out Fedora has made some unfortunate choices in the bootloader realm lately.

Fedora now supports the BootLoaderSpec. That's awesome. However, they support kind of a [bastardized version](https://github.com/systemd/systemd/issues/15029#issuecomment-607691208). The BLS entry files in Fedora are unfortunately littered with references to GRUB variables, see [example here](https://fedoraproject.org/wiki/Changes/BootLoaderSpecByDefault#Config_files_provided_by_kernel.2C_grub2-switch-to-blscfg.2C_and_zipl-switch-to-blscfg).

That means to parse its BLS entries, you must parse GRUB first, and then interpret the BLS entries in reference to the GRUB vars. Bummer! This PR does not attempt to solve that.

You can, however, fix the BLS entries in Fedora and install systemd-boot as your main bootloader, which as a side-effect will also allow booting with u-root using this PR:

```
dnf remove grub2*
bootctl install
rm -rf /boot/loader # do this so bootctl won't assume these entries are already there, when they're in the wrong partition
kernel-install add $(uname -r) /lib/modules/$(uname -r)/vmlinuz
```

And with that, we have boot from a Fedora 32 kernel:

```
~/> boot                                                                                                           
EXT4-fs (sda): VFS: Can't find ext4 filesystem                                                                                                                                                                                         
EXT4-fs (sda): VFS: Can't find ext4 filesystem                                                                                                                                                                                         
EXT4-fs (sda): VFS: Can't find ext4 filesystem                                                                     
squashfs: SQUASHFS error: Can't find a SQUASHFS superblock on sda                                                  
FAT-fs (sda): bogus number of reserved sectors                                                                     
FAT-fs (sda): bogus number of reserved sectors                                                                     
XFS (sda): Invalid superblock magic number                                                                         
EXT4-fs (sda1): VFS: Can't find ext4 filesystem                                                                    
EXT4-fs (sda1): VFS: Can't find ext4 filesystem                                                                    
EXT4-fs (sda1): VFS: Can't find ext4 filesystem                                                                    
squashfs: SQUASHFS error: Can't find a SQUASHFS superblock on sda1                                                 
2020/06/14 10:10:10 Fetching file:///tmp/u-root-boot192944726/dev/sda1/EFI/fedora/grub.cfg                         
2020/06/14 10:10:10 Got config file file:///tmp/u-root-boot192944726/dev/sda1/EFI/fedora/grub.cfg                  
2020/06/14 10:10:10 Failed to parse syslinux configs: no valid syslinux config found on /tmp/u-root-boot192944726/dev/sda1
2020/06/14 10:10:10 BootImage: LinuxImage(                                                                                                                                                                                             
  Name: Fedora 32 (Server Edition) 5.6.6-300.fc32.x86_64                                                           
  Kernel: /tmp/u-root-boot192944726/dev/sda1/de8380606ce44a2dabad127eb049acbe/5.6.6-300.fc32.x86_64/linux          
  Initrd: /tmp/u-root-boot192944726/dev/sda1/de8380606ce44a2dabad127eb049acbe/5.6.6-300.fc32.x86_64/initrd                                                                                                                             
  Cmdline: root=UUID=b0b50629-c323-40de-9b01-05632be6dbd4 ro resume=UUID=abf0a2b5-f8db-411b-b534-1a431c63fbc0 console=ttyS0
)                                                                                                                                                                                                                                      
2020/06/14 10:10:10 Kernel: /tmp/nerf-netboot859423677                                                             
2020/06/14 10:10:10 Initrd: /tmp/nerf-netboot697149944                                                             
2020/06/14 10:10:10 Command line: root=UUID=b0b50629-c323-40de-9b01-05632be6dbd4 ro resume=UUID=abf0a2b5-f8db-411b-b534-1a431c63fbc0 console=ttyS0
kexec_core: Starting new kernel                                                                                                                                                                                                        
[    0.000000] Linux version 5.6.6-300.fc32.x86_64 (mockbuild@bkernel03.phx2.fedoraproject.org) (gcc version 10.0.1 20200328 (Red Hat 10.0.1-0.11) (GCC)) #1 SMP Tue Apr 21 13:44:19 UTC 2020
[    0.000000] Command line: root=UUID=b0b50629-c323-40de-9b01-05632be6dbd4 ro resume=UUID=abf0a2b5-f8db-411b-b534-1a431c63fbc0 console=ttyS0  
```

**Comment by hugelgupf** [comment]
@rjoleary @pallaud @ganshun PTAL

**Comment by hugelgupf** [comment]
Once #1702 makes it in, we can also address the fact that it's only supposed to boot from EFI System Partitions.

**Comment by pallaud** [comment]
It won't let me approve because I'm still listed as the author, but this looks good to me!

**Pull request merged**
