### PR TITLE
[WIP] Swapout netlink package

### LINKED ISSUE #1186: Swap out netlink library
Similarly to https://github.com/insomniacslk/dhcp/issues/257 we want to use github.com/jsimonetti/rtnetlink instead of github.com/vishvananda/netlink . CC @jsimonetti who's already working on this

### PR DESCRIPTION
**Pull request by jsimonetti**
Fixes #1186

This PR will swap out vishvananda/netlink in favor of jsimonetti/rtnetlink.
It is functionally complete.

I am unsure about the `route add` subcommand and made some educated guesses about what the functionality should be. I am confused that the nexthop needs to be a CIDR instead of an IP.
Please be sure to review that part with additional scrutiny.

All other commands reflect the original commands output and function. Some additional formatting and info was added to the `neigh` and `link` subcommands so more closely resemble iproute2.

### CODE REVIEW

**Comment by hugelgupf** [comment]
Thanks! I think after this, it'd just be dhclient/pxeboot that are left with the other netlink.

We need to spend a little bit of time looking at the address add scenario before we can approve.

**Comment by jsimonetti** [comment]
I just saw I screwed up the go dep files. I do apologize for this.
I am unfortunately not well versed in dep and are a bit at a loss how to properly fix this. I hope someone can instruct me on how to properly address the circleci failure.

This change depends on the (as of this writing) latest master of both jsimonetti/rtnetlink aswell as golang.org/x/sys/unix.

**Comment by jsimonetti** [comment]
@hugelgupf looking at dhclient, you can probably use the standard libs `net.Interfaces()`  to accomplish the same result.

**Comment by hugelgupf** [comment]
See Configure: https://github.com/u-root/u-root/blob/master/pkg/dhclient/dhcp4.go

**Comment by insomniacslk** [comment]
Shall we rebase this work on the new `rtnl` wrapper in your library?

**Comment by insomniacslk** [comment]
(cc @jsimonetti and @yarikk )

**Comment by jsimonetti** [comment]
Yes, will rebase this to rtnl package.

**Comment by rjoleary** [comment]
Please feel free to reopen if there's an update.

**Pull request closed without merging**
