### PR TITLE
This is Ryan's build-v2 updated

### PR DESCRIPTION
**Pull request by rminnich**

### CODE REVIEW

**Comment by rminnich** [comment]
sadly, on osx, I hit too many open files almost immediately. Unix being the piece of shit that it is, using a fixed errno instead of a string like "you have 256 files open and that's too many", we don't know HOW many files were open as we do not have errstr on unix. 

We need an implementation of file that, on open, does the open, reads a byte, records that fact, and then close the file. Then, for each read, it opens the file, does the read, closes it. That would solve this problem.

**Comment by lzrd** [comment]
Don't check-in that binary blob.

The kernel source contains a tool usr/gen_init_cpio and a wrapper script scripts/gen_initramfs_list.sh that are provided precisely to generate an initramfs without having to create all the files on the filesystem, and thus to generate an initramfs without requiring any privilege.

**Comment by rminnich** [comment]
The kernel support won't help in the chroot/unshare case, but I I'll work out something.

**Comment by rminnich** [comment]
ok I know what to do, fix coming tomorrow or so

**Comment by rminnich** [comment]
btw I want a solution that "doesn't just work on linux" in the event that I want to target bsd some day. u-root should be able to do that

**Comment by rjoleary** [comment]
What is the progress on this?

**Comment by hugelgupf** [comment]
This still active? I really like the idea of one utility instead of many, and if you want I'll take it over.

**Comment by rminnich** [comment]
yes please. 

you'll need to bring it up to date with other things I've since added to ramfs.go and bb.go, like the new -cmds switch to bb, but yeah, this would be nice to have.

**Comment by rjoleary** [comment]
Yes! Please work on it.

I haven't been keeping real good up to date on what's been going on.

The problem before was that Ron's Mac does not have enough file descriptors to open all the files at once. The per-process default is small and we'd rather not haggle people about running some ulimit command.

The solutions was to implement an `io.Reader` which does "just-in-time" opening of files. Open does not open the file, it merely stores the filename. The first call to `Read` opens the file, and when `Read` returns eof, the file is closed immediately. I forget what Ron named the type - it might have been "stateless" or "onehot".

**Comment by hugelgupf** [comment]
I'm going to take the ideas from this and use them to merge scripts/ramfs.go and bb.go, once my ramfs refactor (#404) gets a little further.

**Pull request closed without merging**
