### PR TITLE
Fix kmodule uncompress code

### PR DESCRIPTION
**Pull request by rminnich**

### CODE REVIEW

**Review by leongross — COMMENTED** [review]
I think the idea of abstracting golang/tinygo differences behind the pgzipinit function is a good idea to reduce unnecessary code duplication. What I am not satisfied with is the naming. The `p` in `pgzip` stands for parallel(ized), in the case of tinygo this is not correct. How about we rename it just to `gzip` or something entirely different?

**Comment by rminnich** [comment]
leon, good point, however, I suspect at some point tinygo will get some sort of pgzip, and then it would be correct. Plus, I think gzip is already taken? 

Not sure I like gzip, but what do others think.

**Comment by rminnich** [comment]
FYI, this fixes insmod so it works with plain .ko again, I'm using it today.

**Comment by rminnich** [comment]
Leon, you were right, what was I thinking ....

fixed I hope

**Review by binjip978 — APPROVED** [review]
I think `generateCompressionTestData` should be a test helper, but it used only once, so  not a big deal.

**Comment by rminnich** [comment]
I'll look at that test helper issue, but for now, I want to get this in, since pkg/kmodule has been broken for 3 months ...

**Pull request merged**
