### PR TITLE
tcz: Bump tinycore to 10.x

### PR DESCRIPTION
**Pull request by bluecmd**
10.x is the current version.

### CODE REVIEW

**Comment by bluecmd** [comment]
Currently untested, if somebody could give this a run that would be nice.

**Comment by rjoleary** [comment]
@bluecmd The last line in your commit has to say "Signed-off-by:" and not "Signed-off:".

**Comment by bluecmd** [comment]
Woops! I usually use the `-s` but must have manually done it this time.
Sorry for not having time to test this, I've been traveling. I'll put it on my todo list for next week.

**Comment by rminnich** [comment]
we can revive this but it seems to have been dropped.

**Pull request closed without merging**
