### PR TITLE
Add nvidia dcgm

### PR DESCRIPTION
**Pull request by rminnich**
Also, add a node about how to disable external tools from ghw.

### CODE REVIEW

**Comment by rminnich** [comment]
what's going to have to be figured out here: from the start, u-root builds with CGO_ENABLED=0, partly because dynamic compilation, partly because we wanted to be insulated from the problems of C.

The NVIDIA DCGM packages requires cgo. So, this will require some build tag fooling around.

**Review by 10000TB — APPROVED** [review]
Nice -- I was curious where is this pkg used, or what triggered this PR ? 

During boot stage where we run u-root tools, any idea how telemetry are going to be used ?

simply print them out to console seems one way to go, if the log noise is accepted.

**Comment by 10000TB** [comment]
some of the CI seems angry..

**Comment by rminnich** [comment]
it's because the dcgm packages require cgo. I'm still thinking about what to do.

**Comment by rminnich** [comment]
I doubt this will ever be used.

**Pull request closed without merging**
