### PR TITLE
Idea on how to fix: fork syscall bug 

### PR DESCRIPTION
**Pull request by robertmin1**
Adding unix.PTRACE_O_TRACEEXEC to the Ptrace Options fixes the fork issue. This will enable us to avoid seeing the SIGTRAP signal. This option tells ptrace to generate a SIGTRAP signal immediately before a new program is executed with the execve system call.

Fixes:  #2670 #2635 and #2590 

Signed-off-by: Robert Mindo <mindo.robert1@gmail.com>

### CODE REVIEW

**Comment by JeremyRand** [comment]
Concept ACK, but would be nice to add the `execve` test case to the tests, so that we don't risk a regression in the future.

**Review by rminnich — COMMENTED** [review]
nice catch! Please sign off and we can get it in!

**Comment by rminnich** [comment]
yes, please add a test.

**Comment by robertmin1** [comment]
Alright, I will work on that

**Comment by robertmin1** [comment]
Since the current `fork.c` is similar to our test file, we can replace it, instead of implementing another test.

**Review by rminnich — APPROVED** [review]

**Review by rminnich — APPROVED** [review]

**Pull request merged**
