### PR TITLE
pkg/mount: determine fstype using statfs type

### PR DESCRIPTION
**Pull request by binjip978**

### CODE REVIEW

**Comment by binjip978** [comment]
an idea how to fix https://github.com/u-root/u-root/issues/3072

**Review by rminnich — COMMENTED** [review]
looks pretty reasonable to me.

**Review by rminnich — APPROVED** [review]
Does this fix that other problem? It seems so.

**Comment by binjip978** [comment]
> Does this fix that other problem? It seems so.

I think it solves only procfs, because devtmpfs is not in the list, but I think it can be added separately.

**Pull request merged**
