### PR TITLE
Turned on TestDeadProcess for circleci

### PR DESCRIPTION
**Pull request by shikharvashistha**
Greetings of the @rminnich,

I've made the necessary changes, kindly review the pull and suggest changes if any.

Thanks & Regards
@shikharvashistha

Fixes : #2175

### CODE REVIEW

**Comment by rminnich** [comment]
It looks like you turned it on but did not in fact fix the underlying problem. If this PR fails I will close it, please come back with a real fix if you can figure out why it is failing. Thanks.

**Comment by rminnich** [comment]
note that you can run tests locally too, did you try that? We were unable to see any reason for this test to fail, but it does in circleci. We just don't understand why.

**Comment by rminnich** [comment]
This looks like a drive-by commit that did not in fact fix anything :-(

If you are interested in fixing the real problem, I'd love to have you take a look. Thanks, closing this PR.

**Comment by shikharvashistha** [comment]
> This looks like a drive-by commit that did not in fact fix anything :-(
> 
> If you are interested in fixing the real problem, I'd love to have you take a look. Thanks, closing this PR.

Kindly give me some time to investigate the issue please.

**Pull request closed without merging**
