### PR TITLE
circleci: Upgrade kernel to 5.10

### PR DESCRIPTION
**Pull request by rjoleary**
Also remove the "new trick" from the docker hub readme. Docker hub does
not do builds for free anymore.

Signed-off-by: Ryan O'Leary <ryanoleary@google.com>

### CODE REVIEW

**Comment by rjoleary** [comment]
Fixes #2075

**Comment by rjoleary** [comment]
```
    integration.go:146: 2021/09/13 19:34:20 serial: 2021/09/13 19:34:19 Tests failed: test.elv ran unsuccessfully: exit status 2~
```

**Comment by rjoleary** [comment]
This info is a bit more useful. In `TestMountKexec`:

```
    integration.go:146: 2021/09/13 19:34:20 serial: 2021/09/13 19:34:19 sys_kexec(11, 13,  console=ttyS0 earlyprintk=ttyS0 uroot.vmtest UROOT_USE_9P=1 KEXEC=Y, 0) = function not implemented~
    integration.go:146: 2021/09/13 19:34:20 serial: Exception: ~[31;1mkexec exited with 1~[m~
```

**Comment by rjoleary** [comment]
> This info is a bit more useful. In `TestMountKexec`:
> 
> ```
>     integration.go:146: 2021/09/13 19:34:20 serial: 2021/09/13 19:34:19 sys_kexec(11, 13,  console=ttyS0 earlyprintk=ttyS0 uroot.vmtest UROOT_USE_9P=1 KEXEC=Y, 0) = function not implemented~
>     integration.go:146: 2021/09/13 19:34:20 serial: Exception: ~[31;1mkexec exited with 1~[m~
> ```

The issue boiled down to KEXEC_FILE now depending on CRYPTO_SHA256.

**Comment by rjoleary** [comment]
I think we have a similar problem for gpio:

```
    integration.go:146: 2021/09/14 02:45:43 serial: === RUN   TestReadValue~
    integration.go:146: 2021/09/14 02:45:43 serial:     gpio_linux_test.go:25: failed to open /sys/class/gpio/export: open /sys/class/gpio/export: no such file or directory~
    integration.go:146: 2021/09/14 02:45:43 serial: --- FAIL: TestReadValue (0.00s)~
```

**Review by rminnich — APPROVED** [review]
but the coverage!

**Pull request merged**
