### PR TITLE
templates: add 'embedded' for embedded system, e.g. ARM gadgets

### PR DESCRIPTION
**Pull request by orangecms**
Note: This template deliberately excludes `sshd`; it could be either added manually or one would use `cpud` instead.

Embedded devices such as IP cameras, NVRs (network video recorders), TV boxes etc may choose this template.

Cheap IP cameras typically have something like 64MB RAM, of which a good third is reserved for image data, leaving ~40MB to the OS and applications, so a small set of utilities can be chosen only. It does work though. :-)

### CODE REVIEW

**Review by rminnich — DISMISSED** [review]

**Comment by orangecms** [comment]
sorry, last one added, which is a must-have for pushing things over from the device: `netcat`

now it's good to go :)

**Comment by orangecms** [comment]
okay, fine, `mkdir` also helps :upside_down_face:

**Comment by orangecms** [comment]
... and `ln` of course

**Comment by orangecms** [comment]
How could I forget `kexec`? :sweat_smile: Finally...
Whatever else may be missing at this point may come from `cpu`.

**Review by rminnich — APPROVED** [review]

**Comment by rminnich** [comment]
remember ... if you have cpu, you don't actually need kexec!

**Pull request merged**
