### PR TITLE
This is the dmesg change rebase.

### PR DESCRIPTION
**Pull request by rminnich**

### CODE REVIEW

**Comment by ryukinix** [comment]
That is okay for, the #38 rebased. @mathgamain, if you can't rebase your fork branch really, we can get that into master. Say to us what you think.

**Comment by rminnich** [comment]
LGTM

let's do it. Git is fuc -- er, I mean fun sometimes.

**Comment by ryukinix** [comment]
HAHAHAHAH!!!

On 03/17/2016 04:49 PM, ron minnich wrote:
>
> LGTM
>
> let's do it. Git is fuc -- er, I mean fun sometimes.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/u-root/u-root/pull/39#issuecomment-198054774>
>

-- 
As lembranças não são só do passado. Podem ser de agora e até de amanhã.
— Serial Experiments Lain
Manoel Vilela,
Discente em Engenharia da Computação[UFPA] - Turma 2014.

**Comment by rafaelcn** [comment]
LOL

**Pull request merged**
