### PR TITLE
[WIP] Systemboot: control debug level via VPD variable

### PR DESCRIPTION
**Pull request by insomniacslk**
Added an additional method to set debug level through the VPD variable
'debug_enabled'. This will behave as follows:
* if -q is explicitly passed (either as true or false), use that
* otherwise, if the VPD variable 'debug_enabled' exists and it is set to
  a valid value (true, false, 1, 0, yes, no - all case-insensitive), use
  that
* otherwise use the default (false)

Signed-off-by: Andrea Barberio <insomniac@slackware.it>

### CODE REVIEW

**Comment by insomniacslk** [comment]
Note: this is still untested

**Comment by jonzhang-fb** [comment]
Instead of debug_enabled, suggest to call it boot_debug_enabled.
FYI that FSP/coreboot debugging is controlled via UPD variable coreboot_log_level.

**Comment by insomniacslk** [comment]
> Instead of debug_enabled, suggest to call it boot_debug_enabled.
> FYI that FSP/coreboot debugging is controlled via UPD variable coreboot_log_level.

Right - having naming consistency would be nice. Currently systemboot simply has debug mode or quiet mode, but I could convert it to log levels and map quiet to warn and debug to.. debug, and leave everything in between as non-debug (i.e. the current "quiet").

coreboot  uses log levels from 1 to 7 (IIRC). What should we use here? Throughout u-root we use the standard `log` library which is not level-aware, and this keeps the code size small. Should we come up with a super-thin layer on top of it, and recommend (but not enforce) its usage in the project? @hugelgupf , what do you think?

**Comment by jonzhang-fb** [comment]
Just for reference, coreboot has log levels defined at : https://review.coreboot.org/cgit/coreboot.git/tree/src/commonlib/include/commonlib/loglevel.h

**Comment by tfg13** [comment]
Continuing this in https://github.com/u-root/u-root/pull/1922

**Pull request closed without merging**
