### PR TITLE
ci: add CIFuzz Github action

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.

This is a service offered by OSS-Fuzz where u-root already runs. CIFuzz can help detect catch regressions and fuzzing build issues early, and has a variety of features (see the URL above). In the current PR the fuzzers gets build on a pull request and will run for 300 seconds.

Signed-off-by: David Korczynski <david@adalogics.com>

### CODE REVIEW

**Comment by RiSKeD** [comment]
Thanks for the PR. This seems to be a great CI action to add:
- Only runs fuzzing tests if affected by PR
- Only fails on reproducible, new bugs

**Review by RiSKeD — APPROVED** [review]

**Comment by rminnich** [comment]
I still don't understand what failed?

**Comment by DavidKorczynski** [comment]
Can you see the issue following the steps here https://google.github.io/oss-fuzz/getting-started/continuous-integration/#understanding-results ?

**Comment by RiSKeD** [comment]
I do not understand either what exactly is failing in this run. 
The artifacts do not provide any failing input or any indication of a failed run in the logs.
Also: Why are all the fuzzing tests being run in the first place? No related code was changed, so in my understanding, no fuzzing test should have been executed.

**Comment by jonathanmetzman** [comment]
Unrelated: @DavidKorczynski can you not include the dry-run line? https://github.com/u-root/u-root/actions/runs/3517053913/workflow#L12 it's unneeded and just clutter.

> > I do not understand either what exactly is failing in this run. The artifacts do not provide any failing input or any indication of a failed run in the logs.
> 
> @jonathanmetzman could you assist here? CIFuzz indicates a crash but there aren't any artifacts or stack traces available?
> 
> > Also: Why are all the fuzzing tests being run in the first place? No related code was changed, so in my understanding, no fuzzing test should have been executed.
> 
> I think this is due to it being the first time CIFuzz runs, @jonathanmetzman can you confirm?

I don't know why a stacktrace is not appearing, that's very bizarre. 
But I think there may be some kind of real failure.
See https://github.com/u-root/u-root/actions/runs/3517053913 how you can download the artifacts zip for fuzz_smbios_parse_info

**Comment by jonathanmetzman** [comment]
It looks like there some kind of really easy to trigger error in the fuzzers now. Not sure if the original issue was a problem with CIFuzz or the fuzzers.

**Comment by DavidKorczynski** [comment]
> It looks like there some kind of really easy to trigger error in the fuzzers now. Not sure if the original issue was a problem with CIFuzz or the fuzzers.

@AdamKorcz is working on this I believe, @AdamKorcz please confirm.

**Comment by AdamKorcz** [comment]
Yes, working on this. Should be fixed shortly.

**Comment by AdamKorcz** [comment]
This has been fixed in latest go-118-fuzz-build. Once https://github.com/google/oss-fuzz/pull/9103 has been merged, we need to wait ~24h and then it should work.

**Pull request merged**
