### PR TITLE
uroot_test: add riscv to the build tests

### PR DESCRIPTION
**Pull request by rminnich**

### CODE REVIEW

**Comment by rjoleary** [comment]
There's a weird error:

```
/usr/local/go/src/internal/cpu/cpu.go:15:30: undeclared name: CacheLinePadSize
```

**Comment by hugelgupf** [comment]
As far as I can tell, riscv64 support in Go 1.13 was not that good. I couldn't get it to work on https://github.com/u-root/gobusybox/pull/37

**Comment by hugelgupf** [comment]
The Go 1.*14* release notes talk about experimental support: https://golang.org/doc/go1.14#riscv

**Comment by rjoleary** [comment]
Ron, can you try building it locally with go1.14? If that works, can we bump the Go version in CircleCI?

**Comment by rjoleary** [comment]
This passes for me with go1.16.4:

```
=== RUN   TestUrootCmdline/RISCV_64bit_bb_build
    uroot_test.go:370: Commandline: [-o /tmp/u-root-456456618 -build=bb all]
    uroot_test.go:370: Commandline: [-o /tmp/u-root-707924588 -build=bb all]
--- PASS: TestUrootCmdline (54.32s)
    --- PASS: TestUrootCmdline/RISCV_64bit_bb_build (54.32s)
PASS
```

I haven't tried 1.14 or 1.15.

**Comment by rjoleary** [comment]
Also passes with go1.15.9

**Review by rjoleary — APPROVED** [review]

**Pull request merged**
