### PR TITLE
bls: boot entry parser

### PR DESCRIPTION
**Pull request by tfg13**
Signed-off-by: Tobias Fleig <tobifleig@gmail.com>

### CODE REVIEW

**Comment by tfg13** [comment]
WIP, stuff to figure out (comments welcome!):

- This should be a library. But I am not sure what to return in that case, we have like 4 different structs that contain kernel, kernelargs and initrd. Madness!
- This won't be able to boot vanilla CentOS, RHEL or Fedora, because they don't comply with their own spec. One needs to pick up the kernel args from a grub file, which is super ugly. Not sure what the best course of action is here.
- The parser has unit tests, the rest needs testing
- Needs to be added to (at least) the systemboot-localboot implementation

**Comment by hugelgupf** [comment]
> This should be a library. But I am not sure what to return in that case, we have like 4 different structs that contain kernel, kernelargs and initrd. Madness

I intend for boot.LinuxImage to be the struct of all Linux structs.

Thoughts?

(In #1241 I will be making the MultibootImage look like LinuxImage with ReaderAt)

**Comment by rjoleary** [comment]
Just a heads up: Since we haven't seen much progress here recently, we plan to close this in 2020. If you have more time, feel free to post an update or reopen the PR.

**Comment by hugelgupf** [comment]
We also to plan to pick up this work in 2020. :)

**Comment by pallaud** [comment]
Closing this because we haven't seen activity - this work is being picked up in #1501!

**Pull request closed without merging**
