### PR TITLE
Build all commands on all GOARCHs in CI

### PR DESCRIPTION
**Pull request by rjoleary**
Signed-off-by: Ryan O'Leary <ryanoleary@google.com>

### CODE REVIEW

**Comment by rjoleary** [comment]
This is probably going to fail until https://github.com/google/go-tpm/pull/147 is merged and vendored.

**Comment by rjoleary** [comment]
It passed because it looks like we don't actually test uroot_test.go. But, we should!

**Comment by hugelgupf** [comment]
> It passed because it looks like we don't actually test uroot_test.go. But, we should!

Oof what? shit!

**Comment by rjoleary** [comment]
I added the test back in.

**Pull request merged**
