### PR TITLE
mount/block: prepare for testing

### PR DESCRIPTION
**Pull request by jensdrenhaus**
Signed-off-by: Jens Drenhaus <jens.drenhaus@9elements.com>

### CODE REVIEW

**Comment by hugelgupf** [comment]
I have a feeling I know where you're going with this...

pkg/mount/block already have some VM tests in the tests for pkg/mount, but they are not being counted for coverage because they are in pkg/mount. 

When I originally opened the PR to add coverage from VM tests in #1958, I moved the tests from pkg/mount that cover pkg/mount/block to pkg/mount/block with the same test setup. See [this commit](https://github.com/u-root/u-root/pull/1958/commits/7bbe699ede506ecdb22c0b1843f7231ca85e9329), and in the PR you can see a couple of follow ups (I had added some tests for Unmount to improve coverage, too). Those commits didn't make it into #2189, apparently

Can we try to improve coverage by adding more tests to the VM tests? Even failure cases are probably coverable in the VM by constructing scenarios that will fail. Tickling failures in mounting and block device code should be relatively easy.

* [pkg/mount test setup](https://github.com/u-root/u-root/blob/main/pkg/mount/mount_integration_test.go) [pkg/mount tests](https://github.com/u-root/u-root/blob/main/pkg/mount/mount_linux_test.go)

**Comment by jensdrenhaus** [comment]
> pkg/mount/block already have some VM tests in the tests for pkg/mount, but they are not being counted for coverage because they are in pkg/mount.
> 
> When I originally opened the PR to add coverage from VM tests in #1958, I moved the tests from pkg/mount that cover pkg/mount/block to pkg/mount/block with the same test setup. See [this commit](https://github.com/u-root/u-root/pull/1958/commits/7bbe699ede506ecdb22c0b1843f7231ca85e9329), and in the PR you can see a couple of follow ups (I had added some tests for Unmount to improve coverage, too). Those commits didn't make it into #2189, apparently
> 
> Can we try to improve coverage by adding more tests to the VM tests? Even failure cases are probably coverable in the VM by constructing scenarios that will fail. Tickling failures in mounting and block device code should be relatively easy.
> 
> * [pkg/mount test setup](https://github.com/u-root/u-root/blob/main/pkg/mount/mount_integration_test.go)
> * [pkg/mount tests](https://github.com/u-root/u-root/blob/main/pkg/mount/mount_linux_test.go)

Yes, already saw that test. I'll move them over here and will add more vmtests. However, I still have lots of regular unittest ready since a while, only need to refactor some due to or "global variable discussion". Since I've already written them, I'll put them in, too. In addition, I'll extend the vmtests.

**Comment by jensdrenhaus** [comment]
> I have a feeling I know where you're going with this...

I picked the wrong commit. This PR should only do code movement. Forget about then paths in global variables.

**Comment by jensdrenhaus** [comment]
> Yes, already saw that test. I'll move them over here and will add more vmtests.

Do I need to touch `integration/gotests/gotest_test.go`? I thought this has nothing to do with package scope test running in QEMU?

**Comment by hugelgupf** [comment]
> > Yes, already saw that test. I'll move them over here and will add more vmtests.
> 
> Do I need to touch `integration/gotests/gotest_test.go`? I thought this has nothing to do with package scope test running in QEMU?

Once you add a specific test setup to pkg/mount/block, you may have to add it to the denylist of gotest_test.go making sure the test doesn't run over there without the proper QEMU setup (the right disks attached etc)

And sgtm on the unit tests

**Comment by jensdrenhaus** [comment]
> Once you add a specific test setup to pkg/mount/block, you may have to add it to the denylist of gotest_test.go making sure the test doesn't run over there without the proper QEMU setup (the right disks attached etc)

I guess that is something we haven't talked/knew about. Thanks for the hint. Stuff like this should be documented. -> #2291

**Comment by jensdrenhaus** [comment]
Addresses #2290

**Comment by jensdrenhaus** [comment]
This PR prepares for writing more unit tests and vm test for mount/block. Therefor, the commits here introduces mainly code movement.

I have also some API changes in mind which I'd like to isolate from the testing stuff, but that's something for a follow-up PR, I think. Anyway, I guess it makes sense to get this PR in first.

**Review by hugelgupf — APPROVED** [review]

**Pull request merged**
