### PR TITLE
Do not terminate fixrsdp when flock fails

### PR DESCRIPTION
**Pull request by GanShun**
Some systems do not have flock enabled, FixRSDP should proceed
regardless.

Signed-off-by: Gan Shun Lim <ganshun@gmail.com>

### CODE REVIEW

**Review by rminnich — APPROVED** [review]

**Comment by rminnich** [comment]
This is weird, I could have sworn I fixed this. I don't see the point of the flock, and this code implicitly says it does not matter -- we warn and continue. Why bother? Your call.

**Review by rminnich — CHANGES_REQUESTED** [review]
let's just remove the flock. It's not needed and when this fails, we'll get one more mysterious noise message no one will understand. It's contrary to the spirit of -Wall -Werror

**Comment by rjoleary** [comment]
> let's just remove the flock. It's not needed and when this fails, we'll get one more mysterious noise message no one will understand. It's contrary to the spirit of -Wall -Werror

Yes, additionally this functionality really should be in the kernel, something like `CONFIG_FIX_RSDP=y`. The kernel has all the facilities, ebda, acpi, rsdp, ... It'd be something like 10 lines during kernel init. Doing a lot of processing on /dev/mem from userspace is probably a bad sign and leads to things like wanting flock.

**Comment by rjoleary** [comment]
Checkout this which removes flock completely: https://github.com/u-root/u-root/pull/2011

**Comment by GanShun** [comment]
Sorry I didn't see this, but the reason I made it a warning is because sometimes the kernel doesn't have FLOCK compiled in. The idea was to use it when we can.

**Pull request closed without merging**
