### PR TITLE
GitHub actions update

### PR DESCRIPTION
**Pull request by MDr164**
This should tackle #2418 and add everything that CircleCI does into GitHub actions.

### CODE REVIEW

**Review by rminnich — DISMISSED** [review]

**Comment by hugelgupf** [comment]
Re test timeouts: I don't know what container sizes you get on GitHub actions, but I pay some dollars a month on CircleCI for us to get more CPU and RAM for certain tests, because otherwise they time out or OOM. [This part of the template](https://github.com/u-root/u-root/blob/2f652f4253a8f61703cb53ab51981c9ec675ca77/.circleci/config.yml#L33)

**Comment by MDr164** [comment]
```
Hardware specification for Windows and Linux virtual machines:

2-core CPU
7 GB of RAM memory
14 GB of SSD disk space
```

That's what the info page tells me. The regular unit tests seem to run faster on Github actions compared to CircleCI while the tests that are building a busybox run slower. The macOS runner is also spec'd a bit higher than the Linux and Windows runners.

**Comment by MDr164** [comment]
I added a function to skip certain tests only in GitHub actions but not in CircleCI. This gives me a bit more time to investigate the failing tests in more detail. Moving the integration tests over will also require additional docker images which don't assume CircleCI as the environment, so maybe we should keep those runs disabled on GitHub action as well until I made those images.

**Comment by MDr164** [comment]
Both CI system are uploading coverage reports to Codecov. Looks like that causes an issue as seen in the drop in coverage. We might need to disable the upload from GH actions before every test works there.

**Comment by walterchris** [comment]
I think you need to squash some commits to satisfy the CI here. Some commits are not signed off.

**Comment by rminnich** [comment]
I should not be able to force push to MDRs branch should I? I did this nonsense on github.

**Review by rminnich — APPROVED** [review]

**Comment by patmaddox** [comment]
#2421 says:

> Remove cirrus ci: It was only used for verifying freebsd buildability. We are going to use github actions for that instead

GitHub actions doesn't officially support FreeBSD as far as I know. [The method I'm aware of](https://github.com/marketplace/actions/freebsd-vm) requires you to run a FreeBSD VM inside of a MacOS instance. That's pretty janky.

Cirrus CI runs directly on FreeBSD machines, so it should probably be re-instated for FreeBSD verification.

**Comment by MDr164** [comment]
I'm currently updating the whole PR with a few better ideas around CI. I would keep running all tests on both CircleCI and GitHub actions for now as they would share common code to run the pipelines. That would also include a general cleanup throughout the CI related code portions. I'll keep you updated here.

**Comment by MDr164** [comment]
I added the CodeCov Orb to our CircleCI project as the bash uploader has been deprecated quite some time ago in favor of the orb. I'll make all the actions pass if possible and then add documentation. After that this PR should finally be good to go.

**Comment by MDr164** [comment]
Will continue on this one this week and see if some of those failures are actually legit test failures that weren't caught before.

**Comment by MDr164** [comment]
Note: This darft will only stay open as a reference to my follow-up PRs that implement an easier path to switching CIs. Those PRs will also be smaller and more incremental.

**Pull request closed without merging**
