### PR TITLE
vendor/netlink: update github.com/vishvananda/netlink to latest master

### PR DESCRIPTION
**Pull request by 10000TB**
...long story, but I have an item that need sth A, which then need sth
B, ... and eventually needing u-root to stay on a latest netlink, which
exposes linkModify via `netlink.LinkModify(link Link)`, which was
previously private only. 

That `netlink.LinkModify(link Link)` landed in netlink master 6 days
ago, so pulling a latest of master.

Ran

`go get github.com/vishvananda/netlink@master`

`go clean -modcache`

`go mod vendor`

then fixed made a tiny fix to ops_linux.go

### CODE REVIEW

**Comment by rjoleary** [comment]
Can you clean up the git commit message, otherwise this looks good :100:

**Comment by 10000TB** [comment]
> Can you clean up the git commit message?

wasn't sure how you suggest cleaning it up. But do I updated it a bit. PTAL

**Comment by rjoleary** [comment]
> > Can you clean up the git commit message?
> 
> wasn't sure how you suggest cleaning it up. But do I updated it a bit. PTAL

Looks good! I was thrown off by the dots ...

**Review by rjoleary — APPROVED** [review]

**Comment by 10000TB** [comment]
I see

in git log it looks like

```
Author: David Hu <xuehaohu@google.com>
Date:   Wed Nov 24 15:19:35 2021 -0800

    vendor/netlink: update vishvananda/netlink.

    ...to latest and fix a build issue in uroot
    so that u-root builds with latest version of
    it.

    Current HEAD of uroot does not build with HEAD
    of vishvananda/netlink.

    Signed-off-by: David Hu <xuehaohu@google.com>
```

I see people do that to connect it as one sentence from headline.

but it does not look good in github webUI

**Pull request merged**
