### PR TITLE
integration: give clear repro steps

### PR DESCRIPTION
**Pull request by hugelgupf**
better developer instructions to clearly let people repro the integration tests locally.

the docker container will take some more work to get right, so let's improve documentation in the meantime.

rendered: https://github.com/u-root/u-root/blob/1dea793ccf1732d78cdbb7798322dca13cf3fda8/integration/README.md

### CODE REVIEW

**Comment by 10000TB** [comment]
What are prerequisites needed for running this integration tests ? (suppose I am on my mac)

**Comment by hugelgupf** [comment]
> What are prerequisites needed for running this integration tests ? (suppose I am on my mac)

Ah yeah. Sorry. These are most likely Linux only. I've never tried it elsewhere.

**Comment by 10000TB** [comment]
but technically, they should run as long as kvm and go are setup on mac ?

**Comment by 10000TB** [comment]
I will be interested in experimenting that and maybe add a section in the README about that

**Comment by hugelgupf** [comment]
> but technically, some of them if not all tests should run as long as kvm and go are setup on mac ?

Theoretically, yes. QEMU on mac won't use kvm, it may (?) have support for some OSX-specific hypervisor -- but you can run QEMU without kvm. It'll just be slow.

I recommend running it on your workstation, though. I'd rather debug the tests than the OSX setup

**Pull request merged**
