### PR TITLE
dd: stop ticker in progress update routine

### PR DESCRIPTION
**Pull request by dennwc**

### CODE REVIEW

**Comment by rminnich** [comment]
I am assuming you've tested this ...

**Comment by bensallen** [comment]
From tick.Tick:

>While Tick is useful for clients that have no need to shut down
>the Ticker, be aware that without a way to shut it down the underlying
>Ticker cannot be recovered by the garbage collector; it "leaks".

Sounds like either the existing tick.Tick or tick.NewTick use is a reasonable approach for dd, as it exits at the same time its done with the Ticker. Just to be a bit safer I say lets go with the changes in this PR.

👍

**Comment by hugelgupf** [comment]
Well, I've always thought about factoring dd out into an externally usable package anyway, so not leaking the ticker is nice to have regardless of the usage in dd right now.

Thanks! Good catch :)

**Comment by hugelgupf** [comment]
@dennwc, could you squash those two commits, as the first one isn't functional? Then this is good to merge :)

**Comment by dennwc** [comment]
Sure :) As a note, Github can now squash PRs automatically on merge

**Pull request merged**
