### PR TITLE
init: only print mount warnings if verbose

### PR DESCRIPTION
**Pull request by hugelgupf**
Most people get confused by these. Not all u-root users need these file
systems mounted. Those that do know who they are.

Signed-off-by: Chris Koch <chrisko@google.com>

### CODE REVIEW

**Comment by fozog** [comment]
Could the code contain "reference" statement in a comment and say that cgroups are optional so that the absence of warning print does not give the impression there is a warning?

**Comment by hugelgupf** [comment]
You're both right.

Proper: we have an init system where the user can indicate whether they need 'em or not. mount or don't mount.

Less proper: perhaps rather than trying to avoid printing them, I should work the word "optional" in there somehow? "optional warning: ..." for each print, or a print like "One or more cgroup mounts failed, ..."?

**Comment by fozog** [comment]
As the LinuxBoot "consumer" is most certainly a contributor at this stage (or a daring boot software adventurer) not masking the warning print seems OK if proper documentation in the code reflects the state of things: depending on the selected init paradigm CGroups or even Name Spaces may be need.

**Comment by hugelgupf** [comment]
updated ptal?

**Pull request merged**
