### PR TITLE
Move stranded tests to correct place

### PR DESCRIPTION
**Pull request by mathgamain**
Signed-off-by: Mateus Pinto Rodrigues <mathgamain@openaliasbox.org>

### CODE REVIEW

**Comment by mathgamain** [comment]
I believe he only moved the which_test.go but not the other 4

**Comment by rminnich** [comment]
LGTM let's see how it goes :-)

**Comment by rminnich** [comment]
weird, no conflicts, well, here we go.

**Comment by rafaelcn** [comment]
Awesome! :smiley:

**Pull request merged**
